// Real local services, synthetic isolated data and mock provider; never original user storage.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',mode=base.includes('github.io')?'prod':'local',receipt=[]
const matrix=[[390,844,100,'light',false],[320,812,140,'light',true],[320,812,200,'light',true],[430,932,140,'dark',true],[390,844,100,'dark',false],[844,390,140,'dark',true]]
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
const write=async(page,data)=>page.evaluate(async data=>{const d=await new Promise((r,j)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data))for(const row of rows)t.objectStore(name).put(row);t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
const read=async(page,name)=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return rows},name)
try{for(const[width,height,scale,colorScheme,reduced]of matrix){
 const context=await browser.newContext({viewport:{width,height},colorScheme,reducedMotion:reduced?'reduce':'no-preference',isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'})
 try{
 await context.addInitScript(()=>{if(!localStorage.getItem('fitlog-ai-active-profile-v1')){const p={id:'catalog-test',name:'合成测试服务',protocol:'openai-chat-completions',baseUrl:'https://mock-catalog.invalid/v1',model:'catalog-model',toolCapability:'supported',createdAt:'',updatedAt:''};localStorage.setItem('fitlog-ai-profiles-v1',JSON.stringify([p]));localStorage.setItem('fitlog-ai-active-profile-v1',p.id);localStorage.setItem('fitlog-ai-key-v1:'+p.id,'synthetic-catalog-key');localStorage.setItem('fitlog-ai-privacy-ack-v1','1')}})
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000)
 const css=`html{font-size:${scale}%} :root{--safe-area-top:47px;--safe-area-bottom:34px}`
 await page.goto(base,{waitUntil:'networkidle'});await page.addStyleTag({content:css});await page.waitForSelector('.sleep-card')
 const shot=async state=>page.screenshot({path:`/tmp/catalog-recovery-${mode}-${width}-${scale}-${colorScheme}-${state}.png`,fullPage:true})
 const bounds=async(selector,chart=false)=>{const result=await page.locator(selector).evaluate((root,chart)=>{const bad=[];for(const e of root.querySelectorAll('*')){if(!e.getClientRects().length||e instanceof SVGElement||(chart&&e.closest('.recovery-chart-scroll')))continue;const r=e.getBoundingClientRect();if(r.left<-.5||r.right>innerWidth+.5)bad.push(e.className);if(e.matches('button,.recovery-number,.recovery-statistics dd')&&e.scrollWidth>e.clientWidth+1)bad.push('clip '+e.className)}return{bad,overflow:document.documentElement.scrollWidth>innerWidth+1}},chart);assert.deepEqual(result.bad,[],`${width}/${scale}/${selector}`);assert.equal(result.overflow,false)}
 // Shared Today grammar and compact sleep action; all underlying cards remain present.
 for(const selector of ['.sleep-card','.water-card']){assert.equal(await page.locator(`${selector}.today-activity-card .today-activity-head .card-icon svg`).count(),1);assert.equal(await page.locator(`${selector} .today-activity-head h2`).count(),1);assert.equal(await page.locator(`${selector} .today-activity-head .text-btn`).count(),1)}
 const grammar=await page.evaluate(()=>{const style=s=>{const e=document.querySelector(s),c=getComputedStyle(e);return{height:c.minHeight,radius:c.borderRadius,padding:c.padding,font:c.fontSize}};return{sleep:style('[data-sleep-action]'),weight:style('#today-record-weight'),headers:['.weight-today-card','.sleep-card','.water-card'].map(s=>{const c=getComputedStyle(document.querySelector(s+' h2'));return[c.fontSize,c.fontWeight,c.lineHeight]}),sleepHeight:document.querySelector('.sleep-card').getBoundingClientRect().height}})
 assert.deepEqual(grammar.headers[0],grammar.headers[1]);assert.deepEqual(grammar.headers[0],grammar.headers[2]);for(const k of ['height','radius','padding','font'])assert.equal(grammar.sleep[k],grammar.weight[k]);if(scale===100)assert.ok(grammar.sleepHeight<170)
 assert.equal(await page.getByText('恢复与习惯',{exact:true}).count(),0);await bounds('[data-recovery-root]');await shot('today-dashboard');for(const [name,selector]of [['training','.workout-today-card'],['weight','.weight-today-card'],['habit','.today-habits-card'],['sleep','.sleep-card'],['water','.water-card']])await page.locator(selector).screenshot({path:`/tmp/catalog-recovery-${mode}-${width}-${scale}-${colorScheme}-today-${name}.png`})
 const manager=await context.newPage();manager.on('pageerror',e=>errors.push(e.message));await manager.goto(base,{waitUntil:'networkidle'});await manager.addStyleTag({content:css});await manager.waitForSelector('.water-card')
 assert.match(await page.locator('[data-water-reference]').innerText(),/2500/);const waterBefore=await read(page,'waterLogs');await page.locator('[data-water-reference-edit]').click();await page.locator('[name=reference]').fill('2000');await bounds('dialog[open]');await shot('reference-editor');await page.locator('[data-water-reference-form] [type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-water-reference]')?.textContent.includes('2000'));await manager.waitForFunction(()=>document.querySelector('[data-water-reference]')?.textContent.includes('2000'))
 await page.locator('[data-water-reference-edit]').click();await page.locator('[data-water-reference-unset]').click();await page.waitForFunction(()=>!document.querySelector('[data-water-reference]'));await manager.waitForFunction(()=>!document.querySelector('[data-water-reference]'));assert.equal((await page.locator('.water-card').innerText()).includes('%'),false);assert.deepEqual(await read(page,'waterLogs'),waterBefore);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('fitlog-water-reference-v1')).referenceMl),null)
 await page.locator('[data-water-reference-edit]').click();await page.locator('[name=reference]').fill('9999');await page.locator('[data-water-reference-cancel]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('fitlog-water-reference-v1')).referenceMl),null);
 const today=await page.evaluate(()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}),localShift=n=>{const d=new Date(today+'T12:00:00');d.setDate(d.getDate()+n);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},stamp=new Date().toISOString()
 await write(page,{sleepSessions:[{id:'range-first',startTime:new Date(localShift(-88)+'T01:00:00+08:00').toISOString(),endTime:new Date(localShift(-88)+'T03:03:00+08:00').toISOString(),durationMinutes:123,recordDate:localShift(-89),createdAt:stamp,updatedAt:stamp},{id:'range-today',startTime:new Date(localShift(-1)+'T23:00:00+08:00').toISOString(),endTime:new Date(today+'T06:36:00+08:00').toISOString(),durationMinutes:456,recordDate:today,createdAt:stamp,updatedAt:stamp}],waterLogs:[{id:'water-first',date:localShift(-89),amountMl:350,timestamp:stamp,createdAt:stamp,updatedAt:stamp},{id:'water-today',date:today,amountMl:500,timestamp:stamp,createdAt:stamp,updatedAt:stamp}]})
 await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await page.locator('[data-tab=progress]').click();await page.waitForSelector('.recovery-trend .recovery-line-chart[data-chart-kind=sleep]')
 const segments=await page.locator('[data-recovery-days]').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return[r.width,r.height]}));assert.ok(segments.every(s=>Math.abs(s[0]-segments[0][0])<1&&s[1]===segments[0][1]))
 for(const days of [7,30,90]){await page.locator(`[data-range-kind="sleep"][data-recovery-days="${days}"]`).click();await page.locator(`[data-range-kind="water"][data-recovery-days="${days}"]`).click();await page.waitForFunction(days=>document.querySelectorAll('.recovery-line-chart[data-chart-kind=sleep] [data-point-date]').length===days,days);assert.equal(await page.locator('.recovery-line-chart[data-chart-kind=sleep] [data-point-date]').count(),days);assert.equal(await page.locator('.recovery-daily').count(),0);assert.equal(await page.locator('.recovery-trend .recovery-statistics').count(),0);for(const kind of ['sleep','water']){assert.equal(await page.locator(`[data-chart-kind=${kind}] .recovery-point-value`).count(),0);assert.equal(await page.locator(`[data-chart-kind=${kind}] [data-point-value]`).count(),await page.locator(`[data-chart-kind=${kind}] .recovery-line-marker`).count())};await bounds('[data-recovery-root]',true);await shot('trend-'+days)}
 const scroll=page.locator('.recovery-chart-long').first();assert.ok(Math.abs(await scroll.evaluate(e=>e.closest('.trend-plot-frame').getBoundingClientRect().height)-162*scale/100)<1);assert.equal(await page.locator('[data-recovery-chart=sleep] [data-point-value]').count(),2);assert.equal(await page.locator('[data-recovery-chart=sleep] .recovery-point-label').count(),0);if(await scroll.evaluate(e=>e.scrollWidth>e.clientWidth)){await scroll.evaluate(e=>e.scrollLeft=1800);assert.ok(await scroll.evaluate(e=>e.scrollLeft>0))}else{assert.ok(await scroll.evaluate(e=>e.scrollWidth<=e.clientWidth));assert.equal(await page.locator('[data-recovery-chart=sleep] [data-point-value]').count(),2)};const firstPoint=page.locator('[data-recovery-chart=sleep] [data-point-value]').first();await firstPoint.focus();await page.keyboard.press('Enter');assert.match(await page.locator('[data-recovery-chart=sleep] [data-chart-value]').innerText(),/2小时3分钟/);await page.keyboard.press('End');assert.match(await page.locator('[data-recovery-chart=sleep] [data-chart-value]').innerText(),/7小时36分钟/);for(let i=0;i<20;i++)for(const days of [7,30,90]){await page.locator(`[data-range-kind="sleep"][data-recovery-days="${days}"]`).click();await page.locator(`[data-range-kind="water"][data-recovery-days="${days}"]`).click();await page.waitForFunction(days=>['sleep','water'].every(kind=>document.querySelectorAll(`[data-chart-kind=${kind}] [data-point-date]`).length===days),days)}await bounds('[data-recovery-root]',true)
 // User-confirmed AI writes refresh the other already-open Management Workspace.
 let replies=[];await page.route('https://mock-catalog.invalid/**',async route=>{if(route.request().method()==='OPTIONS'){await route.fulfill({status:204});return}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(replies.shift()??{choices:[{message:{content:'建议待确认。'}}]})})})
 const propose=async(name,args)=>{replies=[{choices:[{message:{content:null,tool_calls:[{id:crypto.randomUUID(),type:'function',function:{name,arguments:JSON.stringify(args)}}]}}]},{choices:[{message:{content:'建议待确认。'}}]}];await page.locator('#ai-message-input').fill('请按我提供的数据创建并让我确认');await page.locator('#ai-send').click();await page.waitForFunction(()=>document.querySelector('.ai-proposal[data-status=pending]')&&!document.querySelector('#ai-send').hidden)}
 await write(page,{foods:Array.from({length:20},(_,i)=>({id:'seed-food-'+i,name:'燕麦种子'+i,referenceGrams:100,calories:100,createdAt:stamp,updatedAt:stamp}))});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await manager.reload({waitUntil:'networkidle'});await manager.addStyleTag({content:css});await manager.locator('#open-management').click();const frame=await manager.locator('dialog[open]').elementHandle();await page.locator('#open-ai-assistant').click()
 const cases=[['propose_food',{action:'create',name:'燕麦',referenceGrams:100,calories:389,protein:16.9,carbs:66.3,fat:6.9},'more-food-library','[data-edit-food]','foods','food-proposal'],['propose_exercise',{action:'create',name:'AI动作',notes:'明确备注'},'more-exercise-library','[data-edit-exercise]','exercises','exercise-proposal'],['propose_workout_template',{action:'create',name:'AI训练模板',newExercises:[{key:'a',name:'新动作A'},{key:'b',name:'新动作B'}],exercises:[{exerciseRef:'a',sets:[{reps:10}]},{exerciseRef:'b',sets:[{reps:12}]}]},'more-workout-templates','[data-edit-workout-template]','workoutTemplates','workout-proposal'],['propose_diet_template',{action:'create',name:'AI早餐',newFoods:[{key:'o',name:'AI牛奶',referenceGrams:100,calories:60}],items:[{foodRef:'o',grams:250}]},'more-diet-templates','[data-edit-diet-template]','dietTemplates','diet-proposal'],['propose_nutrition_strategy',{action:'create',name:'AI营养模板',variants:[{name:'高碳日',carbs:300},{name:'休息日',calories:1800}]},'more-nutrition-strategies','[data-strategy-detail]','nutritionStrategyTemplates','nutrition-proposal']]
 for(const[name,args,entry,selector,store,state]of cases){await manager.locator('#'+entry).click();await manager.waitForSelector('.manager-surface');const route=await manager.locator('dialog[open]').getAttribute('data-management-route');if(store==='foods'){await manager.locator('#library-search').fill('燕麦');await manager.waitForFunction(()=>document.querySelectorAll('[data-edit-food]').length===20);await manager.locator('.modal-body').evaluate(e=>e.scrollTop=180)}const scrollBefore=await manager.locator('.modal-body').evaluate(e=>e.scrollTop);const count=(await read(page,store)).length;await propose(name,args);assert.equal((await read(page,store)).length,count);const proposal=page.locator('.ai-proposal[data-status=pending]');assert.match(await proposal.innerText(),/涉及写入/);await proposal.locator('summary').click();assert.match(await proposal.innerText(),/修改后/);await bounds('div.ai-assistant');await shot(state);await proposal.locator('.ai-proposal-actions .primary').click();await page.waitForFunction(()=>!document.querySelector('.ai-proposal[data-status=processing]')&&!document.querySelector('.ai-proposal[data-status=pending]'));assert.equal((await read(page,store)).length,count+1);await manager.locator(selector).filter({has:manager.getByText(args.name,{exact:true})}).waitFor();assert.equal(await frame.evaluate(e=>e===document.querySelector('dialog[open]')),true);assert.equal(await manager.locator('dialog[open]').getAttribute('data-management-route'),route);if(store==='foods'){assert.equal(await manager.locator('#library-search').inputValue(),'燕麦');assert.ok(Math.abs(await manager.locator('.modal-body').evaluate(e=>e.scrollTop)-scrollBefore)<2)}await manager.screenshot({path:`/tmp/catalog-recovery-${mode}-${width}-${scale}-${colorScheme}-manager-${store}.png`});await manager.locator('[data-workspace-back]').click()}
 // A live write must not replace an unsaved manager editor; Back refreshes its retained list.
 await manager.locator('#more-food-library').click();await manager.locator('[data-edit-food]').filter({has:manager.getByText('燕麦',{exact:true})}).click();await manager.locator('#food-form [name=name]').fill('未保存草稿')
 await propose('propose_food',{action:'create',name:'燕麦额外',referenceGrams:100,calories:123});await page.locator('.ai-proposal[data-status=pending] .primary').click();await page.waitForFunction(()=>!document.querySelector('.ai-proposal[data-status=pending]')&&!document.querySelector('.ai-proposal[data-status=processing]'));assert.equal(await manager.locator('#food-form [name=name]').inputValue(),'未保存草稿');await manager.locator('[data-workspace-back]').click();await manager.locator('[data-edit-food]').filter({has:manager.getByText('燕麦额外',{exact:true})}).waitFor();assert.equal(await frame.evaluate(e=>e===document.querySelector('dialog[open]')),true)
 assert.equal((await read(page,'nutritionStrategyPhases')).length,0);assert.equal((await read(page,'nutritionTargets')).length,0);assert.deepEqual(errors,[]);receipt.push({width,height,scale,colorScheme,reduced,headers:true,compact:true,referenceDefaultSaveNullCrossTab:true,waterHistoryUnchanged:true,range7_30_90:true,stressSwitches:60,chartOnlyScroll:true,fiveCatalogConfirmed:true,managerIdentityAndRefresh:true,errors});console.log(JSON.stringify(receipt.at(-1)))
 }catch(e){console.log('FAILURE_STATE',await context.pages()[0]?.locator('body').innerText());console.log('SLEEP_ROWS',await read(context.pages()[0],'sleepSessions'));for(const p of context.pages())await p.screenshot({path:`/tmp/catalog-recovery-failure-${context.pages().indexOf(p)}.png`}).catch(()=>{});throw e}finally{await context.close()}
}await fs.writeFile(`/tmp/catalog-recovery-${mode}-receipt.json`,JSON.stringify(receipt,null,2))}finally{await browser.close()}
