// Nine-domain experience: isolated synthetic profiles only; all writes use real app services after seeding.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',mode=base.includes('github.io')?'prod':'local',receipts=[]
const fixture=JSON.parse(await fs.readFile(new URL('../fixtures/legacyV11Data.json',import.meta.url)))
const full=[...[320,375,390,430].flatMap(w=>[100,120,140,200].flatMap(s=>['light','dark'].flatMap(c=>[false,true].map(r=>[w,w===430?932:w===390?844:812,s,c,r])))),[844,390,140,'dark',true]]
const matrix=process.env.FITLOG_DAILY_SMOKE?[[390,844,100,'light',false],[320,812,200,'dark',true]]:mode==='prod'?[[390,844,100,'light',false],[320,812,140,'light',true],[320,812,200,'dark',true],[430,932,140,'dark',true],[844,390,140,'dark',true]]:full
const shardWidth=Number(process.env.FITLOG_DAILY_WIDTH||0)
const cases=shardWidth?matrix.filter(([w])=>w===shardWidth):matrix
if(shardWidth&&!cases.length)throw new Error('Invalid daily-records shard width')
const date='2026-10-09',stamp='2026-10-09T00:30:00Z',shift=n=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
const write=async(page,data)=>page.evaluate(async data=>{const d=await new Promise((r,j)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const [name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
const read=async(page,name)=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const a=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return a},name)
try{for(const [width,height,scale,colorScheme,reduced]of cases){const context=await browser.newContext({viewport:{width,height},colorScheme,reducedMotion:reduced?'reduce':'no-preference',isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'})
try{
 await context.addInitScript(()=>{window.dailyViewport=Object.assign(new EventTarget(),{height:innerHeight,width:innerWidth,offsetTop:0,scale:1});Object.defineProperty(window,'visualViewport',{value:window.dailyViewport,configurable:true})})
 const page=await context.newPage(),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-10-09T15:00:00+08:00')});await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('.water-card')
 const css=`html{font-size:${scale}%}:root{--safe-area-top:47px;--safe-area-bottom:34px}`
 const data=structuredClone(fixture);for(const rows of Object.values(data))for(const row of rows)if(row.date)row.date=date
 data.nutritionTargets=data.nutritionTargets.slice(0,1)
 data.habits[0].active=false
 data.sleepSessions=Array.from({length:90},(_,i)=>({id:'sleep-'+i,startTime:shift(-i)+'T02:00:00+08:00',endTime:shift(-i)+'T10:00:00+08:00',durationMinutes:480,recordDate:shift(-i),sleepNightDate:shift(-i),sleepNightDateSource:'manual',sleepStartLocalDate:shift(-i),createdAt:stamp,updatedAt:stamp})).filter((_,i)=>i!==3)
 data.sleepSessions.push({id:'nap',startTime:date+'T12:00:00+08:00',endTime:date+'T13:00:00+08:00',durationMinutes:60,recordDate:date,createdAt:stamp,updatedAt:stamp},{id:'active',startTime:date+'T14:00:00+08:00',activeKey:'active',createdAt:stamp,updatedAt:stamp})
 data.waterLogs=Array.from({length:90},(_,i)=>({id:'water-'+i,date:shift(-i),amountMl:i===89?100000:i%2?2499:2500,timestamp:stamp,createdAt:stamp,updatedAt:stamp})).filter((_,i)=>i!==3)
 data.waterLogs.push({id:'water-extra',date,amountMl:500,timestamp:stamp,createdAt:stamp,updatedAt:stamp})
 await write(page,data);await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await page.waitForSelector('.water-card')
 const capture=width===390&&scale===100&&colorScheme==='light'&&!reduced
 const shot=async(name,selector)=>{if(capture)await(selector?page.locator(selector):page).screenshot({path:`/tmp/daily-${mode}-${name}.png`,fullPage:selector?undefined:name!=='water-toast'});if([320,430,844].includes(width)&&[140,200].includes(scale)&&reduced)await page.screenshot({path:`/tmp/daily-${mode}-${width}-${scale}-${colorScheme}-${name}.png`})}
 const close=async()=>{if(await page.locator('dialog[open]').count())await page.locator('dialog[open] .modal-head [data-close]').last().click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}
 const nav=async tab=>{await close();await page.locator(`[data-tab=${tab}]`).click();await page.waitForSelector(tab==='progress'?'[data-progress-view]':'.water-card')}
 const progress=async view=>{await nav('progress');await page.locator(`[data-progress-view=${view}]`).click();await page.waitForSelector(view==='calendar'?'.calendar-grid':view==='reports'?'.report-mode':'.recovery-trend')}
 const audit=async selector=>{const bad=await page.locator(selector).evaluate(root=>{const a=[];if(document.documentElement.scrollWidth>innerWidth+1)a.push('page overflow');for(const e of root.querySelectorAll('*')){if(e instanceof SVGElement||e.closest('.recovery-chart-scroll,.weight-chart-scroll')||!e.getClientRects().length)continue;const r=e.getBoundingClientRect();if(!r.width||!r.height)continue;if(r.left<-.6||r.right>innerWidth+.6)a.push('bounds '+e.className);if(e.matches('summary,button')&&(r.height<43.5||e.scrollWidth>e.clientWidth+1))a.push('control '+(e.id||e.className));if(e.matches('.daily-record-item p,.day-detail-content strong,.recovery-number')&&e.scrollWidth>e.clientWidth+1)a.push('text clip '+e.className)}return [...new Set(a)]});assert.deepEqual(bad,[],`${width}/${scale}/${colorScheme}/${selector}`)}
 await progress('calendar');const day=page.locator(`.calendar-day[data-date="${date}"]`)
 const expected=['food','strength','cardio','pelvic','weight','dietEvent','habit','sleep','water']
 assert.deepEqual(await day.locator('.calendar-marker-slot').evaluateAll(es=>es.map(e=>e.dataset.category)),expected);assert.equal(await day.locator('.calendar-marker').count(),9);assert.equal(await page.locator('.calendar-marker-overflow').count(),0);assert.equal(await page.locator('.calendar-legend-item').count(),9)
 const geometry=await page.locator('.calendar-day').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,top:r.top,numberWidth:e.querySelector('.calendar-day-number').scrollWidth,numberClient:e.querySelector('.calendar-day-number').clientWidth}}));assert.ok(geometry.every(g=>g.width>=43.5&&g.height>=44&&g.numberWidth<=g.numberClient+1));assert.equal(new Set(geometry.slice(0,7).map(g=>Math.round(g.top))).size,1);assert.match(await day.getAttribute('aria-label'),/睡眠/);assert.match(await day.getAttribute('aria-label'),/饮水/);await audit('#view');await shot('calendar-nine','.month-calendar')
 const adjacent=page.locator('.calendar-day.outside-month').first(),adjacentDate=await adjacent.getAttribute('data-date');await adjacent.click();assert.equal(await page.locator('[data-record-date]').getAttribute('data-record-date'),adjacentDate);await close();await page.locator('#calendar-today').click();await day.waitFor()
 await day.click();const sheet=await page.locator('dialog[open]').elementHandle();assert.deepEqual(await page.locator('[data-record-category]').evaluateAll(es=>es.map(e=>e.dataset.recordCategory)),expected);assert.equal(await page.locator('[data-record-category][open]').count(),0);await audit('dialog[open]');await shot('day-collapsed','dialog[open]')
 for(const category of expected)await page.locator(`[data-record-category=${category}] summary`).click();assert.equal(await page.locator('[data-record-category][open]').count(),9)
 for(const text of ['Historical food snapshot','Historical exercise snapshot','重量未记录','RPE 7','碳水 未知','Legacy habit','9小时0分钟','3000 ml'])assert.match(await page.locator('dialog[open]').innerText(),new RegExp(text));assert.equal(await page.locator('[data-record-category=sleep] .daily-record-item').count(),2);assert.equal(await page.locator('[data-record-category=water] .daily-record-item').count(),2);await audit('dialog[open]');await page.locator('.modal-body').evaluate(e=>e.scrollTop=0);await shot('day-expanded','dialog[open]');if(capture)for(const category of expected)await page.locator(`[data-record-category=${category}]`).screenshot({path:`/tmp/daily-${mode}-expanded-${category}.png`})
 // App writes in another tab update the same Sheet and expanded groups; draft-safe live facts.
 const other=await context.newPage();other.on('pageerror',e=>errors.push(e.message));await other.clock.install({time:new Date('2026-10-09T15:00:00+08:00')});await other.goto(base,{waitUntil:'networkidle'});await other.locator('[data-tab=today]').click();await other.waitForSelector('[data-water-add]')
 await page.locator('.modal-body').evaluate(e=>e.scrollTop=200);const scrollBefore=await page.locator('.modal-body').evaluate(e=>e.scrollTop);await page.locator('[data-record-category=food] summary').evaluate(e=>e.focus({preventScroll:true}));await other.locator('[data-water-add="250"]').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=water] summary').textContent.includes('3250'))
 assert.equal(await sheet.evaluate(e=>e===document.querySelector('dialog[open]')),true);assert.equal(await page.locator('[data-record-category][open]').count(),9);assert.ok(Math.abs(await page.locator('.modal-body').evaluate(e=>e.scrollTop)-scrollBefore)<2);assert.equal(await page.locator('[data-record-category=food] summary').evaluate(e=>e===document.activeElement),true)
 await other.locator('.water-undo button').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=water] summary').textContent.includes('3000'));await close();await other.close()
 // Single-category and empty month; vacant slots remain semantic, never invented icons.
 await page.locator('.calendar-day[data-date="2026-10-08"]').click();assert.match(await page.locator('[data-record-category=food] summary').innerText(),/未记录/);await shot('day-no-food','dialog[open]');await close()
 // Day without recovery remains a full nine-row detail.
 await page.locator('.calendar-day[data-date="2026-10-06"]').click();for(const kind of ['sleep','water'])assert.match(await page.locator(`[data-record-category=${kind}] summary`).innerText(),/未记录/);await shot('day-no-recovery','dialog[open]');await close()
 await page.locator('#calendar-next').click();await page.waitForSelector('.calendar-day[data-date="2026-11-15"]');assert.equal(await page.locator('.calendar-marker').count(),0);await shot('calendar-empty','.month-calendar');await page.locator('#calendar-today').click();await day.waitFor()
 // Precise selection replaces redundant labels/daily lists; every actual point remains accessible.
 await progress('trend')
 for(const days of [7,30,90]){await page.locator(`[data-range-kind="sleep"][data-recovery-days="${days}"]`).click();await page.locator(`[data-range-kind="water"][data-recovery-days="${days}"]`).click();await page.waitForFunction(days=>['sleep','water'].every(kind=>document.querySelectorAll(`[data-chart-kind=${kind}] [data-point-date]`).length===days),days)
 for(const kind of ['sleep','water']){const chart=page.locator(`.recovery-line-chart[data-chart-kind=${kind}]`);assert.equal(await chart.locator('.recovery-point-value').count(),0);assert.equal(await chart.locator('.recovery-line-marker').count(),days-1);assert.equal(await chart.locator('.recovery-line-path').count(),2);const actual=chart.locator('[data-point-value]');assert.equal(await actual.count(),days-1);assert.equal(await chart.locator('[aria-pressed=true]').getAttribute('data-point-date'),date);await actual.first().focus();await page.keyboard.press('Enter');assert.equal(await chart.locator('[aria-pressed=true]').getAttribute('data-point-date'),shift(1-days));await page.keyboard.press('End');assert.equal(await chart.locator('[aria-pressed=true]').getAttribute('data-point-date'),date);await shot(`${kind}-${days}`,`.recovery-chart-scroll:has([data-chart-kind=${kind}])`)}
 assert.equal(await page.locator('.recovery-daily').count(),0);assert.equal(await page.locator('.recovery-trend .recovery-statistics').count(),0);if(days===90){const scroll=page.locator('.recovery-chart-scroll').first();assert.ok(await scroll.evaluate(e=>e.scrollWidth>e.clientWidth));await scroll.evaluate(e=>e.scrollLeft=e.scrollWidth);assert.ok(await scroll.evaluate(e=>e.scrollLeft>0))}await audit('[data-recovery-root]')}
 await progress('reports');assert.equal(await page.locator('[data-report-mode=week]').getAttribute('aria-pressed'),'true');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-date="'+date+'"]');assert.equal(await page.locator('[data-record-category]').count(),9);assert.match(await page.locator('[data-record-category=water] summary').innerText(),/3000/);await audit('#view');await shot('report-day','.report-page')
 await page.locator('#report-previous').click();await page.waitForSelector('[data-record-date="2026-10-08"]');await page.locator('#report-return').click();await page.waitForSelector('[data-record-date="'+date+'"]')
 await page.locator('[data-report-mode=month]').click();await page.waitForSelector('.recovery-report');const reportText=await page.locator('.recovery-report').innerText();assert.match(reportText,/有记录日平均/);assert.match(reportText,/本期真实累计饮水量/);assert.doesNotMatch(reportText,/达标|评分|优秀|不足|健康等级/);await audit('#view');await shot('report-month','.report-page')
 // Real consecutive writes, exact latest-ID undo, one top-layer toast and stable card flow.
 await nav('today');await page.locator('[data-water-add="250"]').scrollIntoViewIfNeeded();const before=await page.locator('.water-card').boundingBox(),n=(await read(page,'waterLogs')).length
 for(const amount of [250,500,250])await page.locator(`[data-water-add="${amount}"]`).click();await page.waitForFunction(()=>document.querySelector('[data-water-total]')?.textContent==='4000');assert.equal((await read(page,'waterLogs')).length,n+3);assert.equal(await page.locator('.water-undo').count(),1);const after=await page.locator('.water-card').boundingBox();assert.equal(after.height,before.height);assert.equal(after.y,before.y);assert.equal(await page.locator('.water-card .toast').count(),0)
 const toast=await page.locator('.water-undo').boundingBox(),undo=await page.locator('.water-undo button').boundingBox();assert.ok(undo.height>=43.5);for(const selector of ['.bottom-nav','[data-water-add="250"]','[data-water-add="500"]','[data-water-custom]']){const r=await page.locator(selector).boundingBox();assert.ok(toast.y+toast.height<=r.y||toast.y>=r.y+r.height||toast.x+toast.width<=r.x||toast.x>=r.x+r.width,`toast overlap ${selector}`)}await page.locator('.water-undo').evaluate(e=>Promise.allSettled(e.getAnimations().map(a=>a.finished)));await shot('water-toast')
 const last=(await read(page,'waterLogs')).filter(w=>!data.waterLogs.some(old=>old.id===w.id)).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).at(-1);await page.locator('.water-undo button').click();await page.waitForFunction(()=>document.querySelector('[data-water-total]')?.textContent==='3750');assert.equal((await read(page,'waterLogs')).length,n+2);assert.ok(!(await read(page,'waterLogs')).some(w=>w.id===last.id))
 // Shared keyboard geometry keeps toast clear of active form and visible viewport.
 await page.locator('[data-water-add="250"]').click();await page.waitForSelector('.water-undo');await page.locator('[data-water-custom]').click();await page.locator('[data-water-form] input').focus();await page.evaluate(()=>{dailyViewport.height=Math.min(460,innerHeight-160);dailyViewport.dispatchEvent(new Event('resize'))});await page.waitForFunction(()=>document.body.classList.contains('keyboard-open'));await page.waitForTimeout(40);const visible=await page.locator('.water-undo').boundingBox(),field=await page.locator('[data-water-form] input').boundingBox();assert.ok(visible.y>=0&&visible.y+visible.height<=Math.min(460,height-160));assert.equal(await page.locator('.water-undo').evaluate(e=>e.matches(':popover-open')),true);assert.ok(visible.y+visible.height<=field.y||visible.y>=field.y+field.height,JSON.stringify({width,scale,visible,field}));await page.locator('[data-water-form] input').fill('123');await page.locator('.water-undo button').click();await page.waitForFunction(()=>!document.querySelector('.water-undo'));assert.equal(await page.locator('[data-water-form] input').inputValue(),'123');await page.evaluate(()=>{dailyViewport.height=innerHeight;dailyViewport.dispatchEvent(new Event('resize'))});await close()
 // Twenty full navigation/write/undo cycles on a representative profile, including Sheet identities.
 if(capture){for(let i=0;i<20;i++){await progress('calendar');await page.locator('#calendar-previous').count();await page.locator('#calendar-prev').click();await page.waitForSelector('.calendar-day[data-date="2026-09-15"]');await page.locator('#calendar-today').click();await day.click();const node=await page.locator('dialog[open]').elementHandle();for(const category of expected)await page.locator(`[data-record-category=${category}] summary`).click();assert.equal(await node.evaluate(e=>e===document.querySelector('dialog[open]')),true);await close();await progress('trend');for(const days of [7,30,90]){await page.locator(`[data-range-kind="sleep"][data-recovery-days="${days}"]`).click();await page.locator(`[data-range-kind="water"][data-recovery-days="${days}"]`).click();await page.waitForFunction(days=>['sleep','water'].every(kind=>document.querySelectorAll(`[data-chart-kind=${kind}] [data-point-date]`).length===days),days)}await progress('reports');for(const m of ['day','month']){await page.locator(`[data-report-mode=${m}]`).click();await page.waitForSelector(m==='day'?'[data-record-date]':'.recovery-report')}await nav('today');await page.locator('[data-water-add="250"]').click();await page.waitForSelector('.water-undo');await page.locator('.water-undo button').click();await page.waitForFunction(()=>!document.querySelector('.water-undo'));assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('sheet-open')),false);assert.equal((await read(page,'waterLogs')).length,n+2);await audit('[data-recovery-root]')}}
 // Clear remains exactly seven stores while recovery and check-in facts survive.
 await progress('calendar');await day.click();const preserved={sleep:await read(page,'sleepSessions'),water:await read(page,'waterLogs'),habit:await read(page,'habitCheckIns'),tasks:await read(page,'tasks')};await page.locator('#calendar-clear-day').click();assert.match(await page.locator('.confirm-dialog').innerText(),/睡眠、饮水、习惯打卡与计划任务保留/);await page.locator('[data-confirm]').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=food] summary')?.textContent.includes('未记录'))
 for(const [key,store]of [['sleep','sleepSessions'],['water','waterLogs'],['habit','habitCheckIns'],['tasks','tasks']])assert.deepEqual(await read(page,store),preserved[key]);await close();assert.equal(await day.locator('.calendar-marker').count(),3)
 // A month with a single Water category and complete empty slots.
 await write(page,{foodLogs:[],dietEvents:[],workouts:[],cardioSessions:[],pelvicFloorSessions:[],weights:[],habitCheckIns:[],sleepSessions:[],waterLogs:[{id:'single',date,amountMl:250,timestamp:stamp,createdAt:stamp,updatedAt:stamp}]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await progress('calendar');assert.equal(await day.locator('.calendar-marker').count(),1);assert.equal(await day.locator('.calendar-marker-slot').count(),9);await shot('calendar-single','.month-calendar')
 await write(page,{waterLogs:[]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await nav('today');await page.waitForFunction(()=>document.querySelector('[data-water-total]')?.textContent==='0');await page.locator('[data-water-add="250"]').scrollIntoViewIfNeeded();const zeroHeight=await page.locator('.water-card').evaluate(e=>e.getBoundingClientRect().height);await page.locator('[data-water-add="250"]').click();await page.waitForFunction(()=>document.querySelector('[data-water-total]')?.textContent==='250');assert.equal(await page.locator('.water-card').evaluate(e=>e.getBoundingClientRect().height),zeroHeight);await page.locator('.water-undo button').click();await page.waitForFunction(()=>document.querySelector('[data-water-total]')?.textContent==='0');assert.equal(await page.locator('.water-card').evaluate(e=>e.getBoundingClientRect().height),zeroHeight)
 if(capture){
 await write(page,{waterLogs:[],habits:[{...data.habits[0],active:true}],habitCheckIns:[],sleepSessions:[{id:'live-active',startTime:date+'T14:00:00+08:00',activeKey:'active',createdAt:stamp,updatedAt:stamp}]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await progress('calendar');assert.equal(await day.locator('.calendar-marker').count(),0);await day.click()
 const writer=await context.newPage();await writer.clock.install({time:new Date('2026-10-09T15:00:00+08:00')});await writer.goto(base,{waitUntil:'networkidle'});await writer.locator('[data-tab=today]').click();await writer.waitForSelector('[data-water-add]');await writer.locator('[data-water-add="250"]').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=water] summary').textContent.includes('250'))
 // Genuine delete failure is visible and retryable, without pretending the row was undone.
 await writer.evaluate(()=>{window.originalWaterDelete=IDBObjectStore.prototype.delete;IDBObjectStore.prototype.delete=function(...a){if(this.name==='waterLogs')throw new DOMException('synthetic delete failure','UnknownError');return originalWaterDelete.apply(this,a)}});await writer.locator('.water-undo button').click();await writer.waitForFunction(()=>document.querySelector('.water-undo')?.textContent.includes('撤销未完成'));assert.equal((await read(writer,'waterLogs')).length,1);assert.equal(await writer.locator('.water-undo button').isEnabled(),true);await writer.evaluate(()=>IDBObjectStore.prototype.delete=originalWaterDelete)
 await writer.locator('[data-water-history]').click();await writer.locator('[data-edit-water]').click();await writer.locator('[data-water-form] input').fill('400');await writer.locator('[data-water-form] [type=submit]').click();await writer.locator('dialog[open] .modal-head [data-close]').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=water] summary').textContent.includes('400'))
 await writer.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=sleep] summary').textContent.includes('1小时0分钟'));await writer.locator('[data-habit-toggle]').click();await page.waitForFunction(()=>document.querySelector('[data-record-category=habit] summary').textContent.includes('1 次打卡'));await close();assert.equal(await day.locator('.calendar-marker').count(),3)
 await progress('trend');await page.waitForFunction(()=>document.querySelector('[data-chart-kind=water] [data-point-value="400"]'));await progress('reports');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-date]');assert.match(await page.locator('[data-record-category=water] summary').innerText(),/400/);await page.locator('[data-report-mode=month]').click();await page.waitForSelector('.recovery-report');assert.match(await page.locator('.recovery-report').innerText(),/400 ml/)
 await writer.locator('.water-undo button').click();await page.waitForFunction(()=>document.querySelector('.recovery-report')?.textContent.includes('0 天')&&!document.querySelector('.recovery-report')?.textContent.includes('400 ml'));await progress('calendar');assert.equal(await day.locator('.calendar-marker').count(),2);await day.click();assert.match(await page.locator('[data-record-category=water] summary').innerText(),/未记录/);await close();await progress('trend');await page.waitForSelector('[data-trend-module=water] .trend-empty');await progress('reports');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-date]');assert.match(await page.locator('[data-record-category=water] summary').innerText(),/未记录/);await writer.close()
 }
 assert.deepEqual(errors,[]);const receipt={width,height,scale,colorScheme,reduced,nineCalendar:true,detailAllNine:true,historySnapshots:true,inactiveCheckIn:true,multiEpisode:true,activeExcluded:true,adjacent:true,liveSheetIdentity:true,expandedFocusScrollPreserved:true,lineRanges:[7,30,90],preciseSelectablePoints:true,missingSplit:true,internalScroll:true,dayWeekMonth:true,waterExactUndo:true,threeIndependentWrites:true,stableCard:true,keyboardToast:true,clearSevenStores:true,stressCycles:capture?20:0,noOverflow:true,errors,physicalIPhone:'Pending'};receipts.push(receipt);console.log(JSON.stringify(receipt))
}catch(error){for(const p of context.pages())await p.screenshot({path:`/tmp/daily-${mode}-failure.png`}).catch(()=>{});console.log('FAILURE_STATE',await context.pages()[0]?.locator('body').innerText());throw error}finally{await context.close()}}
await fs.writeFile(`/tmp/daily-${mode}${shardWidth?'-'+shardWidth:''}-receipt.json`,JSON.stringify(receipts,null,2))}finally{await browser.close()}
