// Independent DietEvent UI with real local services, Canvas image preparation and mock Vision.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5175/fitlog-lite/',prod=base.includes('github.io'),sizes=prod?[[390,844],[430,932]]:[[320,812],[375,812],[390,844],[430,932]],receipts=[]
const fixture=JSON.parse(await fs.readFile(new URL('../fixtures/legacyV9Data.json',import.meta.url)))
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
try{for(const [width,height] of sizes){const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true,serviceWorkers:'block',timezoneId:'Asia/Shanghai'})
try{
await context.addInitScript(()=>{const p={id:'meal-test',name:'合成图片服务',protocol:'openai-chat-completions',baseUrl:'https://mock-meal-vision.invalid/v1',model:'chat-model',visionModel:'image-model',toolCapability:'supported',visionCapability:'supported',createdAt:'',updatedAt:''};localStorage.setItem('fitlog-ai-profiles-v1',JSON.stringify([p]));localStorage.setItem('fitlog-ai-active-profile-v1',p.id);localStorage.setItem('fitlog-ai-key-v1:'+p.id,'synthetic-meal-ai-key');localStorage.setItem('fitlog-ai-privacy-ack-v1','1');window.mealViewport=Object.assign(new EventTarget(),{width:innerWidth,height:innerHeight,offsetTop:0});Object.defineProperty(window,'visualViewport',{configurable:true,value:window.mealViewport})})
const page=await context.newPage(),states=[],errors=[],vision=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));let fail=false,holdVision=false,releaseVision
await page.route('https://mock-meal-vision.invalid/**',async route=>{const body=route.request().postDataJSON();vision.push(body);assert.equal(body.model,'image-model');assert.ok(!JSON.stringify(body).includes('synthetic-meal-ai-key'));assert.ok(body.messages[0].content.includes('不是包装营养表转录'));assert.ok(body.messages[1].content.filter(p=>p.type==='image_url').every(p=>p.image_url.url.startsWith('data:image/jpeg;base64,')));if(holdVision){await new Promise(resolve=>releaseVision=resolve);try{await route.fulfill({json:{choices:[{message:{content:'{}'}}]}})}catch{}return}await route.fulfill(fail?{json:{choices:[{message:{content:'```bad'}}]}}:{json:{choices:[{message:{content:JSON.stringify({summary:'餐食份量与用油不确定',caloriesLow:1200,caloriesHigh:2000,assumptions:['餐食照片看不到隐藏配料','实际份量仍需用户核对']})}}]}})})
await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management');await page.addStyleTag({content:':root{--safe-area-top:47px;--safe-area-bottom:34px}'})
const dates=await page.evaluate(()=>{const local=offset=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};return {today:local(0),old:local(-1)}})
const put=async data=>page.evaluate(async data=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});await new Promise((resolve,reject)=>{const tx=d.transaction(Object.keys(data),'readwrite');for(const [name,rows]of Object.entries(data)){const s=tx.objectStore(name);s.clear();rows.forEach(row=>s.put(row))}tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});d.close()},data)
const read=async()=>page.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const out={};for(const store of d.objectStoreNames)out[store]=await new Promise(r=>{const q=d.transaction(store).objectStore(store).getAll();q.onsuccess=()=>r(q.result)});d.close();return out})
const close=async()=>{if(await page.locator('dialog[open]').count())await page.locator('dialog[open] [data-close]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}
const nav=async tab=>{await close();await page.locator('[data-tab='+tab+']').click();await page.waitForTimeout(80);await page.evaluate(()=>scrollTo(0,0))}
const audit=async(name,scale)=>{await page.waitForTimeout(230);const failures=await page.evaluate(()=>{const root=document.querySelector('dialog[open]')||document.querySelector('#view'),r=root.matches('dialog')?root.getBoundingClientRect():{left:0,right:innerWidth},out=[];if(document.documentElement.scrollWidth>innerWidth+1)out.push('root');for(const e of root.querySelectorAll('*')){const b=e.getBoundingClientRect(),s=getComputedStyle(e);if(!b.width||!b.height||e.closest('[hidden]')||e.closest('.food-date-rail')||e instanceof SVGElement)continue;if(b.left<r.left-1||b.right>r.right+1)out.push('bounds '+e.className);if(e.matches('button,summary')&&(b.height<43.5||b.width<43.5||e.scrollWidth>e.clientWidth+1))out.push('control '+(e.id||e.className));if(e.matches('input:not([type=checkbox]),textarea,select')&&parseFloat(s.fontSize)<16)out.push('font '+e.name)}return [...new Set(out)]});await page.screenshot({path:`/tmp/diet-events-${prod?'prod':'local'}-${width}-${scale}-${name}.png`,fullPage:!await page.locator('dialog[open]').count()});assert.deepEqual(failures,[],`${width}/${scale}/${name}`);states.push({name,scale})}
const edit=async index=>{await page.locator('[data-diet-event-edit]').nth(index).click();await page.waitForSelector('.diet-event-form')}
const save=async()=>{await page.locator('.diet-event-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}
const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=256;c.height=200;const g=c.getContext('2d');g.fillStyle='orange';g.fillRect(0,0,256,200);return c.toDataURL('image/png').split(',')[1]}),'base64')
for(const scale of [100,120,140]){await page.evaluate(scale=>document.documentElement.style.fontSize=16*scale/100+'px',scale);await put({...fixture,dietEvents:[],foodLogs:[{...fixture.foodLogs[0],date:dates.today}],workouts:[{...fixture.workouts[0],date:dates.today}],cardioSessions:[{...fixture.cardioSessions[0],date:dates.today}],pelvicFloorSessions:[{...fixture.pelvicFloorSessions[0],date:dates.today}],weights:[{...fixture.weights[0],date:dates.today}],nutritionTargets:[{...fixture.nutritionTargets[0],date:dates.today}]});const before=await read();delete before.dietEvents
await nav('today');await nav('food');await page.locator('#food-return-today').evaluate(e=>{if(!e.hidden)e.click()});await page.waitForSelector('[data-diet-event-new]');await audit('food-none',scale)
await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector('.calendar-day[data-date="'+dates.today+'"]');await audit('calendar-ordinary',scale);await nav('food');await page.locator('[data-diet-event-new]').click();await audit('mark-only-form',scale);await save();let records=(await read()).dietEvents;assert.equal(records.length,1);assert.equal(records[0].scope,'dinner');assert.equal(records[0].estimatedCalories,undefined);await audit('food-meal-no-kcal',scale)
await page.locator('[data-diet-event-new]').click();await page.locator('[name=scope]').selectOption('lunch');await page.locator('[name=calories]').fill('1800.125');await save();await audit('food-multiple-manual',scale)
await edit(0);await page.locator('[name=note]').fill('聚餐备注这是一个较长的中文记录用于验证手机上的换行与阅读。'.repeat(20));await page.locator('[name=calories]').fill('1600.25');await audit('long-note-edit',scale)
await page.locator('[name=note]').focus();await page.evaluate(()=>{mealViewport.height=460;mealViewport.offsetTop=0;mealViewport.dispatchEvent(new Event('resize'))});await page.waitForFunction(()=>document.body.classList.contains('keyboard-open'));await page.locator('.modal-body').evaluate(e=>e.scrollTop=e.scrollHeight);await audit('keyboard-bottom-save',scale);await page.evaluate(()=>{mealViewport.height=innerHeight;mealViewport.dispatchEvent(new Event('resize'))});await page.locator('[name=note]').blur();await save();await audit('food-long-note',scale);assert.equal(await page.locator('.diet-event-note').first().evaluate(e=>getComputedStyle(e).webkitLineClamp),'3')
await edit(0);await page.locator('#diet-photo-open').click();assert.equal(await page.locator('[data-meal-file=album]').getAttribute('capture'),null);assert.equal(await page.locator('[data-meal-file=camera]').getAttribute('capture'),'environment');await page.locator('[data-meal-file=album]').setInputFiles([{name:'meal.png',mimeType:'image/png',buffer:png},{name:'meal-second.png',mimeType:'image/png',buffer:png}]);await page.waitForSelector('.meal-photo-images img');assert.equal(await page.locator('.meal-photo-images img').count(),2);await audit('photo-selected',scale);if(await page.locator('#meal-photo-consent').count())await page.locator('#meal-photo-consent').check();await page.locator('#meal-photo-estimate').click();await page.waitForSelector('#meal-photo-use');await audit('photo-review',scale);const old=(await read()).dietEvents;assert.equal(old.find(e=>e.scope==='dinner').estimateSource,'manual');await page.locator('#meal-photo-final').fill('1650.25');await page.locator('#meal-photo-use').click();assert.equal(await page.locator('[name=calories]').inputValue(),'1650.25');assert.equal((await read()).dietEvents.find(e=>e.scope==='dinner').estimateSource,'manual');await save();records=(await read()).dietEvents;const photo=records.find(e=>e.scope==='dinner');assert.equal(photo.estimateSource,'photo');assert.equal(photo.estimatedCalories,1650.25);assert.equal(photo.estimatedCaloriesLow,1200);assert.equal(photo.estimatedCaloriesHigh,2000);assert.ok(!JSON.stringify(records).includes('data:image'));await audit('food-photo-estimate',scale)
// Converting a meal photo to day clears the draft range/value; closing leaves the saved meal unchanged.
await edit(0);await page.locator('[name=scope]').selectOption('day');assert.equal(await page.locator('[name=calories]').inputValue(),'');assert.equal(await page.locator('.diet-photo-range').innerText(),'');assert.ok(await page.locator('#diet-photo-open').isDisabled());await audit('photo-to-day-draft',scale);await close();assert.equal((await read()).dietEvents.find(e=>e.scope==='dinner').estimateSource,'photo');
await edit(0);await page.locator('#diet-photo-open').click();assert.equal(await page.locator('.meal-photo-images img').count(),0);await page.locator('[data-meal-file=album]').setInputFiles({name:'retry.png',mimeType:'image/png',buffer:png});await page.waitForSelector('.meal-photo-images img');fail=true;await page.locator('#meal-photo-estimate').click();await page.waitForFunction(()=>document.querySelector('#meal-photo-stop').hidden);assert.equal(await page.locator('#meal-photo-use').count(),0);assert.ok((await page.locator('.meal-photo-status').innerText()).length>0);await audit('photo-malformed-response',scale);fail=false;await close();assert.equal((await read()).dietEvents.find(e=>e.scope==='dinner').estimatedCalories,1650.25);
if(scale===100){for(const action of ['stop','close']){await edit(0);await page.locator('#diet-photo-open').click();await page.locator('[data-meal-file=album]').setInputFiles({name:'cancel.png',mimeType:'image/png',buffer:png});await page.waitForSelector('.meal-photo-images img');holdVision=true;releaseVision=undefined;await page.locator('#meal-photo-estimate').click();while(!releaseVision)await page.waitForTimeout(10);if(action==='stop'){await page.locator('#meal-photo-stop').click();await page.waitForFunction(()=>document.querySelector('#meal-photo-stop').hidden);assert.equal(await page.locator('#meal-photo-use').count(),0);await audit('photo-stop-aborted',scale);await close()}else await close();releaseVision();holdVision=false;assert.equal((await read()).dietEvents.find(e=>e.scope==='dinner').estimatedCalories,1650.25)}}

await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector('.calendar-day[data-date="'+dates.today+'"]');const day=page.locator('.calendar-day[data-date="'+dates.today+'"]');assert.equal(await day.locator('.calendar-marker').count(),4);assert.equal(await day.locator('.calendar-category-dietEvent').count(),1);assert.equal(await day.locator('.calendar-marker-overflow').innerText(),'+2');assert.ok((await day.getAttribute('aria-label')).includes('放纵餐'));await audit('calendar-six-markers',scale);await day.click();await audit('calendar-meal-detail',scale);assert.equal(await page.locator('.diet-events-detail .diet-event-note').first().evaluate(e=>getComputedStyle(e).webkitLineClamp),'none');assert.ok((await page.locator('.diet-events-detail').innerText()).includes('不计入营养总计'));await page.locator('[data-diet-event-edit]').first().click();await page.waitForSelector('.diet-event-form');await close();await nav('food')
await page.locator('[data-diet-event-new]').click();await page.locator('[name=scope]').selectOption('day');assert.ok(await page.locator('#diet-photo-open').isDisabled());assert.ok((await page.locator('.diet-photo-scope').innerText()).includes('单餐'));await page.locator('[name=calories]').fill('2500');await page.locator('[name=note]').fill('旅行放松饮食');await save();assert.equal(await page.locator('[data-diet-event-new]').count(),0);await audit('food-day-with-existing-meals',scale);await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector('.calendar-day[data-date="'+dates.today+'"]');assert.ok((await day.getAttribute('aria-label')).includes('放纵日'));await audit('calendar-day',scale);await day.click();await audit('calendar-day-detail',scale);await page.locator('.modal-body').evaluate(e=>e.scrollTop=e.scrollHeight);await audit('calendar-day-detail-bottom',scale);assert.ok((await page.locator('.diet-events-detail').innerText()).includes('放纵日'));await close();await nav('food')
const after=await read();delete after.dietEvents;assert.deepEqual(after,before,'all original 17 stores/targets/strategy/history unchanged');assert.ok((await page.locator('.food-calorie-row').innerText()).includes('100'));await nav('today');assert.equal(await page.locator('.today-calorie-gauge').getAttribute('data-actual'),'100');await nav('food')
// Delete day and photo notes through the actual named danger confirmation; meals remain independent.
let ids=(await read()).dietEvents;for(const record of ids){await page.locator('[data-diet-event-edit="'+record.id+'"]').click();await page.locator('#diet-event-delete').click();assert.ok((await page.locator('.confirm-dialog').innerText()).includes(record.scope==='day'?'放纵日':'放纵餐'));await page.locator('[data-confirm]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}assert.equal((await read()).dietEvents.length,0);await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector('.calendar-day[data-date="'+dates.today+'"]');assert.equal(await day.locator('.calendar-category-dietEvent').count(),0);await audit('calendar-after-delete',scale)
await nav('food');await page.locator('#food-date-picker-open').click();await page.locator('[data-date="'+dates.old+'"]').click();await page.locator('[data-done]').click();await page.locator('[data-diet-event-new]').click();await page.locator('[name=scope]').selectOption('day');await save();assert.equal((await read()).dietEvents[0].date,dates.old);await audit('food-historical-day',scale);await page.locator('#food-return-today').click();await page.waitForSelector('[data-diet-event-new]')
}
assert.deepEqual(errors,[]);receipts.push({width,height,states:states.length,visionRequests:vision.length,canonicalTotalsExcluded:true,all17StoresUnchanged:true,independentMultipleScopes:true,photoDraftRequiresSave:true,photoErrorStopClosePreserve:true,photoToDayClearsDraft:true,noImagesPersisted:true,crowdedMarkerVisible:true,dayPhotoDisabled:true,historicalDate:true,keyboard:'mocked',physicalIPhone:'Pending'});console.log(JSON.stringify(receipts.at(-1)))
}finally{await context.close()}}
await fs.writeFile(`/tmp/diet-events-${prod?'prod':'local'}-receipt.json`,JSON.stringify(receipts,null,2))
}finally{await browser.close()}
