// New Food/Recovery acceptance gate. Every write targets an isolated synthetic context.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',prod=base.includes('github.io'),receipt=[]
const matrix=process.env.FITLOG_RECOVERY_SMOKE?[[320,812,140,'light',false],[390,844,100,'dark',true]]:prod?[[390,844,100,'light',false],[320,812,140,'light',true],[390,844,100,'dark',true],[844,390,140,'dark',false]]:[...[[320,812],[375,812],[390,844],[430,932]].flatMap(([w,h])=>[100,120,140].flatMap(s=>[false,true].map(r=>[w,h,s,'light',r]))),...[[320,812],[360,812],[430,932],[480,932],[844,390]].flatMap(([w,h])=>[100,140].map(s=>[w,h,s,'dark',s===140])),[844,390,140,'light',false]]
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
try{for(const[width,height,scale,colorScheme,reduced]of matrix){
 const context=await browser.newContext({viewport:{width,height},colorScheme,reducedMotion:reduced?'reduce':'no-preference',isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'})
 try{
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000)
 await page.clock.install({time:new Date('2026-10-09T07:24:00+08:00')});await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management');await page.addStyleTag({content:`html{font-size:${scale}%}`})
 const write=async data=>page.evaluate(async data=>{const d=await new Promise((r,j)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
 const read=async name=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return rows},name)
 const stamp='2026-10-08T00:00:00Z',date='2026-10-09',logs=Array.from({length:20},(_,i)=>({id:'long-food-'+i,date,meal:'breakfast',foodName:'非常长的全麦脆麦片甜菜根固体饮料酵母蛋白粉 '+i,grams:100,referenceGrams:100,caloriesPerReference:i?0:419,totalCalories:i?0:419,totalProtein:i?0:164,totalCarbs:i?0:252,totalFat:i?0:52,createdAt:stamp,updatedAt:stamp}))
 const sleep={id:'overnight',startTime:'2026-10-08T23:48:00+08:00',activeKey:'active',createdAt:stamp,updatedAt:stamp}
 await write({foodLogs:logs,nutritionTargets:[{id:'target',date,calories:2200,protein:165,carbs:255,fat:50,createdAt:stamp,updatedAt:stamp}],weights:[{id:'historical',date:'2026-10-08',weightKg:80,createdAt:stamp,updatedAt:stamp}],sleepSessions:[sleep],waterLogs:[]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`})
 const tab=async name=>{await page.locator(`[data-tab=${name}]`).click();await page.waitForSelector(name==='food'?'.food-content-body':'[data-recovery-root] .sleep-card')}
 const bounds=async selector=>{const result=await page.locator(selector).evaluate(root=>{const bad=[];for(const e of root.querySelectorAll('*')){if(!e.getClientRects().length||e instanceof SVGElement)continue;const r=e.getBoundingClientRect(),c=getComputedStyle(e);if(r.left<-.5||r.right>innerWidth+.5)bad.push('bounds '+e.className);if(e.matches('.macro-value,.macro-per-kg,.meal-more,.recovery-number,.recovery-history-tokens > span,.water-actions button,.recovery-card .primary')&&(e.scrollWidth>e.clientWidth+1||c.textOverflow==='ellipsis'))bad.push('critical-clipped '+e.className);if(e.matches('button,input')&&r.height<43.5)bad.push('touch '+e.className)}return{bad,overflow:document.documentElement.scrollWidth>innerWidth+1}});assert.deepEqual(result.bad,[],`${width}/${scale}/${colorScheme}: ${selector}`);assert.equal(result.overflow,false)}
 const shot=async state=>{if((width===320&&scale===140)||(width===390&&scale===100)||height===390)await page.locator(state==='food-collapsed'?'[data-meal-section=breakfast]':state==='food-ratios'||state==='large-numbers'?'.food-nutrition-hero':state==='active-sleep'?'.sleep-card':'.recovery-trend').screenshot({path:`/tmp/food-recovery-${prod?'prod':'local'}-${width}-${scale}-${colorScheme}-${reduced}-${state}.png`})}
 await tab('food');assert.equal(await page.locator('.macro-per-kg').count(),0)
 const more=page.locator('[data-meal-section=breakfast] .food-meal-summary');assert.equal(await page.locator('.meal-more').count(),0);assert.equal(await page.locator('[data-meal-section=breakfast] [data-toggle-meal]').count(),1);assert.match(await more.innerText(),/20 项/);assert.equal(await page.locator('.meal-preview-name').count(),3);await bounds('.food-content-body');await shot('food-collapsed')
 await more.click();assert.equal(await page.locator('[data-meal-section=breakfast] .meal-log-list').isVisible(),true);assert.equal(await page.locator('.meal-log-list .food-row').count(),20);await bounds('.food-content-body');await page.locator('.meal-collapse').click();assert.equal(await page.locator('.meal-log-list').isVisible(),false)
 await write({weights:[{id:'today-weight',date,weightKg:86,createdAt:stamp,updatedAt:stamp}]});await tab('today');await tab('food');assert.deepEqual(await page.locator('.macro-per-kg').allTextContents(),['1.91 g/kg','2.93 g/kg','0.60 g/kg']);assert.equal(await page.locator('#food-completion-open').evaluate(e=>e.classList.contains('primary')),true);await bounds('.food-content-body');await shot('food-ratios')
 // <=3 items expose each name and no counter; large values keep intact responsive macro amounts.
 await write({foodLogs:logs.slice(0,3)});await tab('today');await tab('food');assert.equal(await page.locator('.meal-preview-name').count(),3);assert.equal(await page.locator('.meal-more').count(),0)
 await write({foodLogs:[{...logs[0],totalCalories:12345,totalProtein:1234.5,totalCarbs:9999.9,totalFat:999.9}]});await tab('today');await tab('food');await bounds('.food-content-body');await shot('large-numbers')
 await tab('today');await page.waitForFunction(()=>document.querySelector('[data-sleep-state]')?.textContent==='睡眠记录中');await bounds('[data-recovery-root]');await shot('active-sleep')
 await tab('progress');assert.match(await page.locator('[data-sleep-elapsed]').innerText(),/7小时36分钟/)
 await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`});await page.waitForSelector('[data-sleep-elapsed]');assert.equal((await read('sleepSessions')).length,1)
 await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-state]')?.textContent==='今日睡眠');const ended=(await read('sleepSessions'))[0];assert.equal(ended.recordDate,date);assert.equal(ended.durationMinutes,456);assert.equal(ended.activeKey,undefined)
 await tab('progress');await page.waitForSelector('.sleep-bars');assert.match(await page.locator('.recovery-statistics').innerText(),/7小时36分钟/);await page.locator('[data-recovery-days="30"]').click();assert.equal(await page.locator('.sleep-bars:not(.water-bars) .sleep-bar-column').count(),30);await bounds('[data-recovery-root]');await shot('trends')
 await page.locator('[data-sleep-history]').click();await page.waitForSelector('[data-edit-sleep]');await bounds('dialog[open]');const history=await page.locator('dialog[open]').elementHandle();await page.locator('[data-edit-sleep]').click();await page.locator('[data-sleep-start-date]').click();await page.locator('[data-recovery-date-picker]').waitFor();assert.equal(await history.evaluate(e=>e===document.querySelector('dialog[open]')),true);await page.locator('[data-recovery-back]').click();await page.locator('[data-sleep-form]').waitFor();await page.locator('input[name=end]').fill('06:24');await page.locator('[data-sleep-form] [type=submit]').click();await page.waitForSelector('[data-edit-sleep]');assert.equal((await read('sleepSessions'))[0].durationMinutes,396);await page.locator('dialog[open] .modal-head [data-close]').click()
 await page.locator('[data-sleep-action]').click();await page.waitForSelector('[data-sleep-cancel]');await tab('today');assert.equal((await read('sleepSessions')).length,2)
 // Historical editor, time correction, validation and field bounds.
 await page.locator('[data-sleep-edit]').click();await page.locator('[data-sleep-form] input[name=start]').fill('06:00');await page.locator('[data-sleep-form] [type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('dialog[open]').length===0);assert.match(await page.locator('[data-sleep-elapsed]').innerText(),/1小时24分钟/)
 await page.locator('[data-sleep-cancel]').click();await page.locator('dialog[open]').last().locator('.danger-solid,.danger-button').click();await page.waitForFunction(()=>!document.querySelector('[data-sleep-cancel]'));assert.equal((await read('sleepSessions')).length,1)
 await page.locator('[data-water-add="250"]').click();await page.waitForSelector('.water-undo');await page.locator('.water-undo button').click();await page.waitForFunction(()=>document.querySelector('.water-total strong')?.textContent==='0');assert.equal((await read('waterLogs')).length,0)
 await page.locator('[data-water-add="500"]').click();await page.waitForFunction(()=>document.querySelector('.water-total strong')?.textContent==='500');await page.locator('[data-water-custom]').click();await page.locator('[data-water-form] input').fill('350');await page.locator('[data-water-form] [type=submit]').click();await page.waitForFunction(()=>document.querySelector('.water-total strong')?.textContent==='850')
 await page.locator('[data-water-history]').click();await page.waitForSelector('[data-edit-water]');await page.locator('[data-edit-water]').first().click();await page.locator('[data-water-form] input').fill('400');await page.locator('[data-water-form] [type=submit]').click();await page.waitForFunction(()=>[...document.querySelectorAll('[data-edit-water] strong')].some(e=>e.textContent==='400 ml'));assert.equal((await read('waterLogs')).reduce((n,w)=>n+w.amountMl,0),900)
 await page.locator('[data-delete-water]').first().click();await page.locator('dialog[open]').last().locator('.danger-solid,.danger-button').click();await page.waitForFunction(()=>document.querySelectorAll('[data-edit-water]').length===1);await page.locator('dialog[open] .modal-head [data-close]').click();await bounds('[data-recovery-root]')
 // Forgotten sleep warning and persisted state remain visible without any automatic finish.
 await write({sleepSessions:[{...sleep,startTime:'2026-10-07T23:48:00+08:00'}]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`});await page.locator('.recovery-warning').waitFor();await tab('progress');await page.locator('.recovery-warning').waitFor();await bounds('[data-recovery-root]');assert.equal((await read('sleepSessions'))[0].activeKey,'active')
 if(colorScheme==='dark'){const colors=await page.locator('.recovery-card').first().evaluate(e=>({surface:getComputedStyle(e).backgroundColor,text:getComputedStyle(e).color,mode:getComputedStyle(document.documentElement).colorScheme}));assert.equal(colors.mode,'dark');assert.notEqual(colors.surface,'rgb(255, 254, 248)')}
 assert.deepEqual(errors,[]);const r={width,height,scale,colorScheme,reduced,food20:true,singleMealEntry:true,expandCollapse:true,onlySameDayWeight:true,ratios:true,largeNumbers:true,primaryCompletion:true,sleepPersisted:true,crossDay:true,globalSleep:true,singleActive:true,sleepCorrection:true,forgottenWarning:true,waterUndoEditDelete:true,range7and30:true,noOverflow:true,sameHistorySheet:true,dateBack:true,completedTimeCorrection:true,errors,physicalIPhone:'Pending'};receipt.push(r);console.log(JSON.stringify(r))
 }catch(error){const p=context.pages()[0];if(p){console.log('FAILURE_STATE',await p.locator('body').innerText());await p.screenshot({path:'/tmp/recovery-failure.png'})}throw error}finally{await context.close()}
}await fs.writeFile(`/tmp/food-recovery-${prod?'prod':'local'}-receipt.json`,JSON.stringify(receipt,null,2))}finally{await browser.close()}
