// Serving, exact meal deletion, Calendar glyphs, Cardio presentation and Today states.
// All writes use fresh synthetic contexts; viewport/keyboard are explicitly emulated.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5175/fitlog-lite/',prod=base.includes('github.io'),todayOnly=process.env.FITLOG_QA_TODAY_ONLY==='1'
const sizes=(prod?[[390,844],[430,932]]:[[320,812],[375,812],[390,844],[430,932]]).filter(([width])=>!process.env.FITLOG_QA_SINGLE_WIDTH||width===Number(process.env.FITLOG_QA_SINGLE_WIDTH));assert.ok(sizes.length)
const fixture=JSON.parse(await fs.readFile(new URL('../fixtures/legacyV9Data.json',import.meta.url)))
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME}),receipts=[]
const stamp='2026-09-28T08:00:00.000Z'
try{for(const [width,height] of sizes){
 const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'})
 await context.addInitScript(()=>{window.servingViewport=Object.assign(new EventTarget(),{height:innerHeight,width:innerWidth,offsetTop:0});Object.defineProperty(window,'visualViewport',{configurable:true,value:servingViewport})})
 try{
  const page=await context.newPage(),states=[],errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message))
  await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management');await page.addStyleTag({content:':root{--safe-area-top:47px;--safe-area-bottom:34px}'})
  const dates=await page.evaluate(()=>{const local=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};return {today:local(0),old:local(-1)}})
  const put=async data=>page.evaluate(async data=>{const d=await new Promise(resolve=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>resolve(q.result)});await new Promise((resolve,reject)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const [name,rows] of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=resolve;t.onerror=()=>reject(t.error)});d.close()},data)
  const read=async store=>page.evaluate(async store=>{const d=await new Promise(resolve=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>resolve(q.result)});const rows=await new Promise(resolve=>{const q=d.transaction(store).objectStore(store).getAll();q.onsuccess=()=>resolve(q.result)});d.close();return rows},store)
  const click=async selector=>{await page.locator(selector).first().click();await page.waitForTimeout(70)}
  const close=async()=>{if(await page.locator('.sheet[open]').count())await page.locator('.sheet[open] [data-close]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}
  const nav=async tab=>{await close();await click('[data-tab='+tab+']');await page.evaluate(()=>scrollTo(0,0))}
  const foodNav=async()=>{await nav('today');await nav('food');await page.waitForSelector('[data-add-meal=lunch]')}
  const library=async()=>{await close();await click('#open-management');await click('#more-food-library');await page.waitForSelector('#library-search')}
  const audit=async(name,scale,selector)=>{
   await page.waitForTimeout(220)
   const failures=await page.evaluate(selector=>{
    const root=selector?document.querySelector(selector):[...document.querySelectorAll('dialog[open]')].at(-1)||document.querySelector('#view'),bounds=root.matches('dialog')?root.getBoundingClientRect():{left:0,right:innerWidth},errors=[]
    if(document.documentElement.scrollWidth>innerWidth+1)errors.push('document overflow')
    for(const e of root.querySelectorAll('*')){const r=e.getBoundingClientRect(),s=getComputedStyle(e);if(!r.width||!r.height||e.closest('[hidden]')||e.closest('.food-date-rail')||e.closest('.calendar-grid')||e instanceof SVGElement)continue
     if(r.left<bounds.left-1||r.right>bounds.right+1)errors.push('bounds '+e.className)
     if(e.matches('button,summary')&&(r.width<43.5||r.height<43.5||e.scrollWidth>e.clientWidth+1))errors.push('target/clip '+(e.id||e.className))
     if(e.matches('input:not([type=hidden]),textarea')&&parseFloat(s.fontSize)<16)errors.push('font '+e.name)
     if(e.matches('[data-quantity-mode],.meal-clear,.meal-clear-confirm [data-confirm],#today-workout-details,#today-workout')&&s.whiteSpace!=='nowrap')errors.push('orphan action '+e.className)
    }
    const body=root.querySelector('.modal-body');if(body&&body.scrollWidth>body.clientWidth+1)errors.push('body overflow')
    return [...new Set(errors)]
   },selector)
   await page.screenshot({path:`/tmp/food-serving-${prod?'prod':'local'}-${width}-${scale}-${name}.png`,fullPage:!(await page.locator('dialog[open]').count())});assert.deepEqual(failures,[],`${width}/${scale}/${name}`);states.push({name,scale})
  }
  const food={...fixture.foods[0],id:'serving-food',name:'希腊酸奶这是一款名字较长的食物用于小屏和大字体显示验证',referenceGrams:100,servingGrams:150,calories:120,protein:10,carbs:8,fat:4}
  const plain={...food,id:'plain-food',name:'旧按克食物',servingGrams:undefined}
  const quantity=async id=>{await click('[data-add-meal=lunch]');await click('[data-food="'+id+'"]');await page.waitForSelector('#grams');assert.equal(await page.locator('.sheet[open]').getAttribute('data-sheet-variant'),'form')}
  const mealLog=(id,date,meal)=>({...fixture.foodLogs[0],id,date,meal,foodId:food.id,foodName:food.name,grams:100,totalCalories:120,totalProtein:10,totalCarbs:8,totalFat:4})
  const setDate=async date=>{await click('#food-date-picker-open');if(!await page.locator('[data-date="'+date+'"]').count())await click('[data-month="-1"]');await click('[data-date="'+date+'"]');await click('[data-done]');await page.waitForFunction(date=>document.querySelector('.food-content-body')?.dataset.foodDate===date,date)}
  for(const scale of [1,1.2,1.4]){
   await page.evaluate(scale=>document.documentElement.style.fontSize=`${16*scale}px`,scale)
   await put({foods:[food,plain],foodLogs:[],nutritionTargets:[],workouts:[],cardioSessions:[],pelvicFloorSessions:[],weights:[]})
   if(!todayOnly){
   await foodNav();await quantity(plain.id);assert.equal(await page.locator('[data-quantity-mode]').count(),0);await page.locator('#grams').fill('225');assert.equal(await page.locator('#kcal-preview').innerText(),'270 kcal');await audit('no-serving-grams',scale);await close()
   await quantity(food.id);assert.equal(await page.locator('[data-quantity-mode=grams]').getAttribute('aria-pressed'),'true');await page.locator('#grams').fill('225.123456789');await click('[data-quantity-mode=servings]');await click('[data-quantity-mode=grams]');assert.equal(await page.locator('#grams').inputValue(),'225.123456789');await page.locator('#grams').fill('225');await audit('serving-default-grams',scale)
   await click('[data-quantity-mode=servings]');assert.equal(await page.locator('#grams').inputValue(),'1.5');assert.equal(await page.locator('#serving-conversion').innerText(),'1.5 份 = 225 g');assert.equal(await page.locator('#kcal-preview').innerText(),'270 kcal');await audit('serving-one-and-half',scale)
   await page.locator('#grams').fill('.5');assert.equal(await page.locator('#serving-conversion').innerText(),'0.5 份 = 75 g');assert.equal(await page.locator('#kcal-preview').innerText(),'90 kcal');await audit('serving-half',scale)
   await page.locator('#grams').fill('2.25');assert.equal(await page.locator('#serving-conversion').innerText(),'2.25 份 = 337.5 g');assert.equal(await page.locator('#grams').inputValue(),'2.25');await audit('serving-quarter-precision',scale)
   await click('[data-quantity-mode=grams]');assert.equal(await page.locator('#grams').inputValue(),'337.5');await click('[data-quantity-mode=servings]');assert.equal(await page.locator('#grams').inputValue(),'2.25');await page.locator('#grams').fill('1.5')
   await page.locator('#grams').focus();await page.evaluate(()=>{servingViewport.height=innerHeight-300;servingViewport.offsetTop=20;servingViewport.dispatchEvent(new Event('resize'))});await page.waitForTimeout(90);assert.ok(await page.evaluate(()=>document.body.classList.contains('keyboard-open')));assert.ok(await page.locator('#grams').evaluate(e=>e.getBoundingClientRect().bottom<=visualViewport.height+visualViewport.offsetTop+1));await audit('serving-keyboard',scale);await page.locator('.modal-body').evaluate(e=>e.scrollTop=e.scrollHeight);assert.ok(await page.locator('#log-food-form [type=submit]').evaluate(e=>{const r=e.getBoundingClientRect(),b=e.closest('.modal-body').getBoundingClientRect();return r.top>=b.top&&r.bottom<=b.bottom+1}));await page.screenshot({path:`/tmp/food-serving-${prod?'prod':'local'}-${width}-${scale}-serving-keyboard-bottom-cta.png`})
   await page.locator('.sheet-focus-anchor').focus();await page.evaluate(()=>{servingViewport.height=innerHeight;servingViewport.offsetTop=0;servingViewport.dispatchEvent(new Event('resize'))});await page.waitForTimeout(90);await click('#log-food-form [type=submit]');await page.waitForFunction(()=>!document.querySelector('dialog[open]'));const saved=(await read('foodLogs'))[0];assert.equal(saved.grams,225);assert.equal(saved.totalCalories,270);assert.equal(saved.servingGrams,undefined)
   await library();assert.equal(await page.locator('[data-edit-food="'+food.id+'"] .food-serving-note').innerText(),'1 份 150 g');assert.equal(await page.locator('[data-edit-food="'+plain.id+'"] .food-serving-note').count(),0);await audit('library-serving',scale);await click('[data-edit-food="'+food.id+'"]');await audit('food-editor-serving',scale);assert.equal(await page.locator('[name=referenceGrams]').inputValue(),'100');await page.locator('[name=servingGrams]').fill('170');await page.locator('[name=servingGrams]').focus();await page.evaluate(()=>{servingViewport.height=innerHeight-300;servingViewport.offsetTop=20;servingViewport.dispatchEvent(new Event('resize'))});await page.waitForTimeout(90);assert.ok(await page.locator('[name=servingGrams]').evaluate(e=>e.getBoundingClientRect().bottom<=visualViewport.height+visualViewport.offsetTop+1));await page.screenshot({path:`/tmp/food-serving-${prod?'prod':'local'}-${width}-${scale}-food-editor-serving-keyboard.png`});await page.locator('.sheet-focus-anchor').focus();await page.evaluate(()=>{servingViewport.height=innerHeight;servingViewport.offsetTop=0;servingViewport.dispatchEvent(new Event('resize'))});await page.waitForTimeout(90);await click('#food-form [type=submit]');await page.waitForSelector('#library-search');assert.equal((await read('foods')).find(f=>f.id===food.id).servingGrams,170);assert.deepEqual(await read('foodLogs'),[saved]);await close()
   // Single deletion retains an expanded section; confirmations preserve exact date and meal scope.
   const records=[];for(const [date,meal,count] of [[dates.today,'breakfast',2],[dates.today,'lunch',4],[dates.today,'dinner',3],[dates.today,'snack',1],[dates.today,undefined,2],[dates.old,'lunch',5],[dates.old,undefined,1]])for(let i=0;i<count;i++)records.push(mealLog(date+'-'+(meal||'old')+'-'+i,date,meal))
   await put({foodLogs:records});await foodNav();await click('[data-toggle-meal=lunch]');await audit('meal-multiple-expanded',scale);await click('[data-clear-meal=lunch]');await audit('meal-clear-confirm',scale);assert.ok((await page.locator('dialog[open]').innerText()).includes('4 条'));assert.ok((await page.locator('dialog[open]').innerText()).includes('食物库'));await click('[data-cancel]');assert.deepEqual(await read('foodLogs'),records.sort((a,b)=>a.id.localeCompare(b.id)))
   const lunch=page.locator('[data-meal-section=lunch]');await lunch.locator('summary').first().click();await lunch.locator('[data-delete-log]').first().click();await click('[data-confirm]');await page.waitForFunction(()=>document.querySelector('[data-toggle-meal=lunch]')?.getAttribute('aria-expanded')==='true');assert.equal(await lunch.locator('.food-row').count(),3);await audit('single-delete-stays-expanded',scale)
   await click('[data-clear-meal=lunch]');await click('[data-confirm]');await page.waitForFunction(()=>!document.querySelector('[data-toggle-meal=lunch]'));const remaining=await read('foodLogs');assert.equal(remaining.filter(l=>l.date===dates.today&&l.meal==='lunch').length,0);assert.equal(remaining.filter(l=>l.date===dates.old&&l.meal==='lunch').length,5);assert.equal(remaining.filter(l=>l.date===dates.today&&l.meal==='breakfast').length,2);assert.equal(remaining.filter(l=>l.date===dates.today&&l.meal==='dinner').length,3);await audit('meal-cleared-scope',scale)
   await click('[data-toggle-meal=unclassified]');await click('[data-clear-meal=unclassified]');await click('[data-confirm]');await page.waitForFunction(()=>!document.querySelector('[data-toggle-meal=unclassified]'));assert.equal((await read('foodLogs')).filter(l=>l.date===dates.old&&!l.meal).length,1)
   await setDate(dates.old);await click('[data-toggle-meal=unclassified]');await click('[data-clear-meal=unclassified]');await audit('historical-one-record-confirm',scale);await click('[data-confirm]');await page.waitForFunction(()=>!document.querySelector('[data-toggle-meal=unclassified]'));await click('[data-toggle-meal=lunch]');await click('[data-clear-meal=lunch]');await click('[data-confirm]');await page.waitForFunction(()=>!document.querySelector('[data-toggle-meal=lunch]'));assert.equal((await read('foodLogs')).filter(l=>l.date===dates.old).length,0);assert.equal((await read('foods')).length,2);await click('#food-return-today')
   }
   // All Today execution/navigation states and real metric fields.
   const treadmill={...fixture.cardioSessions[0],date:dates.today,durationMinutes:30,speed:5.5,inclinePercent:6},stair={...treadmill,activityType:'stair_climber',speed:12,inclinePercent:undefined},finished={...fixture.workouts[0],date:dates.today},open={...finished,id:'ongoing',finishedAt:undefined}
   for(const [name,workouts,cardioSessions] of [['empty',[],[]],['treadmill',[],[treadmill]],['stair',[],[stair]],['stair-no-metrics',[],[{...stair,speed:undefined}]],['completed',[finished],[]],['combined',[finished],[treadmill]],['large-summary',[{...finished,exercises:Array.from({length:5},(_,i)=>({...finished.exercises[0],id:'exercise-'+i,sets:Array.from({length:i===0?4:3},(_,j)=>({...finished.exercises[0].sets[0],id:'set-'+i+'-'+j}))}))}],[{...treadmill,durationMinutes:120,speed:12.5,inclinePercent:15}]],['multiple',[],[treadmill,{...treadmill,id:'second'}]],['open',[open],[treadmill]],['large-metrics',[],[{...treadmill,speed:12345.6,inclinePercent:9999.9,durationMinutes:99999.9}]]]){
    await put({workouts,cardioSessions});await nav('today');const card=page.locator('.workout-today-card');assert.ok(await card.locator('#today-workout-details').evaluate(e=>!!e.closest('.card-heading')&&e.classList.contains('text-btn')&&!!e.querySelector('svg')));assert.equal(await card.locator('h2').innerText(),'训练');assert.equal(await card.locator('#today-workout').count(),1);assert.equal(await card.locator('#today-workout').innerText(),name==='open'?'继续力量训练':'记录训练');if(name!=='open')assert.ok(await card.locator('#today-workout').evaluate(e=>e.classList.contains('secondary')&&e.classList.contains('today-activity-action')&&!!e.closest('.today-activity-body')));assert.ok(!(await card.innerText()).includes('km/h'));assert.ok(!(await card.innerText()).includes('%'));if(cardioSessions.length)assert.ok((await card.innerText()).includes('分钟'));if(name==='stair-no-metrics')assert.ok(!(await card.innerText()).trim().endsWith('·'));if(name==='open'){assert.ok(await card.locator('#today-workout').evaluate(e=>e.classList.contains('primary')&&!!e.closest('.today-strength-status')))}assert.ok(await card.locator('.today-training-token').evaluateAll(es=>es.every(e=>getComputedStyle(e).whiteSpace==='nowrap'&&e.getClientRects().length===1)));assert.ok(await card.evaluate(card=>{const overlaps=(a,b)=>{const r=a.getBoundingClientRect(),s=b.getBoundingClientRect();return r.left<s.right&&r.right>s.left&&r.top<s.bottom&&r.bottom>s.top};return !overlaps(card.querySelector('h2'),card.querySelector('#today-workout-details'))&&!overlaps(card.querySelector('.today-strength-status > span'),card.querySelector('#today-workout'))}));if(name!=='open'){const geometry=await page.locator('#today-workout,#today-record-weight,#today-pelvic,#today-habit-create').evaluateAll(es=>es.map(e=>{const s=getComputedStyle(e);return {height:s.minHeight,padding:s.padding,radius:s.borderRadius,font:s.fontSize,background:s.backgroundColor,ink:s.color}}));for(const g of geometry)assert.deepEqual(g,geometry[0])}await audit('today-'+name,scale);await card.screenshot({path:`/tmp/food-serving-${prod?'prod':'local'}-${width}-${scale}-today-${name}-card.png`})
    if(name==='completed'){await click('#today-workout-details');await click('#workout-date-picker-open');await click('[data-date="'+dates.old+'"]');await click('[data-done]');await page.waitForSelector('#start-workout');await click('#history-workout');await nav('today')}
    const before={workouts:await read('workouts'),cardioSessions:await read('cardioSessions')}
    await click('#today-workout');if(name==='open'){await page.waitForSelector('#exit-workout');assert.ok((await page.locator('#view').innerText()).includes(open.exercises[0].exerciseName));assert.deepEqual(await read('workouts'),before.workouts);assert.deepEqual(await read('cardioSessions'),before.cardioSessions);await click('#exit-workout')}else{await page.waitForSelector('#start-workout');assert.equal(await page.locator('#add-cardio').count(),1);assert.equal(await page.locator('#exit-workout').count(),0);assert.ok((await page.locator('#workout-date-picker-open').innerText()).includes(`${Number(dates.today.slice(5,7))}月${Number(dates.today.slice(8))}日`));assert.equal(await page.locator('dialog[open]').count(),0);assert.ok(await page.evaluate(()=>scrollY<1));assert.deepEqual(await read('workouts'),before.workouts);assert.deepEqual(await read('cardioSessions'),before.cardioSessions)}await nav('today');assert.equal(await card.locator('#today-workout').innerText(),name==='open'?'继续力量训练':'记录训练')
    const beforeBrowse={workouts:await read('workouts'),cardioSessions:await read('cardioSessions')};await click('#today-workout-details');await page.waitForSelector('.training-card-action');assert.equal(await page.locator('#exit-workout').count(),0);assert.equal(await page.locator('.training-card-action.primary').count(),3);assert.deepEqual(await read('workouts'),beforeBrowse.workouts);assert.deepEqual(await read('cardioSessions'),beforeBrowse.cardioSessions)
    if(['treadmill','stair'].includes(name)){await click('#cardio-history');await audit('cardio-'+name+'-history',scale);assert.ok(!(await page.locator('dialog[open]').innerText()).includes('km/h'));assert.ok(!(await page.locator('dialog[open]').innerText()).includes('%'));await close();await click('[data-cardio-id]');await audit('cardio-'+name+'-form',scale);assert.ok(!(await page.locator('#cardio-form').innerText()).includes('km/h'));assert.ok(!(await page.locator('#cardio-form').innerText()).includes('%'));assert.equal(await page.locator('[name=speed]').inputValue(),String(cardioSessions[0].speed));assert.equal(await page.locator('[name=duration]').inputValue(),'30');if(name==='stair')assert.ok(!await page.locator('[data-cardio-incline]').isVisible());await close()}
   }
   if(!todayOnly){
   // Food-only, Strength+Food, Food+Cardio+Kegel+Weight and all-category days.
   const pelvic={...fixture.pelvicFloorSessions[0],date:dates.today},weight={...fixture.weights[0],date:dates.today}
   for(const [name,workouts,cardioSessions,pelvicFloorSessions,weights,markers] of [['food-only',[],[],[],[],1],['strength-food',[finished],[],[],[],2],['food-cardio-kegel-weight',[],[treadmill],[pelvic],[weight],4],['all-markers',[finished],[treadmill],[pelvic],[weight],4]]){
    await put({foodLogs:[mealLog('calendar-food',dates.today,'lunch')],workouts,cardioSessions,pelvicFloorSessions,weights});await nav('progress');await click('[data-progress-view=calendar]');const day=page.locator('.calendar-day[data-date="'+dates.today+'"]'),foodMarker=day.locator('.calendar-category-food');assert.equal(await day.locator('.calendar-marker').count(),markers);assert.equal(await foodMarker.locator('svg').count(),1);assert.equal(await foodMarker.locator('path').count(),1);assert.ok((await day.getAttribute('aria-label')).includes('饮食'));const styles=await day.locator('.calendar-marker').evaluateAll(es=>es.map(e=>{const svg=e.querySelector('svg'),s=getComputedStyle(svg),b=e.getBoundingClientRect();return {width:b.width,height:b.height,svgWidth:s.width,svgHeight:s.height,strokeWidth:s.strokeWidth,opacity:s.opacity,align:getComputedStyle(e).alignItems}}));for(const s of styles)assert.deepEqual(s,styles[0]);await audit('calendar-'+name,scale);if(name==='all-markers')assert.equal(await day.locator('.calendar-marker-overflow').innerText(),'+1');await day.click();assert.ok(!(await page.locator('dialog[open]').innerText()).includes('km/h'));await audit('calendar-'+name+'-detail',scale);await close()
   }
   }
  }
  assert.deepEqual(errors,[]);receipts.push({...(!todayOnly?{servingDefaultGrams:true,halfOneAndHalfQuarter:true,exactSnapshotPreserved:true,keyboardMock:true,keyboardBottomCtaReachable:true,foodEditorKeyboard:true,mealCancelExactScopeHistoricalUnclassified:true,singleDeleteRetainsExpansion:true,calendarSingleGlyphAndAria:true}:{}),width,height,todayOnly,states:states.length,fontScales:[100,120,140],cardioUnitlessWithMinutes:true,todayTenStates:true,recordTrainingCreatesNoRecords:true,headerNavigationCreatesNoRecords:true,existingWorkoutContinuation:true,normalNavigationAndPrimaryContinuation:true,noOverflowClipOrOrphans:true,safeAreaMock:true,errors});console.log(JSON.stringify(receipts.at(-1)))
 }finally{await context.close()}
}
await fs.writeFile(`/tmp/food-serving-${prod?'prod':'local'}${todayOnly?'-today':''}${process.env.FITLOG_QA_SINGLE_WIDTH?'-targeted-'+process.env.FITLOG_QA_SINGLE_WIDTH:''}-receipt.json`,JSON.stringify(receipts,null,2))
}finally{await browser.close()}
