// Isolated synthetic devices and mocked GitHub only; no real user credentials.
const { chromium } = await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
import fs from 'node:fs'
import { webcrypto } from 'node:crypto'
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5173/',prod=base.includes('github'),password='synthetic-data-password-123456',fixture=JSON.parse(fs.readFileSync(process.cwd()+'/tests/fixtures/legacyV7Data.json','utf8'))
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
const assert=(v,m)=>{if(!v)throw Error(m)},canonical=d=>JSON.stringify(Object.fromEntries(Object.keys(d).sort().map(s=>[s,[...d[s]].sort((a,b)=>a.id<b.id?-1:1)])))
async function encrypt(backup){const salt=webcrypto.getRandomValues(new Uint8Array(16)),iv=webcrypto.getRandomValues(new Uint8Array(12)),material=await webcrypto.subtle.importKey('raw',Buffer.from(password),'PBKDF2',false,['deriveKey']),key=await webcrypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:310000},material,{name:'AES-GCM',length:256},false,['encrypt']),cipher=await webcrypto.subtle.encrypt({name:'AES-GCM',iv,tagLength:128},key,Buffer.from(JSON.stringify(backup)));return JSON.stringify({format:'fitlog-lite-encrypted-sync',formatVersion:1,encryptedAt:new Date().toISOString(),kdf:{name:'PBKDF2',hash:'SHA-256',iterations:310000,salt:Buffer.from(salt).toString('base64')},cipher:{name:'AES-GCM',iv:Buffer.from(iv).toString('base64')},ciphertext:Buffer.from(cipher).toString('base64')})}
async function decrypt(text){const e=JSON.parse(text),material=await webcrypto.subtle.importKey('raw',Buffer.from(password),'PBKDF2',false,['deriveKey']),key=await webcrypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:Buffer.from(e.kdf.salt,'base64'),iterations:e.kdf.iterations},material,{name:'AES-GCM',length:256},false,['decrypt']);return JSON.parse(new TextDecoder().decode(await webcrypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(e.cipher.iv,'base64'),tagLength:128},key,Buffer.from(e.ciphertext,'base64'))))}
for(const [width,height]of prod?[[390,844],[430,932]]:process.env.FITLOG_QA_QUICK?[[Number(process.env.FITLOG_QA_WIDTH||390),812]]:[[320,812],[375,812],[390,844],[430,932]]){
 const server={private:true,remote:undefined,writes:0,attempts:0,calls:0,race:false,failure:0,archived:false,empty:false},contexts=[],errors=[]
 const device=async(saved)=>{const c=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai'});contexts.push(c);await c.route('https://api.github.com/**',async route=>{
  server.calls++;const req=route.request(),url=req.url(),json=(body,status=200)=>route.fulfill({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Accept,Content-Type,X-GitHub-Api-Version','Access-Control-Allow-Methods':'GET,PUT,OPTIONS'},body:JSON.stringify(body)})
  assert(url.startsWith('https://api.github.com/repos/king-640-060/fitlog-lite-data'),'wrong default repository');if(server.failure)return json({},server.failure)
  if(req.method()==='PUT'){server.attempts++;const body=req.postDataJSON();if(server.race){server.race=false;const other=await decrypt(server.remote.text);other.data.tasks.push({id:'race-task',title:'Other device race',tagIds:[],createdAt:'2026-09-28T08:00:00.000Z',updatedAt:'2026-09-28T08:00:00.000Z'});server.remote={sha:'race-sha',text:await encrypt(other)};return json({},409)}
   if(body.sha!==server.remote?.sha)return json({},409);server.writes++;server.remote={sha:'sha-'+server.writes,text:Buffer.from(body.content,'base64').toString('utf8')};assert(!server.remote.text.includes('PRIVATE_TEST_'),'plaintext leak');assert(!server.remote.text.includes(password),'password leak');return json({content:{sha:server.remote.sha}})
  }
  if(url.includes('/contents/fitlog/'))return server.remote?json({type:'file',sha:server.remote.sha,encoding:'base64',content:Buffer.from(server.remote.text).toString('base64')}):json({},404)
  if(url.includes('/contents?'))return json([])
  return json({private:server.private,archived:server.archived,default_branch:server.empty?'':'main'})
 });if(saved)await c.addInitScript(saved=>{for(const[k,v]of Object.entries(saved))localStorage.setItem(k,v)},saved);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'networkidle'});await p.waitForSelector('#open-management');return {c,p}}
 const read=async(p)=>p.evaluate(async()=>{const d=await new Promise((y,n)=>{let r=indexedDB.open('fitlog-lite-db');r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)}),data={};for(const s of d.objectStoreNames)data[s]=await new Promise((y,n)=>{let r=d.transaction(s).objectStore(s).getAll();r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)});d.close();return data})
 const mutate=async(p,commands)=>p.evaluate(async commands=>{const d=await new Promise((y,n)=>{let r=indexedDB.open('fitlog-lite-db');r.onsuccess=()=>y(r.result);r.onerror=()=>n(r.error)});await new Promise((y,n)=>{const t=d.transaction([...new Set(commands.map(c=>c.store))],'readwrite');t.oncomplete=()=>y();t.onabort=()=>n(t.error);for(const c of commands){const s=t.objectStore(c.store);if(c.clear)s.clear();else s.put(c.value)}});d.close()},commands)
 const shot=async(p,name)=>{await p.waitForTimeout(330);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page overflow '+name);assert(await p.locator('.modal-body').evaluate(e=>e.scrollWidth<=e.clientWidth),'sheet overflow '+name);assert(await p.locator('#github-sync-body button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)),'touch targets '+name);assert(await p.locator('#github-sync-body input').evaluateAll(es=>es.every(e=>parseFloat(getComputedStyle(e).fontSize)>=16)),'input font '+name);await p.screenshot({path:`/tmp/github-sync-${prod?'prod':'local'}-${width}-${name}.png`})}
 const open=async(p)=>{await p.locator('#open-management').click();await p.locator('#more-github-sync').click();await p.waitForSelector('#sync-connect-form')}
 const connect=async(p)=>{await p.locator('[name=token]').fill('synthetic-token-not-real');await p.locator('#sync-connect-form [type=submit]').click()}
 const waitReady=async(p)=>{await p.waitForFunction(()=>{const b=document.querySelector('#sync-now');return b&&!b.disabled})}
 const task=(id,title)=>({id,title,tagIds:[],createdAt:'2026-09-28T08:00:00.000Z',updatedAt:'2026-09-28T08:00:00.000Z'})
 const oldConfig={owner:'another-owner',repo:'previous-private-repo',defaultBranch:'legacy-branch',remotePath:'fitlog/latest.enc.json'},oldState={deviceId:'previous-device',lastRemoteSha:'old-sha',lastSyncedDataHash:'old-hash',lastSyncedAt:'2026-09-28T08:00:00.000Z'},saved={'fitlog-github-sync-config-v1':JSON.stringify(oldConfig),'fitlog-github-sync-state-v1':JSON.stringify(oldState),'fitlog-github-sync-token-v1':'synthetic-old-token'}
 const legacy=await device(saved);await legacy.p.locator('#open-management').click();await legacy.p.locator('#more-github-sync').click();await waitReady(legacy.p);assert(server.calls===0,'opening old config contacted GitHub');assert((await legacy.p.locator('#github-sync-body').innerText()).includes('another-owner / previous-private-repo'),'old config overwritten');for(const [k,v]of Object.entries(saved))assert(await legacy.p.evaluate(k=>localStorage.getItem(k),k)===v,'old saved metadata changed');await legacy.p.locator('#sync-disconnect').click();await legacy.p.locator('#sync-confirm-disconnect').click();assert((await legacy.p.locator('#github-sync-body').innerText()).includes('king-640-060 / fitlog-lite-data'),'disconnect defaults');await legacy.c.close()
 const setupDevice=await device();await open(setupDevice.p);assert(await setupDevice.p.locator('#sync-connect-form input').count()===1,'setup fields');assert(await setupDevice.p.locator('[name=owner],[name=repo]').count()===0,'editable owner/repo');await setupDevice.p.locator('.sync-prepare summary').click();await shot(setupDevice.p,'preparation');assert((await setupDevice.p.locator('.sync-prepare').innerText()).includes('Contents: Read and write'),'least privilege guidance');
 for(const [failure,text]of [[404,'king-640-060/fitlog-lite-data'],[403,'Contents: Read and write']]){server.failure=failure;await connect(setupDevice.p);await setupDevice.p.waitForFunction(text=>document.querySelector('#sync-message')?.textContent.includes(text),text);if(failure===404){const message=await setupDevice.p.locator('#sync-message').innerText();assert(message.includes('Private Repository')&&message.includes('README'),'404 preparation');await shot(setupDevice.p,'missing-repo')}assert(await setupDevice.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-config-v1'))===null,'failed setup saved')}
 server.failure=0;for(const flag of ['archived','empty']){server[flag]=true;await connect(setupDevice.p);await setupDevice.p.waitForFunction(text=>document.querySelector('#sync-message')?.textContent.includes(text),flag==='archived'?'归档':'README');assert(await setupDevice.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-config-v1'))===null,'invalid repo connected');server[flag]=false}await setupDevice.c.close();server.calls=0
 const a=await device();assert(server.calls===0,'automatic network');await mutate(a.p,Object.entries(fixture).flatMap(([store,rows])=>[{store,clear:true},...rows.map(value=>({store,value}))]));await open(a.p);await shot(a.p,'setup');server.private=false;await connect(a.p);await a.p.waitForFunction(()=>document.querySelector('#sync-message')?.textContent.includes('Private Repository')).catch(async e=>{console.log('public check diagnostic',await a.p.locator('#sync-message').innerText(),server.calls);throw e});assert(await a.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-config-v1'))===null,'public repo stored');server.private=true;await connect(a.p);await a.p.waitForSelector('#sync-password-form');assert((await a.p.locator('h3').innerText()).includes('创建第一份加密备份'),'automatic create password');assert(await a.p.locator('[name=confirmation]').count()===1,'new password confirmation');
 await a.p.locator('[name=password]').fill(password);await a.p.locator('[name=confirmation]').fill(password);await a.p.locator('#sync-password-form [type=submit]').click();await a.p.waitForSelector('#sync-first-upload');await a.p.locator('#sync-first-upload').click();await waitReady(a.p);assert(server.writes===1,'first upload');assert(canonical((await decrypt(server.remote.text)).data)===canonical(await read(a.p)),'full remote backup');await shot(a.p,'connected')
 await mutate(a.p,[{store:'tasks',value:task('local-new','Local new task')}]);await a.p.locator('#sync-now').click();await waitReady(a.p);assert(server.writes===2,'local-only upload')
 const b=await device();await open(b.p);await connect(b.p);await b.p.waitForSelector('#sync-password-form');assert((await b.p.locator('h3').innerText()).includes('发现已有 GitHub 备份'),'automatic unlock');assert(await b.p.locator('[name=confirmation]').count()===0,'existing password confirmation exposed');assert((await b.p.locator('#sync-password-form [type=submit]').innerText())==='解锁并检查','unlock label');await shot(b.p,'unlock');const freshBefore=canonical(await read(b.p)),baselineBefore=await b.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-state-v1')),remoteBefore=server.remote.text
 await b.p.locator('[name=password]').fill('wrong-password');await b.p.locator('#sync-password-form [type=submit]').click();await b.p.waitForFunction(()=>document.querySelector('#sync-message')?.textContent.includes('数据密码不正确'));assert(canonical(await read(b.p))===freshBefore,'wrong password local mutation');assert(server.remote.text===remoteBefore,'wrong password remote mutation');assert(await b.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-state-v1'))===baselineBefore,'wrong password baseline')
 await b.p.locator('[name=password]').fill(password);await b.p.locator('#sync-password-form [type=submit]').click();await b.p.waitForSelector('#sync-use-remote');assert(await b.p.locator('#sync-use-local').count()===0,'fresh upload exposed');assert((await b.p.locator('#github-sync-body').innerText()).includes('发现 GitHub 备份'),'fresh restore state');await b.p.locator('#sync-use-remote').click();await shot(b.p,'restore-preview');await b.p.locator('#sync-confirm-restore').click();await b.p.waitForFunction(()=>!document.querySelector('dialog[open]'));assert(canonical(await read(b.p))===canonical((await decrypt(server.remote.text)).data),'new device restore')
 await mutate(b.p,[{store:'tasks',value:task('remote-new','Remote new task')}]);await b.p.locator('#open-management').click();await b.p.locator('#more-github-sync').click();await b.p.locator('#sync-now').click();await waitReady(b.p);assert(server.writes===3,'second device upload')
 await a.p.locator('#sync-now').click();await a.p.waitForSelector('#sync-use-remote');assert((await a.p.locator('#github-sync-body').innerText()).includes('GitHub 上有新数据'),'remote-only state');assert(server.writes===3,'remote-only overwrite');await a.p.locator('#sync-use-remote').click();assert(await a.p.locator('#sync-export-local').count()===1,'local backup option');await a.p.locator('#sync-confirm-restore').click();await a.p.waitForFunction(()=>!document.querySelector('dialog[open]'))
 await mutate(a.p,[{store:'tasks',value:task('divergent-a','Local divergent')}]);await mutate(b.p,[{store:'tasks',value:task('divergent-b','Remote divergent')}]);await b.p.locator('#sync-now').click();await waitReady(b.p);assert(server.writes===4,'remote divergence upload')
 await a.p.locator('#open-management').click();await a.p.locator('#more-github-sync').click();await a.p.locator('#sync-now').click();await a.p.waitForSelector('#sync-use-local');assert((await a.p.locator('#github-sync-body').innerText()).includes('检测到数据冲突'),'conflict missing');assert(server.writes===4,'conflict automatic PUT');await shot(a.p,'conflict');await a.p.locator('#sync-use-local').click();await shot(a.p,'replacement-confirm');assert(server.writes===4,'replacement before confirm');await a.p.locator('#sync-confirm-upload').click();await waitReady(a.p);assert(server.writes===5,'explicit replacement')
 await mutate(a.p,[{store:'tasks',value:task('race-local','Race local')}]);server.race=true;const attempts=server.attempts,baselineRace=await a.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-state-v1'));await a.p.locator('#sync-now').click();await a.p.waitForFunction(()=>document.querySelector('#sync-message')?.textContent.includes('并发数据冲突'));assert(server.attempts===attempts+1,'PUT automatically retried');assert(await a.p.evaluate(()=>localStorage.getItem('fitlog-github-sync-state-v1'))===baselineRace,'race advanced baseline');await shot(a.p,'race-stopped')
 await a.p.locator('#sync-now').click();await a.p.waitForSelector('#sync-use-local');await a.p.locator('#sync-cancel').click();await waitReady(a.p);await a.c.setOffline(true);const offlineData=canonical(await read(a.p));await a.p.locator('#sync-now').click();await a.p.waitForFunction(()=>document.querySelector('#sync-message')?.textContent.includes('当前离线'));assert(canonical(await read(a.p))===offlineData,'offline data mutation');await shot(a.p,'offline');await a.c.setOffline(false)
 await a.p.locator('#sync-disconnect').click();await a.p.locator('#sync-confirm-disconnect').click();await a.p.waitForSelector('#sync-connect-form');assert(canonical(await read(a.p))===offlineData,'disconnect business mutation');assert(await a.p.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('fitlog-github-sync-')))===false,'disconnect metadata');assert(server.remote,'disconnect deleted remote');assert(!errors.length,JSON.stringify(errors));console.log(JSON.stringify({mode:prod?'production-mocked':'local-mocked',width,writes:server.writes,attempts:server.attempts,stores:14,errors}));for(const c of contexts)await c.close()
}
await browser.close()
