// Computed geometry across six shared renderers. Writes only isolated synthetic contexts.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',prod=base.includes('github.io'),receipts=[]
const configs=process.env.FITLOG_VISUAL_SMOKE?[[390,844,100,false],[320,812,140,false]]:prod?[[390,844,100,false],[390,844,100,true],[320,812,140,false],[320,812,140,true]]:[[320,812],[375,812],[390,844],[430,932]].flatMap(([w,h])=>[100,120,140].flatMap(s=>[false,true].map(r=>[w,h,s,r])))
const modules=[['food-library','食物库','食物'],['exercise-library','动作库','动作'],['workout-templates','训练模板','训练模板'],['diet-templates','饮食模板','饮食模板'],['nutrition-strategies','营养模板','营养模板'],['habits','习惯','习惯']]
const now='2026-10-07T00:00:00Z',data={foods:[],exercises:[],workoutTemplates:[],dietTemplates:[],nutritionStrategyTemplates:[],nutritionStrategyVariants:[],nutritionStrategyPhases:[],habits:[],habitCheckIns:[]}
for(let i=0;i<2;i++){const stamp={createdAt:now,updatedAt:now};data.foods.push({id:'v-food-'+i,name:'示例食物 '+i,referenceGrams:100,calories:120,...stamp});data.exercises.push({id:'v-ex-'+i,name:'示例动作 '+i,notes:'力量训练动作',...stamp});data.workoutTemplates.push({id:'v-workout-'+i,name:'示例训练 '+i,exercises:[{id:'v-item-'+i,exerciseId:'v-ex-'+i,exerciseName:'示例动作 '+i,sets:[{id:'v-set-'+i,reps:10}]}],...stamp});data.dietTemplates.push({id:'v-diet-'+i,name:'示例饮食 '+i,items:[{id:'v-di-'+i,foodId:'v-food-'+i,foodName:'示例食物 '+i,grams:100,referenceGrams:100,calories:120}],...stamp});data.nutritionStrategyTemplates.push({id:'v-nutrition-'+i,name:'示例营养 '+i,...stamp});data.nutritionStrategyVariants.push({id:'v-variant-'+i,templateId:'v-nutrition-'+i,name:'训练日',calories:2000,sortOrder:0,...stamp});data.habits.push({id:'v-habit-'+i,name:'示例习惯 '+i,active:true,sortOrder:i,...stamp})}
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
try{for(const[width,height,scale,reduced]of configs){
 const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,serviceWorkers:'block',timezoneId:'Asia/Shanghai',reducedMotion:reduced?'reduce':'no-preference'})
 try{
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000)
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management');await page.addStyleTag({content:`html{font-size:${scale}%}`})
 const put=async value=>page.evaluate(async value=>{const d=await new Promise((r,j)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(value),'readwrite');for(const[name,rows]of Object.entries(value)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},value)
 const click=selector=>page.locator(selector).evaluate(e=>e.click())
 const title=label=>page.waitForFunction(label=>document.querySelector('.modal-head h2')?.textContent===label,label)
 const settle=()=>page.evaluate(async()=>{await new Promise(requestAnimationFrame);await Promise.all(document.querySelector('dialog').getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{})))})
 const enter=async(id,label)=>{await click('#more-'+id);await title(label);await page.locator('.manager-surface .manager-toolbar').waitFor();await page.waitForFunction(()=>document.querySelector('dialog').dataset.managementLoading==='false')}
 const back=async()=>{await click('[data-workspace-back]');await title('管理与设置')}
 const bounds=async()=>{const v=await page.evaluate(()=>{const d=document.querySelector('dialog[open]'),body=d.querySelector('.modal-body');return{same:d===window.visualDialog,one:document.querySelectorAll('.sheet[open]').length,lock:document.body.style.position==='fixed',overflow:document.documentElement.scrollWidth>innerWidth+1||body.scrollWidth>body.clientWidth+1,children:[...d.querySelectorAll('.manager-surface *')].filter(e=>e.getClientRects().length).some(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<0-.5||r.right>innerWidth+.5)}),toolbar:d.querySelectorAll('.manager-toolbar').length,create:d.querySelectorAll('.manager-create:not([hidden])').length}});assert.equal(v.same,true);assert.equal(v.one,1);assert.equal(v.lock,true);assert.equal(v.overflow,false);assert.equal(v.children,false);assert.equal(v.toolbar,1);assert.ok(v.create<=1)}
 const shot=async(id,state)=>{if(!reduced&&((width===390&&scale===100)||(width===320&&scale===140)))await page.screenshot({path:`/tmp/manager-visual-${prod?'prod':'local'}-${width}-${scale}-${state}-${id}.png`})}
 const compare=(items,key,tolerance=2)=>{const values=items.map(x=>x[key]);assert.ok(Math.max(...values)-Math.min(...values)<=tolerance,`${key}: ${JSON.stringify(values)}`);return Math.max(...values)-Math.min(...values)}
 await put(data);await page.locator('#open-management').click();await title('管理与设置');await settle();await page.evaluate(()=>window.visualDialog=document.querySelector('dialog[open]'))
 const geometry=[]
 for(const[id,label,entity]of modules){await enter(id,label);await page.locator('.manager-row-main').first().waitFor();await settle();await bounds();assert.equal(await page.locator('.manager-create').getAttribute('aria-label'),'新建'+entity);assert.equal((await page.locator('.manager-create').innerText()).trim(),'+ 新建');assert.equal(await page.locator('.manager-empty').count(),0);assert.ok(await page.locator('.manager-row-main').count()>=2)
  const m=await page.evaluate(()=>{const q=s=>document.querySelector(s),r=s=>q(s).getBoundingClientRect(),c=s=>getComputedStyle(q(s)),t=r('.manager-toolbar'),b=r('.manager-create'),slot=r('.manager-toolbar-main'),list=r('.manager-list'),row=r('.manager-row-main'),name=r('.manager-row-title'),meta=r('.manager-row-meta'),ch=r('.manager-row-trailing > svg');return{toolbarTop:t.top,toolbarHeight:t.height,createHeight:b.height,slotHeight:slot.height,createRadius:c('.manager-create').borderRadius,createPrimary:q('.manager-create').classList.contains('primary'),listRadius:c('.manager-list').borderRadius,listBorder:c('.manager-list').borderTopWidth,listBg:c('.manager-list').backgroundColor,listShadow:c('.manager-list').boxShadow,rowHeight:row.height,rowMin:parseFloat(c('.manager-row-main').minHeight),paddingLeft:parseFloat(c('.manager-row-main').paddingLeft),paddingRight:parseFloat(c('.manager-row-main').paddingRight),titleX:name.left-list.left,metaX:meta.left-list.left,chevronRight:list.right-ch.right,chevronSize:ch.width,titleFont:c('.manager-row-title').fontSize,metaFont:c('.manager-row-meta').fontSize,divider:c('.manager-row + .manager-row').borderTopWidth,searchFont:q('input[type=search]')?parseFloat(c('input[type=search]').fontSize):null}})
  assert.ok(m.createHeight>=44);assert.equal(m.createPrimary,false);assert.equal(m.listRadius,'17px');assert.equal(m.listBorder,'1px');assert.equal(m.listShadow,'none');assert.equal(m.rowMin,66);assert.equal(m.chevronSize,18);assert.equal(m.divider,'1px');if(m.searchFont)assert.ok(m.searchFont>=16);geometry.push({id,...m});await shot(id,'populated')
  const search=page.locator('.manager-toolbar input[type=search]');if(await search.count()){await search.fill('zzzz-no-match');await page.locator('.manager-no-results').waitFor();assert.equal(await page.locator('.manager-empty-action,.manager-no-results .primary').count(),0);await settle();await bounds();await shot(id,'no-results');await search.fill('');await page.locator('.manager-row-main').first().waitFor()}
  if(id==='habits'){await click('#habit-reorder');assert.equal(await page.locator('.manager-create').isVisible(),false);assert.equal(await page.locator('.manager-row.is-reordering').count(),2);await click('#habit-reorder');await page.locator('[data-habit-edit]').first().waitFor()}
  await back()
 }
 const delta={};for(const key of ['toolbarTop','toolbarHeight','createHeight','rowHeight','paddingLeft','paddingRight','titleX','metaX','chevronRight'])delta[key]=compare(geometry,key)
 for(const key of ['listRadius','listBorder','listBg','listShadow','titleFont','metaFont','createRadius'])assert.equal(new Set(geometry.map(m=>m[key])).size,1,key)
 // Same-frame continuous switching, with two rows restored on every visit.
 for(let i=0;i<20;i++)for(const[id,label]of modules){await enter(id,label);await page.locator('.manager-row-main').first().waitFor();await bounds();assert.equal(await page.locator('.manager-empty').count(),0);await back()}
 await click('.modal-head [data-close]');assert.equal(await page.locator('dialog').count(),0);assert.equal(await page.evaluate(()=>document.body.style.position==='fixed'),false)
 // Existing direct entrances must mount exactly the same six-manager primitives.
 await page.locator('[data-tab=food]').click();await page.locator('.food-content-body').waitFor();await page.locator('#food-library').click();await page.locator('.manager-row-main').first().waitFor();await settle();const directFood=await page.locator('.manager-list').evaluate(e=>({radius:getComputedStyle(e).borderRadius,rowPadding:getComputedStyle(e.querySelector('.manager-row-main')).paddingLeft}));assert.equal(directFood.radius,geometry[0].listRadius);assert.equal(parseFloat(directFood.rowPadding),geometry[0].paddingLeft);await click('.modal-head [data-close]')
 await page.locator('[data-tab=today]').click();await page.locator('#today-habits-manage').waitFor();await click('#today-habits-manage');await page.locator('.manager-row-main').first().waitFor();assert.equal(await page.locator('.manager-toolbar').count(),1);await click('.modal-head [data-close]')
 // Each empty module starts with its own clean, synthetic browser context.
 const empty=[]
 for(const[id,label,entity]of modules){const ec=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,serviceWorkers:'block',timezoneId:'Asia/Shanghai',reducedMotion:reduced?'reduce':'no-preference'});try{const ep=await ec.newPage();ep.on('pageerror',e=>errors.push(e.message));await ep.goto(base,{waitUntil:'networkidle'});await ep.waitForSelector('#open-management');await ep.addStyleTag({content:`html{font-size:${scale}%}`});await ep.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});await new Promise((r,j)=>{const t=d.transaction(['foods','exercises','workoutTemplates','dietTemplates','nutritionStrategyTemplates','nutritionStrategyVariants','nutritionStrategyPhases','habits','habitCheckIns'],'readwrite');for(const n of t.objectStoreNames)t.objectStore(n).clear();t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()});await ep.locator('#open-management').click();await ep.locator('#more-'+id).click();await ep.locator('.manager-empty-action').waitFor();await ep.evaluate(async()=>Promise.all(document.querySelector('dialog').getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))));assert.equal(await ep.locator('.manager-empty-action').count(),1);assert.equal(await ep.locator('.manager-create').isVisible(),false);assert.equal(await ep.locator('.manager-empty-title').innerText(),'还没有'+entity);assert.equal(await ep.locator('.manager-empty-action').getAttribute('aria-label'),'新建'+entity);const m=await ep.locator('.manager-empty-action').evaluate(e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return{height:r.height,radius:c.borderRadius,font:c.fontSize,padding:c.padding,primary:e.classList.contains('primary'),overflow:document.documentElement.scrollWidth>innerWidth+1||e.closest('.modal-body').scrollWidth>e.closest('.modal-body').clientWidth+1}});assert.ok(m.height>=48);assert.equal(m.primary,true);assert.equal(m.overflow,false);empty.push({id,...m});if(!reduced&&((width===390&&scale===100)||(width===320&&scale===140)))await ep.screenshot({path:`/tmp/manager-visual-${prod?'prod':'local'}-${width}-${scale}-empty-${id}.png`})}finally{await ec.close()}}
 const emptyHeightDelta=compare(empty,'height');for(const key of ['radius','font','padding'])assert.equal(new Set(empty.map(m=>m[key])).size,1,key)
 assert.deepEqual(errors,[]);const receipt={width,height,scale,reduced,geometry,delta,empty,emptyHeightDelta,sixSharedManagers:true,stressRounds:20,identity:true,directEntries:true,overflow:false,errors,physicalSafari:'Pending',originalPwa:'Pending'};receipts.push(receipt);console.log(JSON.stringify(receipt))
 }finally{await context.close()}
}await fs.writeFile(`/tmp/manager-visual-${prod?'prod':'local'}-receipt.json`,JSON.stringify(receipts,null,2))}finally{await browser.close()}
