// Isolated synthetic data only. Actual native dialog identity, never an ID/string substitute.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5183/fitlog-lite/',prod=base.includes('github.io'),receipts=[]
const sizes=process.env.FITLOG_WORKSPACE_SMOKE?[[390,844]]:prod?[[390,844],[430,932]]:[[320,812],[375,812],[390,844],[430,932]]
const scales=process.env.FITLOG_WORKSPACE_SMOKE?[100]:[100,120,140],modes=process.env.FITLOG_WORKSPACE_SMOKE?[false]:[false,true]
const entries=[['food-library','食物库'],['exercise-library','动作库'],['workout-templates','训练模板'],['diet-templates','饮食模板'],['nutrition-strategies','营养模板'],['habits','习惯'],['import','导入数据'],['backup','备份与恢复'],['github-sync','GitHub 同步'],['ai-settings','AI 设置'],['diagnostics','版本诊断'],['about','关于 FitLog Lite']]
const creates=[['food-library','食物'],['exercise-library','动作'],['workout-templates','训练模板'],['diet-templates','饮食模板'],['nutrition-strategies','营养模板'],['habits','习惯']]
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
try{for(const [width,height]of sizes)for(const scale of scales)for(const reduced of modes){
 const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block',reducedMotion:reduced?'reduce':'no-preference'})
 try{
 const page=await context.newPage(),errors=[],failedRequests=[];page.on('requestfailed',request=>failedRequests.push(request.url()));page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000)
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management');await page.addStyleTag({content:`html{font-size:${scale}%}`})
 const put=async data=>page.evaluate(async data=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
 await put({foods:[],exercises:[],workoutTemplates:[],dietTemplates:[],nutritionStrategyTemplates:[],nutritionStrategyVariants:[],nutritionStrategyPhases:[],habits:[],habitCheckIns:[]})
 const heading=title=>page.waitForFunction(title=>document.querySelector('.modal-head h2')?.textContent===title,title)
 const click=async selector=>{await page.locator(selector).evaluate(e=>e.click())}
 const settle=()=>page.evaluate(async()=>{await new Promise(requestAnimationFrame);await Promise.all(document.querySelector('dialog').getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{})))})
 const shot=async name=>{if(!reduced&&((width===390&&scale===100)||(width===320&&scale===140)))await page.screenshot({path:`/tmp/management-${prod?'prod':'local'}-${width}-${scale}-${name}.png`})}
 let maxTopDelta=0,maxHeightDelta=0,maxPrimary=0,identityChecks=0,baseline
 const open=async()=>{await page.locator('#open-management').click();await heading('管理与设置');await settle();baseline=await page.evaluate(()=>{window.workspaceDialog=document.querySelector('dialog[open]');window.workspaceHead=workspaceDialog.querySelector('.modal-head');window.workspaceBody=workspaceDialog.querySelector('.modal-body');const r=workspaceDialog.getBoundingClientRect();return{top:r.top,height:r.height}})}
 const check=async title=>{
  await heading(title);await page.waitForFunction(()=>document.querySelector('dialog')?.dataset.managementLoading==='false');if(creates.some(e=>entries.find(x=>x[0]===e[0])[1]===title))await page.locator('.manager-toolbar').waitFor();const m=await page.evaluate(()=>{const d=document.querySelector('.sheet[open]'),r=d.getBoundingClientRect(),h=d.querySelector('.modal-head'),t=h.querySelector('h2').getBoundingClientRect(),x=h.querySelector('[data-close]').getBoundingClientRect(),b=h.querySelector('[data-workspace-back]'),q=b.getBoundingClientRect(),body=d.querySelector('.modal-body');return{identity:d===workspaceDialog,header:h===workspaceHead,body:body===workspaceBody,top:r.top,height:r.height,count:document.querySelectorAll('.sheet[open]').length,lock:document.body.style.position==='fixed',overflow:document.documentElement.scrollWidth>innerWidth+1||body.scrollWidth>body.clientWidth+1,overlap:t.right>x.left+.5||!b.hidden&&q.right>t.left+.5,xWidth:x.width,xHeight:x.height,backWidth:b.hidden?44:q.width,backHeight:b.hidden?44:q.height,variant:d.dataset.sheetVariant}})
  identityChecks++;maxPrimary=Math.max(maxPrimary,m.count);maxTopDelta=Math.max(maxTopDelta,Math.abs(m.top-baseline.top));maxHeightDelta=Math.max(maxHeightDelta,Math.abs(m.height-baseline.height));assert.equal(m.identity,true);assert.equal(m.header,true);assert.equal(m.body,true);assert.equal(m.count,1);assert.equal(m.lock,true);assert.equal(m.overflow,false);assert.equal(m.overlap,false);assert.equal(m.variant,'large');for(const v of [m.xWidth,m.xHeight,m.backWidth,m.backHeight])assert.ok(v>=44);assert.ok(maxTopDelta<=2&&maxHeightDelta<=2,JSON.stringify(m));return m
 }
 const back=async title=>{await click('[data-workspace-back]');if(await page.locator('.confirm-dialog[open]').count())await click('.confirm-dialog [data-confirm]');await check(title)}
 const close=async()=>{await click('.modal-head [data-close]');assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.evaluate(()=>document.body.classList.contains('sheet-open')||document.body.style.position==='fixed'),false)}
 await open();await check('管理与设置');assert.equal(await page.locator('[data-workspace-back]').isVisible(),false);await shot('hub')
 // Six empty managers: exactly one visible create control, with full accessible name.
 for(const[id,entity]of creates){await click('#more-'+id);await check(entries.find(e=>e[0]===id)[1]);const create=page.locator('dialog[open]').getByRole('button',{name:'新建'+entity,exact:true});await create.waitFor();assert.equal(await create.count(),1,id);assert.ok(await create.isVisible());assert.ok(await create.evaluate(e=>e.classList.contains('primary')));assert.ok(await create.evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44}));await create.click();await check('新建'+entity);assert.equal(await page.locator('.modal-body').evaluate(e=>e.scrollTop),0);await back(entries.find(e=>e[0]===id)[1]);await back('管理与设置')}
 const now='2026-10-07T00:00:00Z',food={id:'w-food',name:'工作区测试食物',referenceGrams:100,calories:120,createdAt:now,updatedAt:now}
 await put({foods:[food],exercises:Array.from({length:36},(_,i)=>({id:'w-ex-'+i,name:'工作区动作 '+String(i).padStart(2,'0'),notes:'力量训练动作',createdAt:now,updatedAt:now})),habits:Array.from({length:25},(_,i)=>({id:'w-habit-'+i,name:'工作区习惯 '+i,active:true,sortOrder:i,createdAt:now,updatedAt:now})),workoutTemplates:[{id:'w-template',name:'工作区训练组合',exercises:[{id:'w-item',exerciseId:'w-ex-0',exerciseName:'工作区动作 00',sets:[{id:'w-set',reps:10}]}],createdAt:now,updatedAt:now}],dietTemplates:[{id:'w-diet',name:'工作区饮食组合',items:[{id:'w-food-item',foodId:food.id,foodName:food.name,grams:100,referenceGrams:100,calories:120}],createdAt:now,updatedAt:now}],nutritionStrategyTemplates:[{id:'w-strategy',name:'工作区营养模板',createdAt:now,updatedAt:now}],nutritionStrategyVariants:[{id:'w-variant',templateId:'w-strategy',name:'训练日',calories:2100,sortOrder:0,createdAt:now,updatedAt:now}]})
 // Configure only an invented local profile. Opening settings must make no requests.
 await page.evaluate(()=>{const profile={id:'workspace-ai',name:'合成服务',preset:'custom',protocol:'openai-chat-completions',baseUrl:'https://workspace.invalid/v1',model:'synthetic-model',toolCapability:'supported',createdAt:'2026-10-07T00:00:00Z',updatedAt:'2026-10-07T00:00:00Z'};localStorage.setItem('fitlog-ai-profiles-v1',JSON.stringify([profile]));localStorage.setItem('fitlog-ai-active-profile-v1',profile.id);localStorage.setItem('fitlog-ai-key-v1:'+profile.id,'synthetic-workspace-key');localStorage.setItem('fitlog-ai-privacy-ack-v1','1')})
 // All 12 L2 entries, with the same real dialog throughout.
 for(const[id,title]of entries){await click('#more-'+id);await check(title);await settle();await shot(id);if(id==='diagnostics')await page.waitForSelector('[data-diagnostic="App build"]');await back('管理与设置')}
 for(const[id,entity]of creates){await click('#more-'+id);await check(entries.find(e=>e[0]===id)[1]);const create=page.locator('dialog[open]').getByRole('button',{name:'新建'+entity,exact:true});await create.waitFor();assert.equal(await create.count(),1,id);assert.equal((await create.innerText()).trim(),'+ 新建');assert.ok(await create.evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44}));await back('管理与设置')}
 // Hub scroll is saved before departure and restored without re-opening the Hub.
 const hubScroll=await page.locator('.modal-body').evaluate(e=>{e.scrollTop=180;return e.scrollTop});assert.ok(hubScroll>0)
 await click('#more-ai-settings');await check('AI 设置');await back('管理与设置');assert.ok(Math.abs(await page.locator('.modal-body').evaluate(e=>e.scrollTop)-hubScroll)<=1)
 await click('#more-exercise-library');await page.locator('#exercise-library-search').fill('工作区动作');await page.locator('.modal-body').evaluate(e=>e.scrollTop=240);const managerScroll=await page.locator('.modal-body').evaluate(e=>e.scrollTop);assert.ok(managerScroll>0)
 await click('[data-edit-exercise="w-ex-20"]');await check('编辑动作');await shot('exercise-editor');await click('#delete-exercise');assert.equal(await page.locator('.confirm-dialog[open]').count(),1);assert.equal(await page.evaluate(()=>document.querySelector('.sheet[open]')===workspaceDialog),true);await click('.confirm-dialog [data-cancel]');await check('编辑动作');await back('动作库');assert.equal(await page.locator('#exercise-library-search').inputValue(),'工作区动作');assert.ok(Math.abs(await page.locator('.modal-body').evaluate(e=>e.scrollTop)-managerScroll)<=1)
 await click('#new-exercise');await check('新建动作');assert.equal(await page.locator('.modal-body').evaluate(e=>e.scrollTop),0);await page.locator('#exercise-form [name=name]').fill('工作区动作新建');await click('#exercise-form [type=submit]');await check('动作库');assert.equal(await page.locator('#exercise-library-search').inputValue(),'工作区动作');assert.ok(Math.abs(await page.locator('.modal-body').evaluate(e=>e.scrollTop)-managerScroll)<=1);await back('管理与设置')
 await click('#more-habits');await click('[data-habit-edit="w-habit-0"]');await check('编辑习惯');await settle();await shot('habit-editor');const habit=await page.locator('.habit-editor-actions').evaluate(e=>{const r=e.querySelector('button').getBoundingClientRect();let overlap=0;for(const field of e.closest('form').querySelectorAll('input,textarea,fieldset,.habit-target-row,.habit-status-section')){if(!field.getClientRects().length)continue;const q=field.getBoundingClientRect();if(Math.min(r.right,q.right)>Math.max(r.left,q.left))overlap=Math.max(overlap,Math.min(r.bottom,q.bottom)-Math.max(r.top,q.top))}return{position:getComputedStyle(e).position,overlap,height:r.height,radius:getComputedStyle(e.querySelector('button')).borderRadius}});assert.equal(habit.position,'static');assert.equal(habit.overlap,0);assert.equal(habit.height,52);assert.equal(habit.radius,'15px');await back('习惯');await click('#habit-new');await check('新建习惯');await back('习惯');await back('管理与设置')
 await click('#more-workout-templates');await click('[data-edit-workout-template]');await check('编辑训练模板');await back('训练模板');await back('管理与设置')
 await click('#more-nutrition-strategies');await click('[data-strategy-detail]');await check('编辑营养模板');await click('#strategy-show-detail');await check('营养模板详情');await back('编辑营养模板');await back('营养模板');await back('管理与设置')
 // AI root with no saved service is exercised above; configure through the actual existing editor.
 await click('#more-ai-settings');if(await page.locator('.ai-profile-form').count()){await page.locator('[name=model]').fill('synthetic-model');await page.locator('[name=apiKey]').fill('synthetic-workspace-key');await page.locator('#ai-privacy-ack').check();await page.locator('details.ai-advanced').evaluate(e=>e.open=true);await click('#ai-save-only')}
 await check('AI 设置');await click('#ai-voice-settings');await check('语音');await back('AI 设置');await back('管理与设置')
 const cdp=await context.newCDPSession(page)
 const listenerCounts=async()=>{const {result}=await cdp.send('Runtime.evaluate',{expression:'window.workspaceDialog'});const {listeners}=await cdp.send('DOMDebugger.getEventListeners',{objectId:result.objectId});return listeners.map(e=>e.type).sort()}
 const listenersBefore=await listenerCounts()
 // 20 complete consecutive management rounds; one topbar entry for the whole sequence.
 for(let i=0;i<20;i++)for(const id of ['food-library','exercise-library','workout-templates','diet-templates','nutrition-strategies','habits','ai-settings','github-sync']){await click('#more-'+id);await check(entries.find(e=>e[0]===id)[1]);await back('管理与设置')}
 const listenersAfter=await listenerCounts();assert.deepEqual(listenersAfter,listenersBefore);await cdp.detach()
 await settle();const residual=await page.locator('.modal-body').evaluate(e=>({transform:getComputedStyle(e).transform,opacity:getComputedStyle(e).opacity,pointer:getComputedStyle(e).pointerEvents,animations:e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length,inline:e.style.cssText}));assert.equal(residual.transform,'none');assert.equal(residual.opacity,'1');assert.notEqual(residual.pointer,'none');assert.equal(residual.animations,0);assert.equal(residual.inline,'');await close()
 // X exits the entire workspace at root, manager, editor and AI depths. Reopen starts Hub.
 for(const target of ['hub','exercise','editor','ai']){await open();if(target==='exercise'||target==='editor'){await click('#more-exercise-library');await check('动作库');if(target==='editor'){await click('#new-exercise');await check('新建动作')}}if(target==='ai'){await click('#more-ai-settings');await check('AI 设置')}await close()}
 // Close an in-flight model-list request. A late mocked result cannot revive a closed editor.
 for(const exit of ['back','close']){
 let pending,release;const requested=new Promise(r=>pending=r),held=new Promise(r=>release=r)
 await context.route('https://workspace.invalid/**',async route=>{pending();await held;await route.fulfill({json:{data:[{id:'late-synthetic-model'}]}}).catch(()=>{})})
 await open();await click('#more-ai-settings');await check('AI 设置');await click('[data-edit]');await check('编辑 AI 服务');await click('#ai-list-models');await requested;if(exit==='back'){await back('AI 设置');await page.waitForTimeout(80);assert.ok(failedRequests.some(url=>url.startsWith('https://workspace.invalid/')),'Back aborts editor request');await close()}else await close();release();await page.waitForTimeout(80);assert.equal(await page.locator('dialog').count(),0);assert.ok(failedRequests.some(url=>url.startsWith('https://workspace.invalid/')),'model request aborted');await context.unroute('https://workspace.invalid/**')
 }
 // Closing GitHub setup aborts its first fetch and prevents follow-up connection writes.
 for(const exit of ['back','close']){
 let syncPending,syncRelease;const syncRequested=new Promise(r=>syncPending=r),syncHeld=new Promise(r=>syncRelease=r)
 await context.route('https://api.github.com/**',async route=>{syncPending();await syncHeld;await route.fulfill({json:{private:true,default_branch:'main'}}).catch(()=>{})})
 await open();await click('#more-github-sync');await check('GitHub 同步');await page.locator('#sync-connect-form [name=token]').fill('synthetic-workspace-token');await click('#sync-connect-form [type=submit]');await syncRequested;if(exit==='back'){await back('管理与设置');await close()}else await close();syncRelease();await page.waitForTimeout(80);assert.ok(failedRequests.some(url=>url.startsWith('https://api.github.com/')),'sync request aborted');assert.equal(await page.evaluate(()=>localStorage.getItem('fitlog-github-sync-token-v1')),null);assert.equal(await page.locator('dialog').count(),0);await context.unroute('https://api.github.com/**')
 }
 // An intentionally delayed file read also observes route disposal, without mounting a preview.
 await page.evaluate(()=>{window.originalFileText=File.prototype.text;File.prototype.text=function(){return new Promise(resolve=>{window.finishImportRead=()=>resolve('[{"name":"late-file","referenceGrams":100,"calories":1}]')})}})
 await open();await click('#more-import');await check('导入数据');await page.locator('#import-file').setInputFiles({name:'late.json',mimeType:'application/json',buffer:Buffer.from('[]')});await close();await page.evaluate(()=>{finishImportRead();File.prototype.text=originalFileText});await page.waitForTimeout(80);assert.equal(await page.locator('dialog').count(),0)
 assert.deepEqual(errors,[]);const receipt={width,height,scale,reduced,identityChecks,maxPrimary,maxTopDelta,maxHeightDelta,levels:12,sixManagers:true,emptySingleCreate:true,hubScroll,managerScroll,queryRestored:true,saveRefresh:true,newScroll:0,stressRounds:20,habit,residual,closeAtAllDepths:true,listenersBefore,listenersAfter,closedModelRequest:true,closedSyncRequest:true,backAbortsRequests:true,closedFileRead:true,confirmationPreservesParent:true,errors,physicalSafari:'Pending',originalInstalledPwa:'Pending'};receipts.push(receipt);console.log(JSON.stringify(receipt))
 }finally{await context.close()}
}await fs.writeFile(`/tmp/management-${prod?'prod':'local'}-receipt.json`,JSON.stringify(receipts,null,2))}finally{await browser.close()}
