// Layout assertions use isolated synthetic records and mocked Safe Area values, never real user data.
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5175/fitlog-lite/',prod=base.includes('github.io')
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
const sizes=prod?[[390,844],[430,932]]:[[320,812],[375,812],[390,844],[430,932]]
const model='synthetic-long-chat-model-identifier-2026',visionModel='synthetic-long-image-model-identifier-2026'
try { for(const [width,height] of sizes){
 const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true,serviceWorkers:'block',timezoneId:'Asia/Shanghai'})
 try {
  await context.addInitScript(({model,visionModel})=>{const p={id:'layout',preset:'zhipu',protocol:'openai-chat-completions',name:'智谱 · '+model,baseUrl:'https://mock-layout.invalid/v1',model,visionModel,toolCapability:'unknown',visionCapability:'unknown',createdAt:'',updatedAt:''};localStorage.setItem('fitlog-ai-profiles-v1',JSON.stringify([p]));localStorage.setItem('fitlog-ai-active-profile-v1',p.id);localStorage.setItem('fitlog-ai-key-v1:'+p.id,'synthetic-layout-key');localStorage.setItem('fitlog-ai-privacy-ack-v1','1')},{model,visionModel})
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let networkCalls=0;await page.route('https://mock-layout.invalid/**',async r=>{networkCalls++;await r.abort()})
  await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management')
  await page.addStyleTag({content:':root { --safe-area-top: 47px; --safe-area-bottom: 34px; }'})
  const mutate=async(store,values,clear=false)=>page.evaluate(async({store,values,clear})=>{const d=await new Promise((resolve,reject)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});await new Promise((resolve,reject)=>{const t=d.transaction(store,'readwrite'),s=t.objectStore(store);if(clear)s.clear();for(const v of values)s.put(v);t.oncomplete=resolve;t.onerror=()=>reject(t.error)});d.close()},{store,values,clear})
  const read=async store=>page.evaluate(async store=>{const d=await new Promise(resolve=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>resolve(q.result)});const rows=await new Promise(resolve=>{const q=d.transaction(store).objectStore(store).getAll();q.onsuccess=()=>resolve(q.result)});d.close();return rows},store)
  const date=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})
  const now='2026-09-28T10:00:00.000Z',long='这是一个很长的中文名称用于验证移动布局不会溢出或遮挡操作'
  await mutate('foods',[],true)
  await mutate('exercises',[],true)
  await mutate('workouts',Array.from({length:8},(_,i)=>({id:'layout-workout-'+i,date,startedAt:now,finishedAt:now,createdAt:now,updatedAt:now,exercises:[{id:'layout-ex-'+i,exerciseName:long,sets:[{id:'layout-set-'+i,reps:10,weight:20}]}]})))
  await mutate('tasks',[{id:'layout-task',title:long+long,date,completed:false,tagIds:[],createdAt:now,updatedAt:now}])
  const nav=async tab=>{await page.locator(`[data-tab=${tab}]`).click();await page.waitForTimeout(100);await page.evaluate(()=>scrollTo(0,0))}
  const close=async()=>{await page.locator('dialog [data-close]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}
  const shot=async name=>{await page.waitForTimeout(220);await page.screenshot({path:`/tmp/mobile-layout-${prod?'prod':'local'}-${width}-${name}.png`})}
  const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth && [...document.querySelectorAll('dialog[open] .modal-body')].every(e=>e.scrollWidth<=e.clientWidth)),'horizontal overflow')
  const actions=async selector=>{for(const e of await page.locator(selector).all()){assert.ok(await e.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.height>=44 && e.scrollWidth<=e.clientWidth+1 && s.whiteSpace==='nowrap'}),'short action wraps/clips or target <44')}}
  const shell=async()=>{const v=await page.evaluate(()=>{const bar=document.querySelector('.topbar'),frame=document.querySelector('.app-frame'),nav=document.querySelector('.bottom-nav');return {bar:bar.getBoundingClientRect().top,top:parseFloat(getComputedStyle(frame).paddingTop),bottom:parseFloat(getComputedStyle(frame).paddingBottom),navHeight:nav.getBoundingClientRect().height,targets:[...nav.querySelectorAll('button')].map(e=>e.getBoundingClientRect().height)}});assert.equal(v.top,47);assert.ok(v.bar>=47);assert.ok(v.bottom>=v.navHeight+19);assert.equal(v.targets.length,5);assert.ok(v.targets.every(h=>h>=44));await noOverflow()}
  const bottom=async selector=>{await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.waitForTimeout(60);const b=await page.locator(selector).last().boundingBox(),n=await page.locator('.bottom-nav').boundingBox();assert.ok(b.y+b.height<=n.y+1,'last content under nav');await page.evaluate(()=>scrollTo(0,0))}
  for(const tab of ['today','plan','food','workout','progress']){await nav(tab);await shell();await bottom('#view > :last-child');await shot(tab)}
  await nav('workout');assert.ok(await page.locator('#start-workout').evaluate(e=>e.classList.contains('primary')));for(const id of ['add-cardio','start-pelvic-floor'])assert.ok(await page.locator('#'+id).evaluate(e=>e.classList.contains('primary')&&!e.classList.contains('secondary')));await bottom('.history-row');await actions('.context-actions .text-btn, .training-section-head .text-btn, .training-card-action');await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await shot('workout-bottom')
  await nav('food');await page.locator('#food-library').click();await page.waitForSelector('#new-food');assert.equal(await page.locator('.food-library-actions > button').count(),2);await actions('.food-library-actions > button');assert.ok((await page.locator('.library-empty').innerText()).includes('还没有食物'));await noOverflow();await shot('library-empty');await page.locator('#library-search').fill('不存在');await page.waitForSelector('#clear-food-search');assert.ok((await page.locator('.library-empty').innerText()).includes('没有匹配'));await page.locator('#clear-food-search').click();assert.equal(await page.locator('#library-search').inputValue(),'');await close()
  // Both file chooser buttons reuse the existing parsing / preview / explicit commit path.
  for(const kind of ['csv','json']){
   await page.locator('#food-library').click();await page.waitForSelector('#new-food');await page.locator('#food-import-open').click();assert.equal(await page.locator('dialog[open]').count(),1);await actions('#import-csv,#import-json');const chooser=page.waitForEvent('filechooser');await page.locator('#import-'+kind).click();const fc=await chooser;const food={name:'布局导入'+kind,referenceGrams:100,calories:123,protein:4,carbs:5,fat:6};const body=kind==='csv'?'name,referenceGrams,calories,protein,carbs,fat\n布局导入csv,100,123,4,5,6':JSON.stringify([food]);await fc.setFiles({name:'layout.'+kind,mimeType:kind==='csv'?'text/csv':'application/json',buffer:Buffer.from(body)});await page.waitForSelector('#confirm-import');await page.locator('#confirm-import').click();await page.waitForSelector('#new-food');assert.ok((await read('foods')).some(f=>f.name===food.name));await close()
  }
  await mutate('foods',[{id:'layout-long-food',name:long+long,brand:long+long,referenceGrams:100,calories:123,createdAt:now,updatedAt:now}]);await page.locator('#food-library').click();await page.waitForSelector('#new-food');await noOverflow();await shot('library-list');await page.locator('#new-food').click();await page.waitForSelector('#food-form')
  const form=await page.locator('#food-form').evaluate(form=>{const b=form.getBoundingClientRect(),names=['name','brand','referenceGrams','calories'];return {width:b.width,full:names.map(n=>form.querySelector(`[name=${n}]`).closest('label').getBoundingClientRect().width),macros:['protein','carbs','fat'].map(n=>{const e=form.querySelector(`[name=${n}]`),r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,font:parseFloat(getComputedStyle(e).fontSize),padding:parseFloat(getComputedStyle(e).paddingRight)}})}})
  assert.ok(form.full.every(w=>Math.abs(w-form.width)<2));assert.ok(form.macros.every(m=>m.width>=75 && m.height>=46 && m.font>=16));assert.ok(form.macros.every(m=>m.y===form.macros[0].y));assert.ok(form.macros[1].x>form.macros[0].x && form.macros[2].x>form.macros[1].x);await actions('#food-form [type=submit]');await noOverflow();await shot('food-form')
  await page.locator('[name=name]').fill(long);await page.locator('[name=brand]').fill(long);await page.locator('[name=energyUnit]').selectOption('kJ');await page.locator('[name=calories]').fill('418.4');await page.locator('#food-form [type=submit]').click();await page.waitForSelector('#new-food');assert.ok(Math.abs((await read('foods')).find(f=>f.name===long).calories-100)<1e-8);await close()
  await page.locator('#open-management').click();assert.ok(!(await page.locator('#more-ai-settings').innerText()).includes(model));assert.ok((await page.locator('#more-ai-settings').innerText()).includes('已连接 · 智谱 · 对话与图片已配置'));assert.ok((await page.locator('.settings-section-note').innerText()).includes('更换设备或清除浏览器数据前，请先备份。'));await noOverflow();await shot('management');await page.locator('.modal-body').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('management-bottom');await page.locator('#more-ai-settings').click();assert.ok((await page.locator('.ai-current-service').innerText()).includes(model));assert.ok((await page.locator('.ai-current-service').innerText()).includes(visionModel));assert.equal(networkCalls,0);await noOverflow();await shot('ai-detail');await close()
  // Existing empty-state grammar and other forms are audited without rewriting their behavior.
  await page.locator('#open-management').click();await page.locator('#more-import').click();await page.waitForSelector('#import-csv');assert.equal(await page.locator('#import-json').count(),1);await close()
  for(const destination of ['more-exercise-library','more-workout-templates','more-diet-templates','more-habits']){await page.locator('#open-management').click();await page.locator('#'+destination).click();await noOverflow();await shot(destination);await close()}
  // 120% root font simulation is separate from physical iOS Dynamic Type.
  await page.addStyleTag({content:'html { font-size: 120%; }'})
  for(const tab of ['today','plan','food','workout','progress']){await nav(tab);await shell();await bottom('#view > :last-child');await noOverflow()}
  await nav('food');await page.locator('#food-library').click();await page.waitForSelector('#new-food');await actions('.food-library-actions > button');await noOverflow();await page.locator('#new-food').click();await noOverflow();await shot('font120-food');await close()
  assert.deepEqual(errors,[]);console.log(JSON.stringify({suite:'mobileLayout',width,height,safeAreaMock:true,mainTabs:5,navReserve:true,imports:['CSV','JSON'],macros:3,font120:true,errors}))
 }finally{await context.close()}
}}finally{await browser.close()}
