// Run the pristine approved HTML, then compare actual DOM/computed styles and original screenshots.
// Synthetic disposable app contexts only; the prototype file and real profiles are never altered.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import {createHash} from 'node:crypto'
const reference='design/reference/v4.2/FitLog_V4_2_Prototype.html'
assert.equal(createHash('sha256').update(await fs.readFile(reference)).digest('hex'),'aa8d37f0509035970eb3a26be056eec619066ba308cf5bc8f5911d2458d24687')
const pw=await import(process.env.FITLOG_PLAYWRIGHT_MODULE),engine=process.env.FITLOG_V4_ENGINE||'chromium',base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5186/fitlog-lite/',before=!!process.env.FITLOG_REMAINING_BEFORE
const dir=path.resolve(process.env.FITLOG_QA_ARTIFACT_ROOT||'../../artifacts/v421-remaining-reference-2026-10-10',before?'before':base.includes('github.io')?'prod':engine==='webkit'?'webkit':'local');await fs.mkdir(dir,{recursive:true})
const cases=process.env.FITLOG_V4_SMOKE?[[390,100,'light']]:[...[320,375,390,430].flatMap(w=>[100,120,140,200].flatMap(s=>['light','dark'].map(t=>[w,s,t]))),[844,140,'dark']]
const b=await pw[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.FITLOG_CHROME}:{})}),receipts=[]
const measure=async loc=>loc.evaluate(root=>{const box=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{width:r.width,height:r.height,x:r.x,y:r.y,right:r.right,bottom:r.bottom,padding:s.padding,gap:s.gap,radius:s.borderRadius,border:s.borderWidth,borderColor:s.borderColor,background:s.backgroundColor,image:s.backgroundImage,ink:s.color,font:s.fontFamily,size:s.fontSize,weight:s.fontWeight,line:s.lineHeight}};return{html:root.outerHTML,container:box(root),heading:box(root.querySelector('h3')||root.querySelector('.food-completion-summary>strong')),cells:[...root.querySelectorAll('.goal-mini-item,.gap-item,.remaining-goal')].map(box),labels:[...root.querySelectorAll('.goal-mini-label,.gap-item small')].map(box),values:[...root.querySelectorAll('.goal-mini-item strong,.gap-item strong')].map(box),dots:[...root.querySelectorAll('.goal-mini-dot')].map(box),buttons:[...root.querySelectorAll('button')].map(box),grid:box(root.querySelector('.goal-mini-grid,.gap-grid,.remaining-goals-grid')),actions:root.querySelector('.remaining-actions')?box(root.querySelector('.remaining-actions')):null}})
for(const [width,scale,theme]of cases){
 const c=await b.newContext({viewport:{width,height:width===844?390:844},colorScheme:theme,timezoneId:'Asia/Shanghai',reducedMotion:'reduce',serviceWorkers:'block',isMobile:true,hasTouch:true}),p=await c.newPage(),a=await c.newPage(),errors=[];a.on('pageerror',e=>errors.push(e.message));const prefix=`${width}-${scale}-${theme}`
 try{
 await p.goto(process.env.FITLOG_PROTOTYPE_URL||'http://127.0.0.1:5190/'+reference);const mock=await p.evaluate(()=>({totals:metric(),target:state.goals}))
 await a.goto(base,{waitUntil:'networkidle'});await a.waitForSelector('#open-management');const today=await a.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}),stamp=today+'T01:00:00Z'
 const log={id:'reference-log',date:today,meal:'breakfast',foodName:'合成视觉对照记录',grams:100,referenceGrams:100,caloriesPerReference:mock.totals.cal,totalCalories:mock.totals.cal,totalProtein:mock.totals.p,totalCarbs:mock.totals.c,totalFat:mock.totals.f,createdAt:stamp,updatedAt:stamp}
 const target={id:'reference-target',date:today,calories:mock.target.cal,protein:mock.target.p,carbs:mock.target.c,fat:mock.target.f,createdAt:stamp,updatedAt:stamp}
 const write=async data=>a.evaluate(async data=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[n,rows]of Object.entries(data)){const s=t.objectStore(n);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
 await write({foodLogs:[log],nutritionTargets:[target]});await a.reload({waitUntil:'networkidle'});await a.addStyleTag({content:`html{font-size:${scale}%}`})
 const nav=async tab=>{await a.locator(`[data-tab=${tab}]`).click();await a.waitForSelector('.remaining-goal')};
 const results={width,scale,theme,syntheticActuals:mock.totals,prototypeFontScaling:scale===100?'original untouched':'runtime computed text sizes × font scale; file untouched',modules:{}}
 for(const tab of ['today','food']){
 await p.evaluate(({tab,theme,scale})=>{state.theme=theme;route(tab);render();if(scale!==100){const elements=[document.querySelector('.remaining'),...document.querySelector('.remaining').querySelectorAll('*')];const sizes=elements.map(e=>parseFloat(getComputedStyle(e).fontSize)*scale/100);elements.forEach((e,i)=>e.style.fontSize=sizes[i]+'px')}},{tab,theme,scale})
 await a.locator(`[data-tab=${tab}]`).click();await a.waitForSelector(tab==='today'?'[data-today-remaining] .food-completion-strip':'.food-remaining');const pl=p.locator('.remaining'),al=a.locator(tab==='today'?'[data-today-remaining] .food-completion-strip':'.food-remaining')
 await pl.evaluate(e=>e.scrollIntoView({block:'center'}));await al.evaluate(e=>e.scrollIntoView({block:'center'}));await pl.screenshot({path:path.join(dir,`${prefix}-${tab}-prototype.png`)});await al.screenshot({path:path.join(dir,`${prefix}-${tab}-app.png`)})
 const proto=await measure(pl),app=await measure(al);results.modules[tab]={prototype:proto,app};if(before)continue
 assert.equal(app.cells.length,4);assert.equal(app.container.border,'1px');assert.equal(app.container.radius,proto.container.radius);if(width<=430)assert.ok(Math.abs(app.container.width-proto.container.width)<.1);assert.equal(app.container.gap,proto.container.gap);assert.equal(app.grid.gap,proto.grid.gap);assert.equal(app.container.padding,proto.container.padding)
 for(let i=0;i<4;i++){assert.equal(app.cells[i].border,proto.cells[i].border);assert.equal(app.cells[i].radius,proto.cells[i].radius);assert.equal(app.cells[i].padding,proto.cells[i].padding);assert.equal(app.cells[i].background,proto.cells[i].background);assert.equal(app.cells[i].borderColor,proto.cells[i].borderColor);assert.ok(Math.abs(parseFloat(app.values[i].size)-parseFloat(proto.values[i].size))<.001);assert.equal(app.values[i].weight,proto.values[i].weight);assert.ok(Math.abs(parseFloat(app.labels[i].size)-parseFloat(proto.labels[i].size))<.001)}
 if(theme==='light'){assert.equal(app.container.image,proto.container.image);assert.equal(app.container.background,proto.container.background)}else assert.ok(app.container.image.startsWith('linear-gradient(135deg'))
 if(tab==='today'){assert.equal(app.dots.length,4);for(let i=0;i<4;i++){assert.equal(app.dots[i].width,proto.dots[i].width);assert.equal(app.dots[i].background,proto.dots[i].background)}assert.equal(app.buttons.length,1);assert.ok(app.buttons[0].x>=app.heading.right);assert.ok(await al.locator('.goal-compact-top').evaluate(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('button').getBoundingClientRect();return Math.abs((r.top+r.bottom-b.top-b.bottom)/2)<=1}));assert.equal((await al.locator('.remaining-compact-action').innerText()).replace(/\s+/g,' '),'去补齐 ›')}
 else{assert.equal(await al.evaluate(e=>e.parentElement.classList.contains('food-content-body')),true);assert.equal(await a.locator('.food-nutrition-hero .food-remaining').count(),0);assert.equal(app.buttons.length,2);assert.equal(app.buttons[0].width,app.buttons[1].width);assert.equal(app.buttons[0].y,app.buttons[1].y);assert.equal(app.actions.gap,proto.actions.gap);for(const button of app.buttons){assert.equal(button.border,'1px');assert.equal(button.radius,'10px')}}
 assert.ok(app.buttons.every(x=>x.height>=44));assert.equal(await al.evaluate(root=>[root,...root.querySelectorAll('*')].every(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.left>=-.5&&r.right<=innerWidth+.5&&(e.scrollWidth<=e.clientWidth+1||['auto','scroll'].includes(s.overflowX))})),true,prefix+' '+tab+' clipping/overflow')
 }
 if(!before){const data=async()=>a.locator('.remaining-goal').evaluateAll(es=>es.map(e=>e.dataset.gapText));const food=await data();await nav('today');assert.deepEqual(await data(),food)
 // Every independent state remains factual and both original completion paths open without writes.
 for(const [goal,row,text]of [[undefined,log,'未设置目标'],[{...target,calories:log.totalCalories,protein:log.totalProtein,carbs:log.totalCarbs,fat:log.totalFat},log,'已达目标'],[{...target,calories:100},log,'已超'],[target,{...log,totalFat:undefined},'数据不完整']]){await write({nutritionTargets:goal?[goal]:[],foodLogs:[row]});await nav('food');const values=await data();assert.ok(values.some(v=>v.includes(text)));await nav('today');await a.waitForFunction(text=>[...document.querySelectorAll('.remaining-goal')].some(e=>e.dataset.gapText?.includes(text)),text);assert.deepEqual(await data(),values)}
 await write({nutritionTargets:[target],foodLogs:[log]});await nav('food');await nav('today');await a.locator('[data-today-completion]').click();await a.waitForSelector('[data-completion-mode=smart]');await a.locator('dialog[open] [data-close]').click();assert.equal(await a.locator('.food-content-body').getAttribute('data-food-date'),today)
 for(const id of ['food-completion-open','food-completion-custom']){await a.locator('#'+id).click();await a.waitForSelector('[data-completion-mode]');assert.equal(await a.locator(`[data-completion-mode=${id.endsWith('custom')?'designated':'smart'}]`).getAttribute('aria-pressed'),'true');await a.locator('dialog[open] [data-close]').click()}
 assert.equal(await a.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction('foodLogs').objectStore('foodLogs').getAll();q.onsuccess=()=>r(q.result)});d.close();return rows.length}),1);assert.deepEqual(errors,[])}
 receipts.push(results);console.log(prefix+' '+(before?'BEFORE':'PASS'))
 }finally{await c.close()}
}
await b.close();await fs.writeFile(path.join(dir,'comparison.json'),JSON.stringify(receipts,null,2))
