import assert from 'node:assert/strict'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5175/fitlog-lite/'
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
try { const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'}); const page=await context.newPage(); page.setDefaultTimeout(12000); await page.goto(base,{waitUntil:'networkidle'}); await page.waitForSelector('#open-management')
  await page.locator('[data-tab=workout]').click(); await page.waitForSelector('#start-workout'); await page.locator('#start-workout').click(); await page.waitForSelector('#blank-workout'); await page.locator('#blank-workout').click(); await page.waitForSelector('#exit-workout')
  assert.equal(await page.locator('[data-add-journal]').count(),1); assert.equal(await page.locator('#workout-note').isVisible(),false); await page.locator('[data-add-journal]').click(); assert.equal(await page.locator('#workout-note').isVisible(),true); await page.locator('#workout-note').fill('第一行\n第二行 🌱'); await page.locator('[data-add-journal]').click(); assert.equal(await page.locator('#workout-note').isVisible(),false); assert.equal(await page.locator('[data-add-journal]').getAttribute('aria-expanded'),'false'); await page.locator('[data-add-journal]').click(); assert.equal(await page.locator('#workout-note').inputValue(),'第一行\n第二行 🌱'); await page.locator('#exit-workout').click()
  await page.locator('[data-tab=workout]').click(); await page.locator('#add-cardio').click(); await page.waitForSelector('#cardio-form'); assert.equal(await page.locator('[data-add-journal]').count(),1); assert.equal(await page.locator('#cardio-note').isVisible(),false); await page.locator('[data-add-journal]').click(); assert.equal(await page.locator('#cardio-note').isVisible(),true); await page.locator('#cardio-note').fill('保留草稿'); await page.locator('[data-add-journal]').click(); assert.equal(await page.locator('#cardio-note').isVisible(),false); await page.locator('[data-add-journal]').click(); assert.equal(await page.locator('#cardio-note').inputValue(),'保留草稿'); console.log(JSON.stringify({journalProgressive:true,expandCollapse:true,draftPreserved:true,unicodeNewline:true}))
  await context.close()
} finally { await browser.close() }

