// Real UI lifecycle probe; tracks resources without changing domain code or storage semantics.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME}),context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Shanghai',serviceWorkers:'block'})
try{
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-10-10T10:00:00+08:00')})
 await context.addInitScript(()=>{const intervals=new Set(),frames=new Set(),set=window.setInterval.bind(window),clear=window.clearInterval.bind(window),raf=window.requestAnimationFrame.bind(window),cancel=window.cancelAnimationFrame.bind(window);window.setInterval=(fn,ms,...args)=>{const id=set(fn,ms,...args);intervals.add(id);return id};window.clearInterval=id=>{intervals.delete(id);clear(id)};window.requestAnimationFrame=fn=>{const id=raf(t=>{frames.delete(id);fn(t)});frames.add(id);return id};window.cancelAnimationFrame=id=>{frames.delete(id);cancel(id)};window.trainingRecoveryResources=()=>({intervals:intervals.size,frames:frames.size})})
 await page.goto(process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',{waitUntil:'networkidle'});await page.waitForSelector('#open-management');await page.locator('[data-tab=workout]').click();await page.waitForSelector('#start-workout');await page.clock.fastForward(1000)
 const cdp=await context.newCDPSession(page)
 const globalListeners=async()=>{const counts={};for(const name of ['window','document']){const {result}=await cdp.send('Runtime.evaluate',{expression:name});const {listeners}=await cdp.send('DOMDebugger.getEventListeners',{objectId:result.objectId});counts[name]=listeners.length}return counts}
 const before=await globalListeners(),resources=await page.evaluate(()=>trainingRecoveryResources());assert.equal(resources.frames,0)
 for(let i=0;i<20;i++){
  await page.locator('#start-pelvic-floor').click();await page.locator('[data-pelvic-routine=plan-foundation]').click();await page.waitForSelector('#pelvic-finish');await page.clock.fastForward(30000);await page.locator('#pelvic-finish').click();await page.locator('[data-confirm]').click();await page.waitForSelector('[data-completion-status=saved]');await page.clock.fastForward(1000);assert.deepEqual(await page.evaluate(()=>trainingRecoveryResources()),resources,'timer resources released on completion')
  await page.locator('[data-completion-return]').click();await page.waitForSelector('#start-workout');await page.clock.fastForward(1000);assert.deepEqual(await globalListeners(),before,'no global listener accumulation');assert.deepEqual(await page.evaluate(()=>trainingRecoveryResources()),resources)
  assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('sheet-open')||e.classList.contains('immersive')),false)
 }
 // Background writes refresh retained parent lists while editor drafts stay mounted.
 await page.locator('[data-tab=today]').click();await page.waitForSelector('[data-water-add="250"]');await page.locator('[data-water-add="250"]').click();await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-state]')?.textContent==='睡眠记录中');await page.clock.fastForward(3600000);await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-state]')?.textContent==='最近完成睡眠')
 const writer=await context.newPage();await writer.clock.install({time:new Date('2026-10-10T11:00:00+08:00')});await writer.goto(process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',{waitUntil:'networkidle'});await writer.waitForSelector('[data-water-add="250"]')
 await page.locator('[data-water-history]').click();const history=await page.locator('dialog[open]').elementHandle();await page.locator('[data-edit-water]').click();await page.locator('[data-water-form] input').fill('333');await writer.locator('[data-water-add="250"]').click();await page.waitForTimeout(300);assert.equal(await page.locator('[data-water-form] input').inputValue(),'333');await page.locator('[data-history-back]').click();await page.waitForFunction(()=>document.querySelector('[data-water-history-total]')?.textContent==='当日共 500 ml');assert.equal(await history.evaluate(e=>e===document.querySelector('dialog[open]')),true);await page.locator('dialog[open] [data-close]').click()
 await page.locator('[data-sleep-history]').click();const sleepHistory=await page.locator('dialog[open]').elementHandle();await page.locator('[data-edit-sleep]').click();await page.locator('[data-sleep-form] [name=start]').fill('09:59');await writer.locator('[data-sleep-history]').click();await writer.locator('[data-edit-sleep]').click();await writer.locator('[data-sleep-form] [name=end]').fill('10:55');await writer.locator('[data-sleep-form] [type=submit]').click();await writer.waitForSelector('[data-edit-sleep]');await page.waitForTimeout(300);assert.equal(await page.locator('[data-sleep-form] [name=start]').inputValue(),'09:59');await page.locator('[data-history-back]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-history-list]')?.textContent.includes('10:55'));assert.equal(await sleepHistory.evaluate(e=>e===document.querySelector('dialog[open]')),true);await page.locator('dialog[open] [data-close]').click();await writer.close();await page.locator('[data-tab=workout]').click();await page.waitForSelector('#start-workout');await page.clock.fastForward(1000);assert.deepEqual(await globalListeners(),before);assert.deepEqual(await page.evaluate(()=>trainingRecoveryResources()),resources)
 // Delete-last facts disappear from Today, selectable trends, Calendar, Day and Month.
 await page.locator('[data-tab=today]').click();await page.waitForSelector('[data-sleep-history]')
 for(const kind of ['sleep','water']){await page.locator(`[data-${kind}-history]`).click();await page.waitForSelector('[data-history-delete]');while(await page.locator('[data-history-delete]').count()){const count=await page.locator('[data-history-delete]').count();await page.locator('[data-history-delete]').first().click();await page.locator('[data-confirm]').click();await page.waitForFunction(count=>document.querySelectorAll('[data-history-delete]').length===count-1,count)}await page.waitForSelector('.record-history-empty');await page.locator('dialog[open] [data-close]').click()}
 assert.match(await page.locator('.sleep-card').innerText(),/今晚还未记录/);assert.equal(await page.locator('[data-water-total]').innerText(),'0')
 await page.locator('[data-tab=progress]').click();await page.locator('[data-progress-view=trend]').click();await page.locator('#record-weight').click();await page.locator('#weight-sheet-form input').fill('80');await page.locator('#weight-sheet-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.locator('#weight-history-open').click();await page.locator('[data-history-delete]').click();await page.locator('[data-confirm]').click();await page.waitForSelector('.record-history-empty');await page.locator('dialog[open] [data-close]').click();await page.waitForFunction(()=>!document.querySelector('#weight-chart'));assert.equal(await page.locator('.recovery-chart-empty').count(),2)
 await page.locator('[data-progress-view=calendar]').click();const day=page.locator('.calendar-day[data-date="2026-10-10"]');for(const kind of ['sleep','water','weight'])assert.equal(await day.locator(`.calendar-marker.calendar-category-${kind}`).count(),0);await day.click();for(const kind of ['sleep','water','weight'])assert.match(await page.locator(`[data-record-category=${kind}] summary`).innerText(),/未记录/);await page.locator('dialog[open] [data-close]').click()
 await page.locator('[data-progress-view=reports]').click();await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-date]');for(const kind of ['sleep','water','weight'])assert.match(await page.locator(`[data-record-category=${kind}] summary`).innerText(),/未记录/);await page.locator('[data-report-mode=month]').click();await page.waitForSelector('.recovery-report');for(const label of ['有睡眠记录天数','有饮水记录天数'])assert.equal(await page.locator('.recovery-statistics div').filter({hasText:label}).locator('dd').innerText(),'0 天')
 // Compare settled states after the legitimate saved-weight Toast has disposed its five owned listeners.
 await page.locator('[data-tab=workout]').click();await page.waitForSelector('#start-workout');await page.clock.fastForward(6000);await page.waitForSelector('.action-toast',{state:'detached'});assert.deepEqual(await globalListeners(),before);assert.deepEqual(await page.evaluate(()=>trainingRecoveryResources()),resources)
 const saved=await page.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction('pelvicFloorSessions').objectStore('pelvicFloorSessions').getAll();q.onsuccess=()=>r(q.result)});d.close();return rows});assert.equal(saved.length,20);assert.equal(new Set(saved.map(s=>s.id)).size,20);assert.ok(saved.every(s=>s.completionType==='manual'));assert.deepEqual(errors,[])
 const receipt={cycles:20,globalListeners:before,resources,deleteLastAcrossTodayTrendCalendarDayMonth:true,sameSheetBackgroundWritesPreserveDrafts:true,stableListenerCounts:true,noTimerResidue:true,exactly20DistinctManualSessions:true,noOrphanSheetOrLocks:true,physicalIPhone:'Pending'}
 const dir=path.resolve('../../artifacts/training-recovery-2026-10-09',process.env.FITLOG_QA_URL?.includes('github.io')?'prod':'local');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'lifecycle-receipt.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt))
}finally{await context.close();await browser.close()}
