// Actual UI/service flows in isolated synthetic Chromium contexts. Physical iPhone remains Pending.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',mode=base.includes('github.io')?'prod':'local',dir=path.resolve('../../artifacts/training-recovery-2026-10-09',mode),receipts=[]
await fs.mkdir(dir,{recursive:true})
const fixture=JSON.parse(await fs.readFile(new URL('../fixtures/legacyV11Data.json',import.meta.url)))
const full=[...[320,375,390,430].flatMap(w=>[100,120,140,200].flatMap(s=>['light','dark'].flatMap(c=>[false,true].map(r=>[w,w===430?932:w===390?844:812,s,c,r])))),[844,390,140,'dark',true]]
const matrix=process.env.FITLOG_TRAINING_SMOKE?[[390,844,100,'light',false],[320,812,200,'dark',true]]:mode==='prod'?[[390,844,100,'light',false],[320,812,200,'dark',true],[430,932,140,'dark',true],[844,390,140,'dark',true]]:full
const cases=process.env.FITLOG_TRAINING_WIDTH?matrix.filter(([w])=>w===Number(process.env.FITLOG_TRAINING_WIDTH)):matrix
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
const date='2026-10-10',night='2026-10-09',stamp='2026-10-10T01:00:00Z',shift=(n,from=date)=>{const d=new Date(from+'T12:00:00');d.setDate(d.getDate()+n);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const read=(page,name)=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return rows},name)
const write=(page,data)=>page.evaluate(async data=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
try{for(const [width,height,scale,colorScheme,reduced]of cases){
 const context=await browser.newContext({viewport:{width,height},colorScheme,reducedMotion:reduced?'reduce':'no-preference',timezoneId:'Asia/Shanghai',isMobile:true,hasTouch:true,serviceWorkers:'block'})
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000)
 const representative=width===390&&scale===100&&colorScheme==='light'&&!reduced
 const prefix=`${width}-${scale}-${colorScheme}-${reduced?'reduced':'normal'}`
 try{
 await page.clock.install({time:new Date('2026-10-10T10:00:00+08:00')});await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management')
 const css=`html{font-size:${scale}%}`;await page.addStyleTag({content:css})
 const close=async()=>{if(await page.locator('dialog[open]').count())await page.locator('dialog[open] .modal-head [data-close]').last().click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))}
 const nav=async tab=>{await close();await page.locator(`[data-tab=${tab}]`).click();await page.waitForSelector(tab==='today'?'.sleep-card':tab==='workout'?'#start-workout':'[data-progress-view]')}
 const progress=async view=>{await nav('progress');await page.locator(`[data-progress-view=${view}]`).click();await page.waitForSelector(view==='trend'?'#weight-history-open':view==='calendar'?'.calendar-grid':'.report-mode')}
 const shot=async(name,selector)=>{if(representative||([320,430,844].includes(width)&&[140,200].includes(scale)&&reduced))await(selector?page.locator(selector):page).screenshot({path:path.join(dir,prefix+'-'+name+'.png'),...(selector?{}:{fullPage:true})})}
 const audit=async(selector)=>{await page.locator(selector).evaluate(e=>Promise.allSettled(e.getAnimations({subtree:true}).filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished)));const bad=await page.locator(selector).evaluate(root=>{const bad=[];if(document.documentElement.scrollWidth>innerWidth+1)bad.push('body overflow');for(const e of root.querySelectorAll('*')){if(!e.getClientRects().length||e instanceof SVGElement||e.closest('.recovery-chart-scroll,.weight-chart-scroll'))continue;const r=e.getBoundingClientRect();if(!r.width||!r.height)continue;if(r.left<-.6||r.right>innerWidth+.6)bad.push('bounds '+e.className);if(e.matches('button,input,select')&&r.height<43.5)bad.push('target '+e.className);if(e.matches('button,.completion-summary dd,.record-history-main strong,.chart-selection > *')&&e.scrollWidth>e.clientWidth+1)bad.push('clip '+e.className)}return [...new Set(bad)]});assert.deepEqual(bad,[],`${prefix}/${selector}`)}
 const sleep={id:'actual-night',startTime:'2026-10-10T02:00:00+08:00',endTime:'2026-10-10T09:00:00+08:00',durationMinutes:420,recordDate:date,createdAt:stamp,updatedAt:stamp}
 const data=structuredClone(fixture);for(const rows of Object.values(data))for(const row of rows)if(row.date)row.date=night
 data.nutritionTargets=data.nutritionTargets.slice(0,1);data.sleepSessions=[sleep];data.waterLogs=[{id:'drink',date,amountMl:250,timestamp:stamp,createdAt:stamp,updatedAt:stamp}];data.weights=[{id:'weight',date,weightKg:80,createdAt:stamp,updatedAt:stamp}];data.pelvicFloorSessions=[]
 await write(page,data);await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await page.waitForSelector('.sleep-card');assert.match(await page.locator('.sleep-card').innerText(),/10月9日晚/)
 const startKegel=async()=>{await nav('workout');await page.locator('#start-pelvic-floor').click();await page.locator('[data-pelvic-routine=plan-foundation]').click();await page.waitForSelector('#pelvic-finish')}
 const manualKegel=async()=>{await startKegel();await page.clock.fastForward(30000);await page.locator('#pelvic-finish').click();await page.locator('[data-confirm]').click();await page.waitForSelector('[data-completion-status=saved]')}
 await manualKegel();assert.match(await page.locator('.training-completion').innerText(),/本次训练已结束/);assert.equal(await page.locator('#start-workout').count(),0);let sessions=await read(page,'pelvicFloorSessions');assert.equal(sessions.length,1);assert.equal(sessions[0].completionType,'manual');assert.equal(await page.locator('.completion-notice').count(),0);await audit('.training-completion');await shot('kegel-manual','.training-completion');await page.locator('[data-completion-return]').click();await page.waitForSelector('#start-workout');assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('immersive')),false)
 if(representative){
  await startKegel();await page.locator('#pelvic-pause').click();const paused=await page.locator('#pelvic-remaining').innerText();await page.clock.fastForward(60000);assert.equal(await page.locator('#pelvic-remaining').innerText(),paused);await page.locator('#pelvic-pause').click();await page.clock.fastForward(20*60000);await page.waitForSelector('[data-completion-status=saved]');sessions=await read(page,'pelvicFloorSessions');const natural=sessions.find(s=>s.completionType==='completed');assert.ok(natural);assert.equal(natural.completedRepetitions,natural.repetitions);assert.match(await page.locator('.completion-summary').innerText(),new RegExp(`${natural.completedRepetitions} / ${natural.repetitions}`));await shot('kegel-natural','.training-completion');await page.clock.fastForward(60000);assert.equal((await read(page,'pelvicFloorSessions')).length,2);await page.locator('[data-completion-return]').click()
  // Six actual distinct prior training dates unlock standard on the next natural completion only.
  await write(page,{pelvicFloorSessions:Array.from({length:6},(_,i)=>({...natural,id:'prior-'+i,date:shift(-i-1),startedAt:shift(-i-1)+'T01:00:00Z',finishedAt:shift(-i-1)+'T01:10:00Z'}))});await startKegel();await page.clock.fastForward(20*60000);await page.waitForSelector('.completion-notice');assert.match(await page.locator('.completion-notice').innerText(),/下一阶段已解锁/);assert.equal(await page.locator('dialog[open]').count(),0);await shot('kegel-unlock','.training-completion');await page.locator('[data-completion-return]').click()
  await startKegel();await page.evaluate(()=>{window.originalAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(row,...args){if(this.name==='pelvicFloorSessions'){window.failedPelvic=structuredClone(row);throw new DOMException('合成保存失败','UnknownError')}return originalAdd.call(this,row,...args)}});await page.clock.fastForward(20*60000);await page.waitForSelector('[data-completion-status=error]');assert.match(await page.locator('.training-completion').innerText(),/记录尚未成功保存/);const failed=await page.evaluate(()=>failedPelvic),before=(await read(page,'pelvicFloorSessions')).length;await shot('kegel-error','.training-completion');await page.evaluate(()=>IDBObjectStore.prototype.add=originalAdd);await page.locator('[data-completion-retry]').dblclick();await page.waitForSelector('[data-completion-status=saved]');sessions=await read(page,'pelvicFloorSessions');assert.equal(sessions.length,before+1);assert.deepEqual(sessions.find(s=>s.id===failed.id),failed);await page.locator('[data-completion-return]').click()
 }
 // Strength real creation, actual saved sets, optional load remains unknown.
 await nav('workout');await page.locator('#start-workout').click();await page.locator('#blank-workout').click();await page.locator('#add-exercise').click();await page.locator('[data-exercise]').first().click();await page.locator('[data-add-set]').click();await page.locator('[data-field=reps]').fill('8');await page.locator('[data-add-journal]').click();await page.locator('#workout-note').fill('真实训练日志\n保留未填写重量')
 if(representative)await page.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(row,...args){if(this.name==='workouts'&&row.finishedAt)throw new DOMException('合成力量保存失败','UnknownError');return originalPut.call(this,row,...args)}})
 await page.locator('#finish-workout').click();await page.locator('[data-confirm]').click();await page.waitForSelector('[data-training-completion=strength]');if(representative){await page.waitForSelector('[data-completion-status=error]');await page.evaluate(()=>IDBObjectStore.prototype.put=originalPut);await page.locator('[data-completion-retry]').click()}
 await page.waitForSelector('[data-completion-status=saved]');assert.match(await page.locator('.completion-summary').innerText(),/1 个动作/);assert.match(await page.locator('.completion-summary').innerText(),/1 组/);assert.equal(await page.locator('.history-list').count(),0);await audit('.training-completion');await shot('strength-complete','.training-completion');const strength=(await read(page,'workouts')).find(w=>w.date===date);assert.equal(strength.exercises[0].sets[0].weightKg,undefined);assert.equal(strength.note,'真实训练日志\n保留未填写重量');await page.locator('[data-completion-view]').click();assert.match(await page.locator('.completion-record').innerText(),/8 次/);assert.doesNotMatch(await page.locator('.completion-record').innerText(),/0kg/);await page.locator('[data-completion-record-back]').click();await page.locator('[data-completion-return]').click()
 // Cardio remains light, same Sheet draft on failure and single write under repeated submit.
 await page.locator('#add-cardio').click();const cardioDialog=await page.locator('dialog[open]').elementHandle();await page.locator('[name=duration]').fill('25');await page.locator('[name=speed]').fill('6.5');const cardioBefore=(await read(page,'cardioSessions')).length
 if(representative){await page.evaluate(()=>{window.originalCardioAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...a){if(this.name==='cardioSessions')throw new DOMException('合成有氧保存失败','UnknownError');return originalCardioAdd.apply(this,a)}});await page.locator('#cardio-form [type=submit]').click();await page.locator('[data-cardio-error]:not([hidden])').waitFor();assert.equal(await cardioDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);assert.equal(await page.locator('[name=duration]').inputValue(),'25');await page.evaluate(()=>IDBObjectStore.prototype.add=originalCardioAdd)}
 await page.locator('#cardio-form').evaluate(form=>{form.requestSubmit();form.requestSubmit()});await page.waitForFunction(()=>!document.querySelector('#cardio-form'));await page.waitForFunction(()=>document.querySelector('#add-cardio')?.textContent==='再记一次');assert.equal((await read(page,'cardioSessions')).length,cardioBefore+1);assert.equal(await page.locator('.training-completion').count(),0);await shot('cardio-saved');await page.locator('#cardio-history').click();const historyCardio=await page.locator('dialog[open]').elementHandle();await page.locator('[data-history-cardio]').first().click();assert.equal(await historyCardio.evaluate(e=>e===document.querySelector('dialog[open]')),true);await page.locator('[name=duration]').fill('30');await page.locator('#cardio-form [type=submit]').click();await page.waitForSelector('[data-history-cardio]');await page.locator('[data-history-cardio]').first().click();await page.locator('#delete-cardio').click();await page.locator('[data-confirm]').click();await page.waitForSelector('[data-history-cardio]');assert.equal(await historyCardio.evaluate(e=>e===document.querySelector('dialog[open]')),true);await close()
 // Nearby Weight history, one/many/empty, exact identity, original Sheet and live summary.
 await page.clock.fastForward(6000)
 await progress('trend');assert.equal(await page.locator('.weight-list').count(),0);assert.equal(await page.locator('.weight-hero #weight-history-open').count(),1);await audit('[data-weight-module]');await shot('weight-top','[data-weight-module]');await page.locator('#weight-history-open').click();await page.waitForSelector('[data-edit-weight]');await audit('dialog[open]');await shot('weight-history-one','dialog[open]');const weightDialog=await page.locator('dialog[open]').elementHandle();await page.locator('[data-edit-weight]').click();await page.locator('[data-weight-history-form] input').fill('81');await page.locator('[data-weight-history-form] [type=submit]').click();await page.waitForSelector('[data-edit-weight]');assert.equal(await weightDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);assert.equal((await read(page,'weights'))[0].id,'weight');await page.locator('[data-history-delete]').click();await page.locator('[data-confirm]').click();await page.waitForSelector('.record-history-empty');assert.equal(await weightDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);await audit('dialog[open]');await close();await page.waitForFunction(()=>!document.querySelector('#weight-chart'));assert.match(await page.locator('[data-weight-module]').innerText(),/还没有|暂无/)
 const manyWeights=Array.from({length:35},(_,i)=>({id:'weight-'+i,date:shift(-i),weightKg:80+i/10,createdAt:stamp,updatedAt:stamp}));await write(page,{weights:manyWeights});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await progress('trend');await page.locator('#weight-history-open').click();await page.waitForSelector('[data-history-id]');await shot('weight-history-many','dialog[open]');const weightMany=await page.locator('dialog[open]').elementHandle();await page.locator('[data-history-delete]').first().click();await page.locator('[data-confirm]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-history-id]').length===34);assert.equal(await weightMany.evaluate(e=>e===document.querySelector('dialog[open]')),true);await shot('weight-after-delete','dialog[open]');await close();await page.waitForFunction(()=>document.querySelector('.hero-number strong')?.textContent==='80.1')
 await page.locator('#weight-chart').focus();await page.keyboard.press('Home');assert.equal(await page.locator('[data-weight-chart-date]').innerText(),shift(-29));await page.keyboard.press('End');assert.equal(await page.locator('[data-weight-chart-date]').innerText(),shift(-1))
 // Shared content-sized Water and Sleep histories with same-native-Sheet Back/date/edit.
 await nav('today');await page.locator('[data-water-history]').click();await page.waitForSelector('[data-edit-water]');await audit('dialog[open]');await shot('water-history-one','dialog[open]');if(scale===100&&height>400)assert.ok((await page.locator('dialog[open]').boundingBox()).height<height*.6);const waterDialog=await page.locator('dialog[open]').elementHandle();await page.locator('[data-edit-water]').click();await page.locator('[data-water-form] input').fill('400');await page.locator('[data-water-form] [type=submit]').click();await page.waitForSelector('[data-edit-water]');assert.equal(await waterDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);assert.match(await page.locator('[data-water-history-total]').innerText(),/400 ml/);await page.locator('[data-water-date]').click();await page.locator('[data-history-back]').click();assert.equal(await waterDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);await page.locator('[data-history-delete]').click();await page.locator('[data-confirm]').click();await page.waitForSelector('.record-history-empty');await shot('water-history-empty','dialog[open]');await close()
 const waters=Array.from({length:30},(_,i)=>({id:'drink-'+i,date,amountMl:250,timestamp:new Date(Date.parse(stamp)-i*60000).toISOString(),createdAt:stamp,updatedAt:stamp}));await write(page,{waterLogs:waters});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await page.locator('[data-water-history]').click();await page.waitForSelector('[data-edit-water]');await shot('water-history-many','dialog[open]');await close();await page.locator('[data-sleep-history]').click();await page.waitForSelector('[data-edit-sleep]');await audit('dialog[open]');await shot('sleep-history','dialog[open]');await page.locator('[data-view-sleep]').click();await page.waitForSelector('[data-sleep-interval]');await shot('sleep-timeline-one','dialog[open]');await page.locator('[data-history-back]').click();const sleepDialog=await page.locator('dialog[open]').elementHandle();await page.locator('[data-edit-sleep]').click();await page.locator('[data-sleep-night]').selectOption(date);await page.locator('[data-sleep-form] [type=submit]').click();await page.waitForSelector('[data-edit-sleep]');assert.equal(await sleepDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);let saved=(await read(page,'sleepSessions'))[0];assert.equal(saved.sleepNightDate,date);assert.equal(saved.startTime,sleep.startTime);assert.equal(saved.recordDate,date);await page.locator('[data-edit-sleep]').click();await page.locator('[data-sleep-night]').selectOption(night);await page.locator('[data-sleep-form] [type=submit]').click();await page.waitForSelector('[data-edit-sleep]');saved=(await read(page,'sleepSessions'))[0];await page.locator('[data-history-delete]').click();await page.locator('[data-confirm]').click();await page.waitForSelector('.record-history-empty');assert.equal(await sleepDialog.evaluate(e=>e===document.querySelector('dialog[open]')),true);await audit('dialog[open]');await close();assert.match(await page.locator('.sleep-card').innerText(),/今晚还未记录/);await write(page,{sleepSessions:[saved]})
 saved=(await read(page,'sleepSessions'))[0];const second={...saved,id:'actual-second',startTime:'2026-10-10T09:30:00+08:00',endTime:'2026-10-10T10:00:00+08:00',durationMinutes:30};await write(page,{sleepSessions:[saved,second]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await page.locator('[data-sleep-history]').click();await page.locator('[data-view-sleep]').first().click();await page.waitForFunction(()=>document.querySelectorAll('[data-sleep-interval]').length===2);await audit('dialog[open]');await shot('sleep-timeline-multiple','dialog[open]');await close()
 // Ranges/selected values, gaps, keyboard and touch; same-range live update retains selection.
 const moreSleeps=Array.from({length:90},(_,i)=>({...saved,id:'range-'+i,startTime:shift(-i-1)+'T02:00:00+08:00',endTime:shift(-i-1)+'T09:00:00+08:00',sleepNightDate:shift(-i-2),sleepNightDateSource:'auto',sleepStartLocalDate:shift(-i-1),recordDate:shift(-i-1)})).filter((_,i)=>i!==4)
 await write(page,{sleepSessions:[saved,second,...moreSleeps],waterLogs:[...waters,...Array.from({length:89},(_,i)=>({id:'past-water-'+i,date:shift(-i-1),amountMl:500+i,timestamp:stamp,createdAt:stamp,updatedAt:stamp})).filter((_,i)=>i!==4)]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await progress('trend')
 for(const days of [7,30,90]){await page.locator(`[data-recovery-days="${days}"]`).click();await page.waitForFunction(days=>document.querySelectorAll('[data-chart-kind=sleep] [data-point-date]').length===days,days);for(const kind of ['sleep','water']){const chart=page.locator(`[data-recovery-chart=${kind}]`);assert.equal(await chart.locator('.recovery-point-value').count(),0);assert.equal(await page.locator('.recovery-daily').count(),0);const actual=chart.locator('[data-point-value]');await actual.first().focus();await page.keyboard.press('Enter');assert.equal(await chart.locator('[aria-pressed=true]').getAttribute('data-point-date'),await actual.first().getAttribute('data-point-date'));await page.keyboard.press('End');await chart.locator('[aria-pressed=true] .recovery-line-hit').tap();assert.match(await chart.locator('[data-chart-date]').innerText(),/2026年/);await shot(`${kind}-trend-${days}`,`[data-recovery-chart=${kind}]`)}await audit('.recovery-trend')}
 await shot('trend-selection','.recovery-trend');const selectedDate=await page.locator('[data-recovery-chart=water] [aria-pressed=true]').getAttribute('data-point-date');await page.locator('[data-recovery-chart=water] [aria-pressed=true]').focus();const writer=await context.newPage();await writer.clock.install({time:new Date('2026-10-10T10:00:00+08:00')});await writer.goto(base,{waitUntil:'networkidle'});await writer.waitForSelector('[data-water-add=\"250\"]');await writer.locator('[data-water-add=\"250\"]').click();await page.waitForFunction(()=>document.querySelector('[data-recovery-chart=water] [data-chart-value]')?.textContent==='7750 ml');await writer.close();assert.equal(await page.locator('[data-recovery-chart=water] [aria-pressed=true]').getAttribute('data-point-date'),selectedDate);assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('data-point-date')),selectedDate)
 // Nine categories, complete true timeline, day/month report shared facts.
 await write(page,{waterLogs:[...await read(page,'waterLogs'),{id:'night-water',date:night,amountMl:350,timestamp:stamp,createdAt:stamp,updatedAt:stamp}],weights:[...await read(page,'weights').then(rows=>rows.filter(w=>w.date!==night)),{id:'night-weight',date:night,weightKg:82,createdAt:stamp,updatedAt:stamp}],pelvicFloorSessions:[{...fixture.pelvicFloorSessions[0],date:night}]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:css});await progress('calendar');const day=page.locator(`.calendar-day[data-date="${night}"]`);assert.equal(await day.locator('.calendar-marker').count(),9);await shot('calendar-nine-sleep','.month-calendar');await day.click();await page.locator('[data-record-category=sleep] summary').click();assert.equal(await page.locator('[data-sleep-interval]').count(),2);assert.match(await page.locator('[data-record-category=sleep]').innerText(),/7小时30分钟/);await audit('dialog[open]');await shot('day-detail','dialog[open]');await close();await progress('reports');await page.locator('[data-report-mode=day]').click();await page.locator('#report-previous').click();await page.waitForSelector(`[data-record-date="${night}"]`);assert.match(await page.locator('[data-record-category=sleep] summary').innerText(),/7小时30分钟/);await shot('day-report','.report-page');await page.locator('[data-report-mode=month]').click();await page.waitForSelector('.recovery-report');await audit('#view');await shot('month-report','.report-page')
 if(representative){
  // 20 integrated real UI cycles. Same record identity for corrections, one new manual session per cycle.
  const count=(await read(page,'pelvicFloorSessions')).length
  for(let i=0;i<20;i++){
   await manualKegel();await page.locator('[data-completion-return]').click();assert.equal((await read(page,'pelvicFloorSessions')).length,count+i+1)
   await progress('trend');await page.locator('#weight-history-open').click();await page.locator('[data-edit-weight]').first().click();await page.locator('[data-weight-history-form] input').fill(String(82+i/10));await page.locator('[data-weight-history-form] [type=submit]').click();await page.waitForSelector('[data-edit-weight]');await close()
   await page.locator('[data-water-history]').click();await page.locator('[data-edit-water]').first().click();await page.locator('[data-water-form] input').fill(String(251+i));await page.locator('[data-water-form] [type=submit]').click();await page.waitForSelector('[data-edit-water]');await close()
   await page.locator('[data-sleep-history]').click();await page.locator('[data-edit-sleep="actual-night"]').click();await page.locator('[data-sleep-night]').selectOption(i%2?night:date);await page.locator('[data-sleep-form] [type=submit]').click();await page.waitForSelector('[data-edit-sleep]');await close()
   for(const n of [7,30,90]){await page.locator(`[data-recovery-days="${n}"]`).click();await page.waitForFunction(n=>document.querySelectorAll('[data-chart-kind=sleep] [data-point-date]').length===n,n);await page.locator('[data-recovery-chart=sleep] [data-point-value]').first().focus();await page.keyboard.press('Enter');await page.keyboard.press('End')}
   await progress('calendar');await page.locator(`.calendar-day[data-date="${i%2?night:date}"]`).click();await page.locator('[data-record-category=sleep] summary').click();assert.ok(await page.locator('[data-sleep-interval]').count());await close();await progress('reports');for(const m of ['day','month']){await page.locator(`[data-report-mode=${m}]`).click();await page.waitForSelector(m==='day'?'[data-record-date]':'.recovery-report')}
   assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('sheet-open')),false);await audit('#view')
  }
 }
 assert.deepEqual(errors,[]);const receipt={width,height,scale,colorScheme,reduced,kegelManual:true,naturalPauseUnlockFailureRetry:representative,strengthSavedActual:true,cardioDraftSingleWrite:true,sharedHistoryIdentity:true,weightNearby:true,sleepNightSharedFacts:true,trueIntervals:true,selected7_30_90:true,keyboardTouch:true,liveSelection:true,stressCycles:representative?20:0,noOverflow:true,physicalIPhone:'Pending'};receipts.push(receipt);console.log(JSON.stringify(receipt))
 }catch(error){await page.screenshot({path:path.join(dir,prefix+'-failure.png'),fullPage:true}).catch(()=>{});console.log('FAILURE_STATE',await page.locator('body').innerText());throw error}finally{await context.close()}
}await fs.writeFile(path.join(dir,`receipt${process.env.FITLOG_TRAINING_WIDTH?'-'+process.env.FITLOG_TRAINING_WIDTH:''}.json`),JSON.stringify(receipts,null,2))}finally{await browser.close()}
