// Visible results and real screen-coordinate touch in isolated invented-data contexts.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE),base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5184/fitlog-lite/',mode=base.includes('github.io')?'prod':'local',dir=path.resolve('../../artifacts/coach-report-v3-1-2026-10-09/retained-unified',mode)
await fs.mkdir(dir,{recursive:true});const fixture=JSON.parse(await fs.readFile(new URL('../fixtures/legacyV11Data.json',import.meta.url))),receipts=[]
const matrix=[...[320,375,390,430].flatMap(w=>[100,120,140,200].flatMap(s=>['light','dark'].flatMap(c=>[false,true].map(r=>[w,w===430?932:w===390?844:812,s,c,r])))),[844,390,140,'dark',true]]
const cases=(process.env.FITLOG_UNIFIED_SMOKE?[[390,844,100,'light',false],[320,812,200,'dark',true]]:mode==='prod'?[[390,844,100,'light',false],[320,812,200,'dark',true],[430,932,140,'dark',true],[844,390,140,'dark',true]]:matrix).filter(([w])=>!process.env.FITLOG_UNIFIED_WIDTH||w===Number(process.env.FITLOG_UNIFIED_WIDTH))
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME}),today='2026-10-10',stamp='2026-10-10T01:00:00Z'
const read=(page,name)=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)}),rows=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return rows},name)
const write=(page,data)=>page.evaluate(async data=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
const sleep=(id,date)=>({id,startTime:date+'T02:00:00+08:00',endTime:date+'T09:00:00+08:00',durationMinutes:420,recordDate:date,createdAt:stamp,updatedAt:stamp})
const water=(id,date,amountMl)=>({id,date,amountMl,timestamp:date+'T01:00:00Z',createdAt:stamp,updatedAt:stamp})
const weight=(id,date,weightKg)=>({id,date,weightKg,createdAt:stamp,updatedAt:stamp})
try{for(const[width,height,scale,colorScheme,reduced]of cases){
 const context=await browser.newContext({viewport:{width,height},colorScheme,reducedMotion:reduced?'reduce':'no-preference',timezoneId:'Asia/Shanghai',isMobile:true,hasTouch:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[],prefix=`${width}-${scale}-${colorScheme}-${reduced?'reduced':'normal'}`,representative=width===390&&scale===100&&colorScheme==='light'&&!reduced
 page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message))
 try{
 await page.clock.install({time:new Date('2026-10-10T10:00:00+08:00')})
 await context.addInitScript(()=>{const timeouts=new Set(),later=setTimeout.bind(window),cancelLater=clearTimeout.bind(window);window.setTimeout=(fn,ms,...args)=>{const id=later((...values)=>{timeouts.delete(id);fn(...values)},ms,...args);timeouts.add(id);return id};window.clearTimeout=id=>{timeouts.delete(id);cancelLater(id)};const intervals=new Set(),frames=new Set(),set=setInterval.bind(window),clear=clearInterval.bind(window),raf=requestAnimationFrame.bind(window),cancel=cancelAnimationFrame.bind(window);window.setInterval=(fn,ms,...a)=>{const id=set(fn,ms,...a);intervals.add(id);return id};window.clearInterval=id=>{intervals.delete(id);clear(id)};window.requestAnimationFrame=fn=>{const id=raf(t=>{frames.delete(id);fn(t)});frames.add(id);return id};window.cancelAnimationFrame=id=>{frames.delete(id);cancel(id)};window.unifiedResources=()=>({timeouts:timeouts.size,intervals:intervals.size,frames:frames.size})})
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management')
 const data=structuredClone(fixture);for(const rows of Object.values(data))for(const row of rows)if(row.date)row.date=today;data.nutritionTargets=data.nutritionTargets.slice(0,1);data.weights=[weight('w8','2026-10-08',86.6),weight('w9','2026-10-09',85.7),weight('old','2025-10-09',88.8)];data.sleepSessions=[sleep('s8','2026-10-09'),sleep('s9','2026-10-10')];data.waterLogs=[water('d8','2026-10-08',1000),water('d91','2026-10-09',250),water('d92','2026-10-09',500),water('d93','2026-10-09',500)]
 await write(page,data);await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`});await page.waitForSelector('.sleep-card')
 const module=k=>page.locator(`[data-trend-module=${k}]`),close=async()=>{if(await page.locator('dialog[open]').count())await page.locator('dialog[open] [data-close]').last().click();await page.waitForFunction(()=>!document.querySelector('dialog'));await page.clock.runFor(32)}
 const nav=async tab=>{await close();await page.locator(`[data-tab=${tab}]`).click();await page.waitForSelector(tab==='today'?'.sleep-card':tab==='workout'?'#start-workout':tab==='food'?'#food-date-picker-open':tab==='plan'?'.plan-page':'[data-progress-view]')}
 const trend=async()=>{await nav('progress');await page.locator('[data-progress-view=trend]').click();await page.waitForFunction(()=>document.querySelectorAll('.trend-module .trend-ranges').length===3)}
 const replaceFacts=async(data)=>{await write(page,data);await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`});await trend()}
 const shot=async(name,selector)=>{await settle(selector||'#view');if(representative||['trend-full','today-full','training-full','report-full','report-dark'].includes(name)||([320,430,844].includes(width)&&scale===200&&reduced))await(selector?page.locator(selector):page).screenshot({path:path.join(dir,prefix+'-'+name+'.png'),animations:'disabled',...(selector?{}:{fullPage:true})})}
 const settle=async(selector='#view')=>{await page.locator(selector).evaluate(e=>Promise.allSettled(e.getAnimations({subtree:true}).filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished)))}
 const audit=async selector=>{await settle(selector);const bad=await page.locator(selector).evaluate(root=>{const bad=[];if(document.documentElement.scrollWidth>innerWidth+1)bad.push('page overflow');for(const e of root.querySelectorAll('*')){if(e instanceof SVGElement||!e.getClientRects().length||e.closest('.trend-chart-shell,.food-date-rail'))continue;const r=e.getBoundingClientRect();if(!r.width||!r.height)continue;if(r.left<-.6||r.right>innerWidth+.6)bad.push('bounds '+e.className+' '+JSON.stringify({left:r.left,right:r.right,width:innerWidth}));if(e.matches('button,input,select,summary')&&(r.height<43.5||r.width<43.5))bad.push('target '+e.className);if(e.matches('button,.chart-selection>*')&&e.scrollWidth>e.clientWidth+1)bad.push('clip '+e.className)}return [...new Set(bad)]});assert.deepEqual(bad,[],`${prefix}/${selector}`)}
 const range=async(k,n)=>{await module(k).locator(k==='weight'?`[data-range="${n}"]`:`[data-recovery-days="${n}"]`).click();await page.waitForFunction(([k,n])=>document.querySelector(`[data-trend-module=${k}] .trend-ranges [aria-pressed=true]`)?.textContent===n+'天',[k,n])}
 const state=async()=>Promise.all(['weight','sleep','water'].map(k=>module(k).locator('.trend-ranges [aria-pressed=true]').innerText()))
 const checkValue=async(k,value,date)=>{const m=module(k);assert.match(await m.locator('.chart-selection strong').textContent(),new RegExp(value));assert.match(await m.locator('.chart-selection>span').textContent(),new RegExp(`10月${date}日`))}
 // Find the actual rendered canvas ink, never call the selection function or mutate its state.
 const touchWeight=async(first=true)=>{const canvas=page.locator('#weight-chart');await canvas.scrollIntoViewIfNeeded();await canvas.evaluate((c,first)=>{const p=c.dataset.weightPositions.split(',').map(Number),s=parseFloat(getComputedStyle(document.documentElement).fontSize)/16,region=c.closest('.trend-chart-shell');region.scrollLeft=(first?p[0]:p.at(-1))*s-region.clientWidth/2},first);await page.waitForFunction(()=>{const c=document.querySelector('#weight-chart');return Math.abs(Number(c.dataset.windowScroll)-c.closest('.trend-chart-shell').scrollLeft)<1});const xy=await canvas.evaluate((c,first)=>{const ctx=c.getContext('2d'),rgba=ctx.getImageData(0,0,c.width,c.height).data,tmp=document.createElement('canvas').getContext('2d');tmp.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--weight').trim();tmp.fillRect(0,0,1,1);const color=tmp.getImageData(0,0,1,1).data;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4;if(Math.abs(rgba[i]-color[0])<4&&Math.abs(rgba[i+1]-color[1])<4&&Math.abs(rgba[i+2]-color[2])<4&&rgba[i+3]>200){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}if(!Number.isFinite(minX))throw Error('No painted weight data ink');const r=c.getBoundingClientRect(),s=parseFloat(getComputedStyle(document.documentElement).fontSize)/16,target=(first?minX+3*s:maxX-3*s)*r.width/c.width;return{x:r.left+target,y:r.top+(minY+maxY)/2*r.height/c.height}},first);await page.touchscreen.tap(xy.x,xy.y)}

 const touchSvg=async(k,date,offset=18)=>{const point=module(k).locator(`[data-point-date="2026-10-${date}"][data-point-value]`);await point.scrollIntoViewIfNeeded();const xy=await point.evaluate((p,offset)=>{const circle=p.querySelector('.recovery-line-marker'),svg=p.closest('svg'),v=new DOMPoint(Number(circle.getAttribute('cx')),Number(circle.getAttribute('cy'))).matrixTransform(svg.getScreenCTM());return{x:v.x+offset,y:v.y+10}},offset);await page.touchscreen.tap(xy.x,xy.y)}
 await trend();assert.deepEqual(await state(),['30天','30天','30天']);assert.equal(await page.locator('.trend-module').count(),3);assert.equal(await page.locator('.weight-hero,.trend-domain-heading').count(),0);assert.equal(await page.locator('.recovery-trend h3').count(),0)
 const dimensions=await page.locator('.trend-module').evaluateAll(nodes=>nodes.map(e=>{const css=x=>getComputedStyle(e.querySelector(x)).fontSize;return{title:css('h2'),number:css('.chart-selection>strong'),date:css('.chart-selection>span'),icon:e.querySelector('.module-icon').getBoundingClientRect().width}}));assert.deepEqual(dimensions[0],dimensions[1]);assert.deepEqual(dimensions[1],dimensions[2]);assert.equal(await page.locator('[data-weight-chart-value]').count(),1)
 await audit('#view');await shot('trend-full');for(const n of [7,30,90]){await range('weight',n);await shot('weight-'+n,'[data-trend-module=weight]')}await range('weight',7);await shot('weight-two','[data-trend-module=weight]');const paintedBefore=await page.locator('#weight-chart').evaluate(c=>c.toDataURL());await touchWeight(true);await checkValue('weight','86.6',8);const paintedAfter=await page.locator('#weight-chart').evaluate(c=>c.toDataURL());assert.notEqual(paintedBefore,paintedAfter);await shot('weight-selected-8','[data-trend-module=weight]');await touchWeight(false);await checkValue('weight','85.7',9);await shot('weight-selected-9','[data-trend-module=weight]')
 await touchSvg('water','08');await checkValue('water','1000',8);assert.equal(await module('water').locator('.is-selected').getAttribute('data-point-date'),'2026-10-08');await shot('water-selected-8','[data-trend-module=water]');await touchSvg('water','09');await checkValue('water','1250',9);assert.equal(await module('water').locator('.is-selected').getAttribute('data-point-date'),'2026-10-09');await shot('water-selected-9','[data-trend-module=water]');await shot('water-two','[data-trend-module=water]')
 await touchSvg('sleep','08');await checkValue('sleep','7小时0分钟',8);assert.equal(await module('sleep').locator('.is-selected').getAttribute('data-point-date'),'2026-10-08');await touchSvg('sleep','09');await checkValue('sleep','7小时0分钟',9);await shot('sleep-30','[data-trend-module=sleep]');await shot('sleep-multiple','[data-trend-module=sleep]')
 await range('weight',90);await range('sleep',7);await range('water',30);assert.deepEqual(await state(),['90天','7天','30天']);const selectedBefore=await module('sleep').locator('.chart-selection>span').innerText();await module('sleep').locator('[data-sleep-history]').click();await close();assert.equal(await module('sleep').locator('.chart-selection>span').innerText(),selectedBefore);await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector('.calendar-grid');await page.locator('[data-progress-view=trend]').click();await page.waitForSelector('#weight-chart');assert.deepEqual(await state(),['90天','7天','30天'])
 await page.locator('#weight-history-open').click();await page.waitForSelector('[data-weight-all]');await shot('history-many','dialog[open]');const sheet=await page.locator('dialog[open]').elementHandle();await page.locator('[data-weight-all]').click();await page.waitForSelector('[data-weight-all-chart] #weight-all-chart');await page.locator('#weight-all-chart').focus();await page.keyboard.press('Home');assert.match(await page.locator('[data-weight-all-chart] [data-weight-chart-date]').innerText(),/2025年10月9日/);await shot('weight-all','dialog[open]');await page.locator('[data-history-back]').click();assert.equal(await sheet.evaluate(e=>e===document.querySelector('dialog[open]')),true);await sheet.dispose();await close()
 // Inspecting8th must never silently write8th. All ordinary records default Today.
 await page.locator('#record-weight').click();await shot('weight-record-sheet','dialog[open]');assert.match(await page.locator('#weight-sheet-form p').first().innerText(),/10月10日/);await page.locator('#weight-sheet-form input').fill('85.6');await page.locator('#weight-sheet-form').evaluate(f=>{f.requestSubmit();f.requestSubmit()});await page.waitForFunction(()=>!document.querySelector('dialog[open]'));let rows=await read(page,'weights');assert.equal(rows.filter(w=>w.date===today).length,1);assert.equal(rows.find(w=>w.id==='w8').weightKg,86.6);await page.waitForFunction(()=>document.querySelector('[data-weight-chart-value]')?.textContent==='85.6 kg');assert.equal(await page.locator('#record-weight').innerText(),'修改今日体重');await page.clock.fastForward(7000);await page.waitForSelector('.action-toast',{state:'detached'})
 const weightNode=await page.locator('#weight-chart').elementHandle(),sleepNode=await module('sleep').elementHandle();await module('water').locator('[data-water-record]').click();await shot('water-record-sheet','dialog[open]');await page.locator('[data-water-quick="250"]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await checkValue('water','250',10);assert.equal((await read(page,'waterLogs')).filter(w=>w.date===today).length,1);assert.equal(await weightNode.evaluate(e=>e===document.querySelector('#weight-chart')),true);assert.equal(await sleepNode.evaluate(e=>e===document.querySelector('[data-trend-module=sleep]')),true);await weightNode.dispose();await sleepNode.dispose()
 await module('water').locator('[data-water-record]').click();await page.locator('[data-water-custom]').click();const custom=await page.locator('dialog[open]').elementHandle();await page.locator('[data-water-form] input').fill('333');await page.locator('[data-history-back]').click();assert.equal(await custom.evaluate(e=>e===document.querySelector('dialog[open]')),true);await custom.dispose();await page.locator('[data-water-custom]').click();await page.locator('[data-water-form] input').fill('333');await page.locator('[data-water-form] [type=submit]').click();await page.waitForSelector('[data-water-quick]');await close();await checkValue('water','583',10);await page.clock.fastForward(7000);await page.waitForSelector('.action-toast',{state:'detached'})
 await module('sleep').locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-trend-module=sleep] [data-sleep-action]')?.textContent==='我醒了');assert.equal((await read(page,'sleepSessions')).filter(s=>s.activeKey).length,1);await shot('sleep-active','[data-trend-module=sleep]');await page.clock.fastForward(60000);await module('sleep').locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-trend-module=sleep] [data-sleep-action]')?.textContent==='开始睡眠');assert.equal((await read(page,'sleepSessions')).filter(s=>s.activeKey).length,0)
 await module('sleep').locator('[data-sleep-backfill]').click();await shot('sleep-backfill','dialog[open]');await shot('editor-form','dialog[open]');await page.locator('[data-sleep-backfill-form] [name=start]').fill('02:00');await page.locator('[data-sleep-start-date]').click();await page.locator('.date-picker-day[data-date="2026-10-10"]').click();await page.locator('.date-picker [data-done]').click();await page.locator('[data-sleep-backfill-form] [name=end]').fill('09:00');await page.locator('[data-sleep-backfill-form] [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));rows=await read(page,'sleepSessions');const backfilled=rows.filter(s=>s.startTime==='2026-10-09T18:00:00.000Z');assert.equal(backfilled.length,1);assert.equal(backfilled[0].sleepNightDate,'2026-10-09');assert.equal(backfilled[0].durationMinutes,420);await checkValue('sleep','14小时0分钟',9)
 await module('sleep').locator('[data-sleep-history]').click();await page.locator('.record-history-row').filter({hasText:'2026年10月9日晚'}).locator('[data-view-sleep]').first().click();await page.waitForSelector('.sleep-timeline');await shot('sleep-timeline','dialog[open]');await close()
 // Existing grouped day/report facts see the very same newly saved night and drinks.
 await nav('today');assert.match(await page.locator('.sleep-card').innerText(),/10月10日晚/);assert.match(await page.locator('.sleep-card').innerText(),/0小时1分钟/);assert.equal(await page.locator('[data-water-total]').innerText(),'583');await audit('#view');await shot('today-full');await nav('workout');const headers=await page.locator('.training-card .module-header h2').allTextContents();assert.deepEqual(headers,['力量训练','有氧训练','凯格尔训练']);for(const[k,id]of [['strength','history-workout'],['cardio','cardio-history'],['kegel','pelvic-floor-history']]){assert.equal(await page.locator(`#${id}`).locator('..').evaluate(e=>e.classList.contains('module-header')),true);await shot('training-'+k,`.training-card:has(#${id})`);await page.locator(`#${id}`).click();if(k==='strength'){await page.waitForSelector('#close-history');await page.locator('#close-history').click()}else{await page.waitForSelector('dialog[open]');await close()}await page.waitForSelector('#start-workout')}await audit('#view');await shot('training-full')
 await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.locator('.calendar-day[data-date="2026-10-09"]').click();assert.match(await page.locator('[data-record-category=sleep] summary').innerText(),/14小时/);await close();await page.locator('[data-progress-view=reports]').click();await page.locator('[data-report-mode=month]').click();await page.waitForSelector('.recovery-report');await audit('#view');await shot('report-full');if(colorScheme==='dark')await shot('report-dark');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-date]');assert.match(await page.locator('[data-record-category=water] summary').innerText(),/583/)
 // Equal values still move the date and marker. Three same-day drinks remain three facts.
 await replaceFacts({waterLogs:[water('equal8','2026-10-08',1250),water('equal9','2026-10-09',1250)]});await trend();await touchSvg('water','08');await checkValue('water','1250',8);await touchSvg('water','09');await checkValue('water','1250',9);assert.equal(await module('water').locator('.is-selected').getAttribute('data-point-date'),'2026-10-09');await shot('water-equal-two','[data-trend-module=water]')
 const dense=Array.from({length:90},(_,i)=>{const d=new Date('2026-10-10T12:00:00');d.setDate(d.getDate()-i);const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return{date,i}})
 await replaceFacts({weights:dense.map(({date,i})=>weight('dense-w'+i,date,85+i/10)),waterLogs:dense.map(({date,i})=>water('dense-d'+i,date,1250+i)),sleepSessions:dense.map(({date,i})=>({...sleep('dense-s'+i,date),sleepNightDate:date,sleepNightDateSource:'manual',sleepStartLocalDate:date}))});await trend();await page.waitForFunction(()=>document.querySelector('[data-chart-kind=water] [data-point-date="2026-10-10"][data-point-value]'));for(const k of ['weight','sleep','water']){await range(k,90);const scroll=module(k).locator('.trend-chart-shell');assert.ok(await scroll.evaluate(e=>e.scrollWidth>e.clientWidth));await scroll.evaluate(e=>e.scrollLeft=0);assert.equal(await scroll.evaluate(e=>e.scrollLeft),0);if(k==='weight'){await module(k).locator('canvas').focus();await page.keyboard.press('Home')}else{await module(k).locator('[data-point-value]').first().focus();await page.keyboard.press('Enter')}await page.keyboard.press('End');assert.match(await module(k).locator('.chart-selection>span').textContent(),/10月10日/)}await shot('water-many','[data-trend-module=water]');assert.equal(await page.locator('.recovery-point-label').count(),0)
 if(representative||width===844){const region=module('water').locator('.trend-chart-shell');await region.scrollIntoViewIfNeeded();await region.evaluate(e=>e.scrollLeft=0);const b=await region.boundingBox(),selected=await module('water').locator('.chart-selection>span').textContent(),cdp=await context.newCDPSession(page);await cdp.send('Input.synthesizeScrollGesture',{x:b.x+b.width/2,y:b.y+b.height/2,xDistance:-140,yDistance:0,gestureSourceType:'touch',speed:400});assert.ok(await region.evaluate(e=>e.scrollLeft>20));assert.equal(await module('water').locator('.chart-selection>span').textContent(),selected);const before=await page.evaluate(()=>scrollY);await cdp.send('Input.synthesizeScrollGesture',{x:b.x+b.width/2,y:b.y+b.height/2,xDistance:0,yDistance:120,gestureSourceType:'touch',speed:400});assert.ok(await page.evaluate(previous=>scrollY<previous-20,before));assert.equal(await module('water').locator('.chart-selection>span').textContent(),selected);await cdp.detach()}

 await replaceFacts({weights:[],waterLogs:[],sleepSessions:[]});await trend();await page.waitForFunction(()=>document.querySelectorAll('.trend-module .trend-empty').length===3);assert.equal(await page.locator('.trend-module canvas,.trend-module svg.recovery-line-chart').count(),0);for(const k of ['weight','sleep','water'])await shot(k+'-empty',`[data-trend-module=${k}]`)
 await replaceFacts({weights:[weight('one',today,85)],waterLogs:[water('one',today,250)],sleepSessions:[sleep('one',today)]});await trend();await page.waitForFunction(()=>!!document.querySelector('#weight-chart'));await shot('sleep-single','[data-trend-module=sleep]');await module('water').locator('[data-water-history]').click();await page.waitForSelector('[data-history-id]');await shot('history-one','dialog[open]');if(scale===100)assert.ok((await page.locator('dialog[open]').boundingBox()).height<height*.7);await close()
 // Necessary whole-site size audit, without changing domain structures.
 await nav('plan');await audit('#view');await shot('plan-full');await nav('food');await audit('#view');await shot('food-full');await page.locator('#open-management').click();await page.waitForSelector('#more-food-library');await audit('dialog[open]');await shot('management-full','dialog[open]');await close()
 let cycles=0
 if(representative){
  await replaceFacts({weights:data.weights,waterLogs:data.waterLogs,sleepSessions:data.sleepSessions});await nav('workout');await page.clock.fastForward(7000);const cdp=await context.newCDPSession(page)
  const listeners=async()=>{const result={};for(const name of ['window','document']){const {result:r}=await cdp.send('Runtime.evaluate',{expression:name});const l=await cdp.send('DOMDebugger.getEventListeners',{objectId:r.objectId});result[name]=l.listeners.length;await cdp.send('Runtime.releaseObject',{objectId:r.objectId})}return result}
  const canvases=async()=>{await cdp.send('HeapProfiler.collectGarbage');const {result:proto}=await cdp.send('Runtime.evaluate',{expression:'HTMLCanvasElement.prototype'}),{objects}=await cdp.send('Runtime.queryObjects',{prototypeObjectId:proto.objectId}),{result:r}=await cdp.send('Runtime.callFunctionOn',{objectId:objects.objectId,functionDeclaration:'function(){return this.filter(canvas=>Object.hasOwn(canvas,"$chartjs")).length}',returnByValue:true});await cdp.send('Runtime.releaseObject',{objectId:objects.objectId});await cdp.send('Runtime.releaseObject',{objectId:proto.objectId});return r.value}
  const beforeListeners=await listeners(),beforeCanvas=await canvases(),beforeResources=await page.evaluate(()=>unifiedResources());assert.equal(beforeCanvas,0)
  for(let i=0;i<20;i++){
   await trend();assert.equal(await canvases(),1);for(const k of ['weight','sleep','water']){for(const n of [7,30,90])await range(k,n);if(k==='weight'){await module(k).locator('canvas').focus();await page.keyboard.press('Home');await page.keyboard.press('End')}else{await module(k).locator('[data-point-value]').first().focus();await page.keyboard.press('Enter');await page.keyboard.press('End')}await module(k).locator('.module-history').click();await close()}
   await page.locator('#record-weight').click();await page.locator('#weight-sheet-form input').fill(String(85+i/10));await page.locator('#weight-sheet-form [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'))
   await module('sleep').locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-trend-module=sleep] [data-sleep-action]')?.textContent==='我醒了');await page.clock.fastForward(60000);await module('sleep').locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-trend-module=sleep] [data-sleep-action]')?.textContent==='开始睡眠');assert.equal(await module('sleep').locator('[data-sleep-backfill]').count(),1)
   await module('water').locator('[data-water-record]').click();await page.locator('[data-water-quick="250"]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await checkValue('water',String((i+1)*250),10)
   await nav('workout');for(const id of ['history-workout','cardio-history','pelvic-floor-history']){await page.locator('#'+id).click();if(id==='history-workout')await page.locator('#close-history').click();else{await page.waitForSelector('dialog[open]');await close()}await page.waitForSelector('#start-workout')}
   await nav('today');assert.equal(await page.locator('[data-water-total]').innerText(),String((i+1)*250));await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector('.calendar-day[data-date="2026-10-10"] .calendar-category-water');assert.equal(await page.locator('.calendar-day[data-date="2026-10-10"] .calendar-category-water').count(),1);await page.locator('[data-progress-view=reports]').click();await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-date]');assert.match(await page.locator('[data-record-category=water] summary').innerText(),new RegExp(String((i+1)*250)));await nav('workout');await page.clock.fastForward(7000);await page.waitForSelector('.action-toast',{state:'detached'})
   assert.deepEqual(await listeners(),beforeListeners);assert.deepEqual(await page.evaluate(()=>unifiedResources()),beforeResources);assert.equal(await canvases(),beforeCanvas);assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('sheet-open')||e.classList.contains('immersive')),false);assert.equal((await read(page,'weights')).filter(w=>w.date===today).length,1);assert.equal((await read(page,'sleepSessions')).filter(s=>s.activeKey).length,0);cycles++
  }
  const drinks=(await read(page,'waterLogs')).filter(w=>w.date===today);assert.equal(drinks.length,20);assert.equal(new Set(drinks.map(w=>w.id)).size,20);assert.equal((await read(page,'sleepSessions')).length,22)
 }
 assert.deepEqual(errors,[])
 const receipt={width,height,scale,colorScheme,reduced,sharedThreePeers:true,default30:true,independentRanges:true,retainedState:true,weight8_9CoordinateTouch:true,water8_9CoordinateTouch:true,sleepCoordinateTouch:true,equalValueDateHighlight:true,uniformPlotReadout:true,denseInternalScroll:true,allWeightHistory:true,todayWriteDate:true,weightWaterSleepBackfillWrites:true,crossSurfaceFacts:true,trainingNearby:true,wholeSiteBounds:true,stressCycles:cycles,noLiveChartTimerListenerLeak:true,errors,physicalIPhone:'Pending'};receipts.push(receipt);console.log(JSON.stringify(receipt))
 }catch(e){await page.screenshot({path:path.join(dir,prefix+'-failure.png'),fullPage:true}).catch(()=>{});console.error('FAILURE_STATE',await page.locator('body').innerText());throw e}finally{await context.close()}
}}finally{await browser.close()}
await fs.writeFile(path.join(dir,'receipt'+(process.env.FITLOG_UNIFIED_WIDTH?'-'+process.env.FITLOG_UNIFIED_WIDTH:'')+'.json'),JSON.stringify(receipts,null,2))
