// V4.2.1 seven precise fixes: full visual matrix and real existing-service actions. Synthetic contexts only.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
const pw=await import(process.env.FITLOG_PLAYWRIGHT_MODULE),engine=process.env.FITLOG_V4_ENGINE||'chromium',base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5186/fitlog-lite/',prod=base.includes('github.io')
const dir=path.resolve('../../artifacts/v4-2-1-2026-10-10',process.env.FITLOG_V421_BEFORE?'before':prod?'prod':engine==='webkit'?'webkit':'local');await fs.mkdir(dir,{recursive:true})
const matrix=prod||engine==='webkit'||process.env.FITLOG_V421_BEFORE?[[390,100,'light','no-preference'],[320,140,'light','reduce'],[320,200,'dark','reduce'],[430,140,'dark','reduce'],[844,140,'dark','reduce']]:[...[320,375,390,430].flatMap(w=>[100,120,140,200].flatMap(s=>['light','dark'].flatMap(c=>['no-preference','reduce'].map(m=>[w,s,c,m])))),[844,140,'dark','reduce']]
const cases=process.env.FITLOG_V4_SMOKE?[[390,100,'light','no-preference']]:matrix.filter(x=>(!process.env.FITLOG_V4_WIDTH||x[0]===Number(process.env.FITLOG_V4_WIDTH))&&(!process.env.FITLOG_V4_CASE||x.join('-')===process.env.FITLOG_V4_CASE))
const browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.FITLOG_CHROME}:{})}),receipts=[]
for(const[width,scale,colorScheme,reducedMotion]of cases){
 const ctx=await browser.newContext({viewport:{width,height:width===844?390:844},colorScheme,reducedMotion,hasTouch:true,isMobile:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'}),page=await ctx.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000)
 const prefix=`${width}-${scale}-${colorScheme}-${reducedMotion}`
 const shot=async name=>page.screenshot({path:path.join(dir,prefix+'-'+name+'.png'),fullPage:true})
 try{
 await page.addInitScript(()=>{window.v4TouchTrace=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,e=>{const r=e.target?.getBoundingClientRect?.();window.v4TouchTrace.push({type,target:e.target?.outerHTML?.slice(0,180),x:e.clientX,y:e.clientY,box:r&&{top:r.top,bottom:r.bottom,left:r.left,right:r.right},modal:!!document.querySelector('dialog[open]')});window.v4TouchTrace=window.v4TouchTrace.slice(-15)},true)});
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management')
 const today=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}),past=await page.evaluate(today=>{const d=new Date(today+'T12:00:00');d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},today),stamp=today+'T01:00:00Z'
 const write=async data=>page.evaluate(async data=>{const d=await new Promise((r,j)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
 const read=async name=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return rows},name)
 const f=(id,name,calories,protein,carbs,fat)=>({id,name,referenceGrams:100,calories,protein,carbs,fat,createdAt:stamp,updatedAt:stamp})
 const foods=[f('chicken','鸡胸肉',165,31,0,3.6),f('rice','米饭',116,2.6,25.9,.3),f('oil','橄榄油',900,0,0,100),f('unknown','未知碳水食物',80,3,undefined,1)]
 const target={id:'v4-goal',date:today,calories:2200,protein:159,carbs:250,fat:70,createdAt:stamp,updatedAt:stamp}
 const logs=[{id:'v4-log',date:today,meal:'breakfast',foodId:'chicken',foodName:'早餐历史快照',grams:100,referenceGrams:100,caloriesPerReference:1619,proteinPerReference:135.6,carbsPerReference:188,fatPerReference:32.3,totalCalories:1619,totalProtein:135.6,totalCarbs:188,totalFat:32.3,createdAt:stamp,updatedAt:stamp}]
 const tasks=[{id:'v4-task',title:'阅读与写训练笔记',date:today,startTime:'09:00',tagIds:['v4-tag'],createdAt:stamp,updatedAt:stamp},{id:'v4-inbox',title:'未安排日期的事项',tagIds:[],createdAt:stamp,updatedAt:stamp},{id:'v4-past',title:'未来计划',date:today.slice(0,8)+'28',tagIds:[],createdAt:stamp,updatedAt:stamp}]
 await write({foods,foodLogs:logs,nutritionTargets:[target],weights:[{id:'v4-weight',date:today,weightKg:75,createdAt:stamp,updatedAt:stamp}],tasks,taskTags:[{id:'v4-tag',name:'生活',createdAt:stamp,updatedAt:stamp}]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`})
 const nav=async tab=>{await page.locator(`[data-tab=${tab}]`).click();await page.waitForSelector(tab==='today'?'.nutrition-today-card':tab==='food'?'.food-content-body':tab==='plan'?'.plan-page':'.page-tabs')}
 const bounds=async selector=>{await page.locator(selector).evaluateAll(roots=>Promise.all(roots.flatMap(r=>r.getAnimations({subtree:true})).filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));const failures=await page.locator(selector).evaluateAll(roots=>{const failures=[];for(const root of roots)for(const e of [root,...root.querySelectorAll('*')]){if(!e.getClientRects().length||e instanceof SVGElement||e.classList.contains('sr-only'))continue;const r=e.getBoundingClientRect(),c=getComputedStyle(e);if(r.width&&r.left<-.5||r.right>innerWidth+.5)failures.push('bounds '+e.className);if(e.scrollWidth>e.clientWidth+1&&!['auto','scroll'].includes(c.overflowX)&&!e.matches('.meal-preview,.meal-preview-names,.meal-preview-name,.plan-context-label,.plan-tag-chip'))failures.push('clipped '+e.className)}return failures});assert.deepEqual(failures,[],prefix+' '+selector);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=visualViewport.width+1),true)}
 const rect=async selector=>page.locator(selector).first().evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{top:r.top,bottom:r.bottom,left:r.left,right:r.right,w:r.width,h:r.height,marginTop:s.marginTop,marginBottom:s.marginBottom,padding:s.padding,gap:s.gap,background:s.backgroundColor,border:s.borderWidth}})
 await page.waitForSelector('[data-sleep-action]');await shot('today');const todayRemaining=await rect('[data-today-remaining] .food-completion-strip');const sleepIdle=await rect('[data-sleep-action]');await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-action]')?.textContent==='我醒了');await shot('sleep-active');await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-action]')?.textContent==='开始睡眠')
 await nav('food');await shot('food');const special=await rect('.diet-events'),hero=await rect('.food-nutrition-hero'),mealHead=await rect('.food-meals-head'),meals=await rect('.food-meals')
 await nav('progress');await page.locator('[data-progress-view=reports]').click();await page.waitForSelector('.coach-report');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-category=food]');await shot('report');const reportDetails=await rect('.coach-nutrition-details'),reportSummary=await rect('.coach-nutrition-details summary'),reportNote=await page.locator('.coach-nutrition-details').evaluate(e=>{const r=e.closest('.coach-section').querySelector('.coach-note').getBoundingClientRect();return{top:r.top,bottom:r.bottom}}),foodSummary=await rect('[data-record-category=food] summary')
 await page.locator('[data-record-category=food] summary').click();await shot('food-detail');await page.locator('.coach-nutrition-details summary').click();await shot('report-expanded');
 receipts.push({width,scale,colorScheme,reducedMotion,todayRemaining,sleepIdle,foodSpacing:{heroToSpecial:special.top-hero.bottom,specialToMeals:mealHead.top-special.bottom,headingToCards:meals.top-mealHead.bottom,special},reportSpacing:{detailsToNote:reportNote.top-reportDetails.bottom,summaryToNote:reportNote.top-reportSummary.bottom,reportDetails},foodSummary});console.log(prefix+(process.env.FITLOG_V421_BEFORE?' CAPTURE':' VERIFY'))
 if(process.env.FITLOG_V421_BEFORE)continue
 const close=async()=>page.locator('dialog[open] [data-close]').click()
 // Nutrition disclosure keeps every actual and target, without narrow-column prose.
 const folded=page.locator('[data-record-category=food] summary')
 assert.ok(!(await folded.innerText()).includes('蛋白质'));assert.ok((await folded.innerText()).includes('1619 kcal'))
 const actual=page.locator('[data-daily-nutrition=actual]'),savedTarget=page.locator('[data-daily-nutrition=target]')
 assert.deepEqual(await actual.locator('dt').allTextContents(),['热量','蛋白质','碳水','脂肪']);assert.deepEqual(await actual.locator('dd').allTextContents(),['1619 kcal','135.6 g','188 g','32.3 g']);assert.deepEqual(await savedTarget.locator('dd').allTextContents(),['2200 kcal','159 g','250 g','70 g']);assert.ok((await page.locator('.daily-record-content').first().innerText()).includes('早餐历史快照'));await bounds('.coach-report')
 const reportGeometry=await page.locator('.coach-nutrient').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),bar=e.querySelector('.coach-meter').getBoundingClientRect();return{w:r.width,h:r.height,top:r.top,bar:bar.top}}));assert.equal(reportGeometry.length,4);for(const a of reportGeometry)for(const b of reportGeometry){assert.ok(Math.abs(a.w-b.w)<=1&&Math.abs(a.h-b.h)<=1);if(Math.abs(a.top-b.top)<1)assert.ok(Math.abs(a.bar-b.bar)<=1)}
 assert.equal(reportDetails.marginBottom,'0px');assert.ok(reportNote.top-reportDetails.bottom>=0&&reportNote.top-reportDetails.bottom<=8);const expandedEnd=await rect('.coach-nutrition-details'),expandedNote=await rect('.coach-nutrition-footer .coach-note');assert.ok(expandedNote.top>=expandedEnd.bottom&&expandedNote.top-expandedEnd.bottom<=8);assert.ok((await page.locator('.coach-nutrition-details').innerText()).includes('同日配对'));await bounds('.coach-report')
 await page.locator('.coach-nutrition-details summary').click();await page.locator('[data-record-category=food] summary').click();await bounds('.coach-report')
 // Empty special-diet block keeps its action, and page spacing has one owner.
 assert.equal(special.marginTop,'0px');assert.equal(special.marginBottom,'0px');assert.ok(special.top-hero.bottom<=12.1&&mealHead.top-special.bottom<=12.1&&meals.top-mealHead.bottom<=12.1)
 await nav('food');await page.locator('[data-diet-event-new]').click();await page.locator('.diet-event-form [name=note]').fill('仅备注，不进入摄入');await page.locator('.diet-event-form [name=calories]').fill('9999');await page.locator('.diet-event-form [type=submit]').click();await page.waitForSelector('[data-diet-event-edit]');assert.equal(await page.locator('.calorie-budget').getAttribute('data-actual'),'1619');await shot('food-special');await bounds('.food-content-body');await page.locator('[data-diet-event-edit]').click();assert.equal(await page.locator('.diet-event-form [name=note]').inputValue(),'仅备注，不进入摄入');await close();assert.equal(await page.locator('#save-day-diet-template').count(),1);for(const meal of ['breakfast','lunch','dinner','snack'])assert.equal(await page.locator(`[data-add-meal=${meal}]`).count(),1)
 const remainingFood=await page.locator('.remaining-goals-grid').evaluate(e=>e.outerHTML),foodRemaining=await rect('.food-remaining');await nav('today');assert.equal(await page.locator('[data-today-remaining] .remaining-goals-grid').evaluate(e=>e.outerHTML),remainingFood);assert.equal(todayRemaining.background,'rgba(0, 0, 0, 0)');assert.ok(todayRemaining.border.split(' ').some(v=>v==='0px'));assert.ok(todayRemaining.padding.includes('0px'));assert.equal(await page.locator('[data-today-completion]').count(),1);assert.equal(await page.locator('[data-today-remaining] .completion-entry-actions').count(),0);assert.equal(foodRemaining.border,'1px');await bounds('.today-dashboard')
 // All ordinary Today peers share real primitives, geometry and color in both themes.
 const actionGeometry=await page.locator('#today-workout,#today-cardio,#today-record-weight,#today-pelvic,[data-sleep-action]').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e);return{right:r.right,height:r.height,padding:c.padding,radius:c.borderRadius,font:c.fontSize,background:c.backgroundColor,ink:c.color,secondary:e.classList.contains('secondary')}}));assert.equal(actionGeometry.length,5);assert.ok(actionGeometry.every(g=>g.secondary&&g.height>=44));assert.ok(Math.max(...actionGeometry.map(g=>g.right))-Math.min(...actionGeometry.map(g=>g.right))<=2);assert.equal(new Set(actionGeometry.map(g=>g.height)).size,1);for(const key of ['padding','radius','font','background','ink'])assert.equal(new Set(actionGeometry.map(g=>g[key])).size,1,key)
 const copyGeometry=await page.locator('.today-training-row .today-activity-copy').evaluateAll(es=>es.map(e=>({left:e.getBoundingClientRect().left,label:e.querySelector('.today-activity-status').getBoundingClientRect().left,font:getComputedStyle(e.querySelector('.today-activity-status')).fontSize})));assert.equal(copyGeometry.length,2);assert.equal(copyGeometry[0].left,copyGeometry[1].left);assert.equal(copyGeometry[0].label,copyGeometry[1].label);assert.equal(copyGeometry[0].font,copyGeometry[1].font)
 // Capture a historical Workout date, then prove Today Cardio owns today without mutating history.
 const historical={id:'v421-old-cardio',date:past,activityType:'treadmill',durationMinutes:12.25,speed:5,createdAt:stamp,updatedAt:stamp};await write({cardioSessions:[historical]});await nav('progress');await page.locator('[data-progress-view=calendar]').click();await page.waitForSelector(`.calendar-day[data-date="${past}"]`);await page.locator(`.calendar-day[data-date="${past}"]`).click();await page.locator('#calendar-day-workout').click();await page.waitForSelector('#add-cardio');await nav('today');await page.locator('#today-cardio').click();await page.waitForSelector('#cardio-form');assert.ok((await page.locator('.cardio-form-date').innerText()).includes('今天'));await page.locator('#cardio-form [name=duration]').fill('17.125');await page.locator('#cardio-form [name=speed]').fill('6.5');await page.locator('#cardio-form [type=submit]').click();await page.waitForFunction(()=>document.querySelector('.today-cardio-row')?.textContent.includes('17.1 分钟'));const cardio=await read('cardioSessions');assert.deepEqual(cardio.find(c=>c.id===historical.id),historical);assert.equal(cardio.filter(c=>c.date===today).length,1);assert.equal(cardio.find(c=>c.date===today).durationMinutes,17.125);await shot('today-cardio-recorded');await bounds('.workout-today-card')
 // Ordinary sleep start is secondary; active finish is primary. Busy states are immediately preserved.
 await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-action]')?.textContent==='我醒了');assert.ok(await page.locator('[data-sleep-action]').evaluate(e=>e.classList.contains('primary')));await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-action]')?.textContent==='开始睡眠');assert.ok(await page.locator('[data-sleep-action]').evaluate(e=>e.classList.contains('secondary')));assert.equal((await read('sleepSessions')).filter(s=>s.activeKey).length,0);assert.ok((await read('sleepSessions')).every(s=>s.endTime&&s.durationMinutes>=0));await bounds('[data-recovery-root]')
 // Representative queued sleep start: disabled/busy, duplicate ignored, then actual completion.
 if(width===390&&scale===100&&colorScheme==='light'&&reducedMotion==='no-preference'){
  const beforeSleep=(await read('sleepSessions')).length
  await page.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)}),t=d.transaction('sleepSessions','readwrite'),store=t.objectStore('sleepSessions');window.v421SleepLock=true;const keep=()=>{const q=store.count();q.onsuccess=()=>{if(window.v421SleepLock)keep()}};keep();t.oncomplete=()=>d.close()})
  await page.locator('[data-sleep-action]').click();assert.equal(await page.locator('[data-sleep-action]').isDisabled(),true);assert.equal(await page.locator('[data-sleep-action]').getAttribute('aria-busy'),'true');await page.locator('[data-sleep-action]').evaluate(e=>e.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.evaluate(()=>window.v421SleepLock=false);await page.waitForFunction(()=>document.querySelector('[data-sleep-action]')?.textContent==='我醒了'&&!document.querySelector('[data-sleep-action]').disabled);assert.equal((await read('sleepSessions')).length,beforeSleep+1);await page.locator('[data-sleep-action]').click();await page.waitForFunction(()=>document.querySelector('[data-sleep-action]')?.textContent==='开始睡眠');assert.equal((await read('sleepSessions')).filter(s=>s.activeKey).length,0)
  const open={id:'v421-open',date:today,startedAt:stamp,exercises:[],createdAt:stamp,updatedAt:stamp};await write({workouts:[open]});await nav('food');await nav('today');assert.equal(await page.locator('#today-workout').innerText(),'继续力量训练');assert.ok(await page.locator('#today-workout').evaluate(e=>e.classList.contains('primary')));await page.locator('#today-workout').click();await page.waitForSelector('#finish-workout');assert.deepEqual(await read('workouts'),[open]);await page.locator('#exit-workout').click();await page.waitForSelector('#start-workout');await nav('today')
 }
 // Shared summary state remains factual for unset/reached/excess/incomplete, in both density variants.
 for(const [goal,log,expected]of [[undefined,logs[0],'未设置'],[{...target,calories:1619,protein:135.6,carbs:188,fat:32.3},logs[0],'已达目标'],[{...target,calories:1600},logs[0],'已超'],[target,{...logs[0],totalFat:undefined},'数据不完整']]){
  await write({nutritionTargets:goal?[goal]:[],foodLogs:[log]});await nav('food');const foodText=await page.locator('.remaining-goals-grid').innerText();assert.ok(foodText.includes(expected),foodText+' expected '+expected);await nav('today');assert.equal(await page.locator('.remaining-goals-grid').innerText(),foodText);await bounds('.nutrition-today-card')
 }
 if(width===390&&scale===100&&colorScheme==='light'&&reducedMotion==='no-preference'){
  const name='很长的已保存食物名称'.repeat(18)+'<img onerror=alert(1)>'
  await write({foodLogs:[{...logs[0],foodName:name,totalCalories:123456.7,totalProtein:1234.56,totalCarbs:9999.9,totalFat:0}],nutritionTargets:[{...target,calories:999999,protein:9999,carbs:9999,fat:9999}]});await nav('progress');await page.locator('[data-progress-view=reports]').click();await page.waitForSelector('.coach-report');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('[data-record-category=food]');await page.locator('[data-record-category=food] summary').click();await page.setViewportSize({width:320,height:844});await page.addStyleTag({content:'html{font-size:200%}'});await bounds('.coach-report');assert.ok((await page.locator('[data-record-category=food]').innerText()).includes(name));assert.equal(await page.locator('[data-record-category=food] img').count(),0);assert.ok((await page.locator('[data-daily-nutrition=actual]').innerText()).includes('123457'));assert.ok((await page.locator('[data-daily-nutrition=target]').innerText()).includes('999999'));await shot('large-saved-detail');Object.assign(receipts.at(-1),{largeSavedDetail320Font200:true})
 }
 assert.deepEqual(errors,[]);Object.assign(receipts.at(-1),{reportGeometry,actionGeometry,copyGeometry,strictSameDataDifferentDensity:true,todayCardioDate:true,sleepSemantics:true,specialNoCanonicalIntake:true,completeDisclosure:true,errors,physicalIPhone:'Pending'});console.log(prefix+' PASS')
 }finally{await ctx.close()}
}
await browser.close();await fs.writeFile(path.join(dir,'receipt'+(process.env.FITLOG_V4_WIDTH?'-'+process.env.FITLOG_V4_WIDTH:'')+'.json'),JSON.stringify(receipts,null,2))
