// V4.2 real UI and data writes, exclusively fresh invented-data browser contexts.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
const pw=await import(process.env.FITLOG_PLAYWRIGHT_MODULE),engine=process.env.FITLOG_V4_ENGINE||'chromium',base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5186/fitlog-lite/',prod=base.includes('github.io')
const dir=path.resolve(process.env.FITLOG_QA_ARTIFACT_ROOT||'../../artifacts/v4-2-2026-10-10',process.env.FITLOG_QA_ARTIFACT_ROOT?`v4-flows-${process.env.FITLOG_V4_CAPTURE_BEFORE?'before':prod?'prod':engine==='webkit'?'webkit':'local'}`:process.env.FITLOG_V4_CAPTURE_BEFORE?'before':prod?'prod':engine==='webkit'?'webkit':'local');await fs.mkdir(dir,{recursive:true})
const matrix=prod||engine==='webkit'?[[390,100,'light','no-preference'],[320,140,'light','reduce'],[320,200,'dark','reduce'],[430,140,'dark','reduce'],[844,140,'dark','reduce']]:[...[320,375,390,430].flatMap(w=>[100,120,140,200].flatMap(s=>['light','dark'].flatMap(c=>['no-preference','reduce'].map(m=>[w,s,c,m])))),[844,140,'dark','reduce']]
const cases=process.env.FITLOG_V4_SMOKE?[[390,100,'light','no-preference']]:matrix.filter(x=>(!process.env.FITLOG_V4_WIDTH||x[0]===Number(process.env.FITLOG_V4_WIDTH))&&(!process.env.FITLOG_V4_CASE||x.join('-')===process.env.FITLOG_V4_CASE))
const browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{executablePath:process.env.FITLOG_CHROME}:{})}),receipts=[]
for(const[width,scale,colorScheme,reducedMotion]of cases){
 const ctx=await browser.newContext({viewport:{width,height:width===844?390:844},colorScheme,reducedMotion,hasTouch:true,isMobile:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'}),page=await ctx.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000)
 const prefix=`${width}-${scale}-${colorScheme}-${reducedMotion}`
 const shot=async name=>page.screenshot({path:path.join(dir,prefix+'-'+name+'.png'),fullPage:true})
 try{
 await page.addInitScript(()=>{window.v4TouchTrace=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,e=>{const r=e.target?.getBoundingClientRect?.();window.v4TouchTrace.push({type,target:e.target?.outerHTML?.slice(0,180),x:e.clientX,y:e.clientY,box:r&&{top:r.top,bottom:r.bottom,left:r.left,right:r.right},modal:!!document.querySelector('dialog[open]')});window.v4TouchTrace=window.v4TouchTrace.slice(-15)},true)});
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-management')
 const today=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}),past=await page.evaluate(today=>{const d=new Date(today+'T12:00:00');d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},today),stamp=today+'T01:00:00Z'
 const write=async data=>page.evaluate(async data=>{const d=await new Promise((r,j)=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise((r,j)=>{const t=d.transaction(Object.keys(data),'readwrite');for(const[name,rows]of Object.entries(data)){const s=t.objectStore(name);s.clear();for(const row of rows)s.put(row)}t.oncomplete=r;t.onerror=()=>j(t.error)});d.close()},data)
 const read=async name=>page.evaluate(async name=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const rows=await new Promise(r=>{const q=d.transaction(name).objectStore(name).getAll();q.onsuccess=()=>r(q.result)});d.close();return rows},name)
 const f=(id,name,calories,protein,carbs,fat)=>({id,name,referenceGrams:100,calories,protein,carbs,fat,createdAt:stamp,updatedAt:stamp})
 const foods=[f('chicken','鸡胸肉',165,31,0,3.6),f('rice','米饭',116,2.6,25.9,.3),f('oil','橄榄油',900,0,0,100),f('unknown','未知碳水食物',80,3,undefined,1)]
 const target={id:'v4-goal',date:today,calories:2200,protein:159,carbs:250,fat:70,createdAt:stamp,updatedAt:stamp}
 const logs=[{id:'v4-log',date:today,meal:'breakfast',foodId:'chicken',foodName:'早餐历史快照',grams:100,referenceGrams:100,caloriesPerReference:1893.9,totalCalories:1893.9,totalProtein:136.5,totalCarbs:217,totalFat:53.4,createdAt:stamp,updatedAt:stamp}]
 const tasks=[{id:'v4-task',title:'阅读与写训练笔记',date:today,startTime:'09:00',tagIds:['v4-tag'],createdAt:stamp,updatedAt:stamp},{id:'v4-inbox',title:'未安排日期的事项',tagIds:[],createdAt:stamp,updatedAt:stamp},{id:'v4-past',title:'未来计划',date:today.slice(0,8)+'28',tagIds:[],createdAt:stamp,updatedAt:stamp}]
 await write({foods,foodLogs:logs,nutritionTargets:[target],weights:[{id:'v4-weight',date:today,weightKg:75,createdAt:stamp,updatedAt:stamp}],tasks,taskTags:[{id:'v4-tag',name:'生活',createdAt:stamp,updatedAt:stamp}]});await page.reload({waitUntil:'networkidle'});await page.addStyleTag({content:`html{font-size:${scale}%}`})
 const nav=async tab=>{await page.locator(`[data-tab=${tab}]`).click();await page.waitForSelector(tab==='today'?'.nutrition-today-card':tab==='food'?'.food-content-body':tab==='plan'?'.plan-page':'.page-tabs')}
 const bounds=async selector=>{await page.locator(selector).evaluateAll(roots=>Promise.all(roots.flatMap(r=>r.getAnimations({subtree:true})).filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));const failures=await page.locator(selector).evaluateAll(roots=>{const failures=[];for(const root of roots)for(const e of [root,...root.querySelectorAll('*')]){if(!e.getClientRects().length||e instanceof SVGElement||e.classList.contains('sr-only'))continue;const r=e.getBoundingClientRect(),c=getComputedStyle(e);if(r.width&&r.left<-.5||r.right>innerWidth+.5)failures.push('bounds '+e.className);if(e.scrollWidth>e.clientWidth+1&&!['auto','scroll'].includes(c.overflowX)&&!e.matches('.meal-preview,.meal-preview-names,.meal-preview-name,.plan-context-label,.plan-tag-chip'))failures.push('clipped '+e.className)}return failures});assert.deepEqual(failures,[],prefix+' '+selector);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=visualViewport.width+1),true)}
 await shot('today');await nav('food');await shot('food');if(process.env.FITLOG_V4_CAPTURE_BEFORE){await nav('plan');await shot('plan');await nav('progress');await page.locator('[data-progress-view=reports]').click();await page.waitForSelector('.coach-report');await shot('report');continue}
 const summary=()=>page.locator('.macro-nutrition-summary').evaluate(e=>e.outerHTML)
 await nav('today');const todayHtml=await summary(),budgetToday=await page.locator('.calorie-budget').getAttribute('data-actual');await bounds('.nutrition-today-card');await nav('food');assert.equal(await summary(),todayHtml);assert.equal(await page.locator('.calorie-budget').getAttribute('data-actual'),budgetToday);assert.deepEqual(await page.locator('.macro-per-kg').allTextContents(),['1.82 g/kg','2.89 g/kg','0.71 g/kg']);assert.equal(await page.locator('.macro-nutrition-summary svg').count(),0);assert.ok(await page.locator('.budget-track').evaluate(e=>e.getBoundingClientRect().width>e.closest('.calorie-budget').getBoundingClientRect().width*.8));assert.equal(await page.locator('.remaining-goal').count(),4);await bounds('.food-content-body')
 if(scale===100){const tops=await page.locator('.nutrition-metric').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().top));assert.ok(Math.max(...tops)-Math.min(...tops)<1)}
 // One small recording entry, one disclosure; informational header never toggles.
 assert.equal(await page.locator('[data-meal-section=breakfast] [data-toggle-meal]').count(),1);await page.locator('[data-meal-section=breakfast] .food-meal-summary').click();assert.equal(await page.locator('[data-meal-section=breakfast] .meal-log-list').isVisible(),false);await page.locator('[data-toggle-meal=breakfast]').click();assert.equal(await page.locator('[data-meal-section=breakfast] .meal-log-list').isVisible(),true);await page.locator('[data-toggle-meal=breakfast]').click()
 await page.locator('[data-add-meal=lunch]').click();const identity=await page.locator('dialog[open]').evaluate(e=>{e.dataset.v4Identity='retained';return true});assert.equal(identity,true)
 for(const[id,grams]of[['chicken','125'],['rice','150']]){
  await page.locator(`[data-food=${id}]`).click();await page.locator('#grams').fill(grams);await bounds('dialog[open]');
  if(id==='chicken'){
   await page.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const t=d.transaction('foodLogs','readwrite'),s=t.objectStore('foodLogs');window.v4Lock=true;const keep=()=>{const q=s.count();q.onsuccess=()=>{if(window.v4Lock)keep()}};keep();t.oncomplete=()=>d.close()});
   await page.locator('#log-food-form [type=submit]').click();assert.equal(await page.locator('#log-food-form [type=submit]').isDisabled(),true);await page.locator('#log-food-form').evaluate(form=>{form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))});await page.evaluate(()=>window.v4Lock=false)
  }else await page.locator('#log-food-form [type=submit]').click()
  await page.waitForSelector('#food-search');assert.equal(await page.locator('dialog[open]').getAttribute('data-v4-identity'),'retained')
 }
 assert.equal((await read('foodLogs')).filter(l=>l.date===today&&l.meal==='lunch').length,2);await page.waitForFunction(()=>document.querySelector('[data-meal-subtotal]')?.textContent.includes('2 项'));await shot('continuous');await page.locator('#meal-entry-done').click();await nav('today');await page.waitForFunction(()=>Number(document.querySelector('.calorie-budget')?.dataset.actual)>2200);const liveHtml=await summary();await nav('food');assert.equal(await summary(),liveHtml)
 // Representative failure retry, nested creation, pending close and stale adoption.
 if(width===390&&scale===100&&colorScheme==='light'&&reducedMotion==='no-preference'){
  await page.locator('[data-add-meal=dinner]').click();await page.locator('[data-food=rice]').click();await page.locator('#grams').fill('0');await page.locator('#log-food-form').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await page.waitForSelector('.meal-entry-error:not([hidden])');assert.equal((await read('foodLogs')).length,3);assert.equal(await page.locator('#grams').inputValue(),'0');await page.locator('[data-history-back]').click();
  await page.locator('#create-food-from-picker').click();await page.locator('#food-form [name=name]').fill('连续录入新食物');await page.locator('#food-form [name=calories]').fill('123');await page.locator('#food-form [type=submit]').click();await page.waitForSelector('#food-search');assert.ok((await read('foods')).some(f=>f.name==='连续录入新食物'));await page.locator('#vision-food-from-picker').click();await page.waitForSelector('.food-vision');await page.locator('dialog[open] [data-close]').click();assert.equal((await read('foodLogs')).length,3);
  await page.locator('[data-add-meal=dinner]').click();await page.locator('[data-food=rice]').click();await page.locator('#grams').fill('10');await page.evaluate(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const t=d.transaction('foodLogs','readwrite'),s=t.objectStore('foodLogs');window.v4Lock=true;const keep=()=>{const q=s.count();q.onsuccess=()=>{if(window.v4Lock)keep()}};keep();t.oncomplete=()=>d.close()});await page.locator('#log-food-form [type=submit]').click();await page.locator('dialog[open] [data-close]').click();await page.evaluate(()=>window.v4Lock=false);await page.waitForFunction(async()=>{const d=await new Promise(r=>{const q=indexedDB.open('fitlog-lite-db');q.onsuccess=()=>r(q.result)});const n=await new Promise(r=>{const q=d.transaction('foodLogs').objectStore('foodLogs').count();q.onsuccess=()=>r(q.result)});d.close();return n===4});assert.equal(await page.locator('dialog[open]').count(),0);const saved=await read('foodLogs');await write({foodLogs:saved.filter(l=>l.meal!=='dinner')});await nav('today');await nav('food');
 }
 // Close an unsaved quantity; reopen remains factual, history capture survives own date rail.
 await page.locator('[data-add-meal=dinner]').click();await page.locator('[data-food=rice]').click();await page.locator('#grams').fill('42');await page.locator('dialog[open] [data-close]').click();assert.equal((await read('foodLogs')).length,3);await page.locator(`.food-date-item[data-food-date="${past}"]`).click();await page.waitForFunction(date=>document.querySelector('.food-content-body')?.dataset.foodDate===date,past);await page.locator('[data-add-meal=dinner]').click();await page.locator('[data-food=rice]').click();await page.locator('#grams').fill('42.125');await page.locator('#log-food-form [type=submit]').click();await page.waitForSelector('#food-search');assert.equal((await read('foodLogs')).find(l=>l.date===past)?.grams,42.125);await page.locator('#meal-entry-done').click();await page.locator('#food-return-today').click()
 // Preview a single strict food, then two. No preview writes, partial cannot claim perfection.
 await write({foodLogs:[],nutritionTargets:[{...target,calories:600,protein:100,carbs:150,fat:20}]});await nav('today');await nav('food');await page.waitForSelector('#food-completion-custom');const count=(await read('foodLogs')).length;await page.locator('#food-completion-custom').click();await page.locator('[data-designated-food=chicken]').check();await page.locator('#completion-calculate').click();await page.waitForSelector('[data-plan-food]');assert.ok((await page.locator('[data-plan-food]').evaluateAll(es=>es.map(e=>e.dataset.planFood))).every(id=>id==='chicken'));assert.ok((await page.locator('[data-completion-results]').innerText()).includes('部分目标仍有差距'));assert.equal((await read('foodLogs')).length,count)
 await page.locator('[data-designated-food=rice]').check();await page.locator('#completion-calculate').click();await page.waitForSelector('[data-plan-food]');assert.ok((await page.locator('[data-plan-food]').evaluateAll(es=>es.map(e=>e.dataset.planFood))).every(id=>['chicken','rice'].includes(id)));await shot('designated');await bounds('dialog[open]');await page.locator('[data-completion-mode=smart]').click();await page.locator('[data-completion-mode=designated]').click();assert.equal(await page.locator('[data-designated-food=chicken]').isChecked(),true);assert.equal(await page.locator('[data-designated-food=rice]').isChecked(),true);await page.locator('#completion-calculate').click();await page.waitForSelector('[data-completion-adopt]');await page.locator('[data-completion-adopt]').first().click();await page.locator('[data-completion-meal=lunch]').first().click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.ok((await read('foodLogs')).length>0)
 if(width===390&&scale===100&&colorScheme==='light'&&reducedMotion==='no-preference'){
  await write({foodLogs:[],nutritionTargets:[{...target,calories:600,protein:100,carbs:150,fat:20}]});await nav('today');await nav('food');await page.locator('#food-completion-custom').click();await page.locator('[data-designated-food=rice]').check();await page.locator('#completion-calculate').click();await page.waitForSelector('[data-completion-adopt]');const beforeStale=(await read('foodLogs')).length;await write({nutritionTargets:[{...target,calories:999}]});await page.locator('[data-completion-adopt]').first().click();await page.locator('[data-completion-meal=lunch]').first().click();await page.waitForFunction(()=>document.querySelector('[data-completion-status]')?.textContent.includes('数据已变化'));assert.equal((await read('foodLogs')).length,beforeStale);await page.locator('dialog[open] [data-close]').click();
 }
 // Unknown candidate/no feasible combination and future-date previews never write.
 await write({foodLogs:[],nutritionTargets:[{...target,calories:0,protein:100,carbs:100,fat:0}]});await nav('today');await nav('food');await page.locator('#food-completion-custom').click();const candidate=await page.locator('[data-designated-food=unknown]').elementHandle();await page.locator('[data-designated-food=unknown]').check();assert.equal(await candidate.evaluate(e=>e.isConnected&&e.checked),true);assert.equal(await page.locator('dialog[open]').count(),1);await page.locator('#completion-calculate').click();await page.waitForFunction(()=>document.querySelector('[data-completion-results]')?.textContent.includes('未参与计算'));assert.equal(await page.locator('[data-plan-food]').count(),0);assert.equal((await read('foodLogs')).length,0);await page.locator('[data-designated-food=unknown]').uncheck();await page.locator('[data-designated-food=oil]').check();await page.locator('#completion-calculate').click();await page.waitForFunction(()=>document.querySelector('[data-completion-results]')?.textContent.includes('暂不能改善'));assert.equal(await page.locator('[data-completion-adopt]').count(),0);await page.locator('dialog[open] [data-close]').click();
 const future=await page.evaluate(today=>{const d=new Date(today+'T12:00:00');d.setDate(d.getDate()+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},today);await write({nutritionTargets:[{...target,date:future}]});await page.locator(`.food-date-item[data-food-date="${future}"]`).click();await page.waitForFunction(date=>document.querySelector('.food-content-body')?.dataset.foodDate===date,future);await page.locator('#food-completion-open').click();await page.waitForSelector('.completion-future');assert.equal(await page.locator('[data-completion-adopt]').count(),0);assert.equal((await read('foodLogs')).length,0);await page.locator('dialog[open] [data-close]').click();await page.locator('#food-return-today').click();
 // Shared goal states and unknown dimensions, not zeros; no weight -> no ratio.
 for(const[actual,goal,state]of[[1250,2000,'below'],[2000,2000,'reached'],[2456,2000,'above'],[2456,undefined,'unset']]){await write({foodLogs:[{...logs[0],totalCalories:actual}],nutritionTargets:goal===undefined?[]:[{...target,calories:goal}]});await nav('today');await page.waitForFunction(actual=>Number(document.querySelector('.calorie-budget')?.dataset.actual)===actual,actual);assert.ok(await page.locator('.calorie-budget').evaluate((e,state)=>e.classList.contains(state),state));assert.equal(await page.locator('.budget-number strong').innerText(),String(actual));if(goal===undefined)assert.ok(!(await page.locator('.budget-meta').innerText()).includes('%'));await nav('food');await bounds('.food-content-body')}
 await write({foodLogs:[{...logs[0],totalFat:undefined}],weights:[],nutritionTargets:[target]});await nav('today');await nav('food');await page.waitForFunction(()=>document.querySelector('.fat .macro-value')?.textContent==='数据不完整');assert.equal(await page.locator('.macro-per-kg').count(),0);await bounds('.food-content-body')
 // Task toggles use the exact same saved entity across Today/Plan.
 await nav('today');assert.ok((await page.locator('.today-plan-summary').innerText()).includes('已完成 0 / 1'));await page.locator('[data-task-complete=v4-task]').click();await page.waitForFunction(()=>document.querySelector('.today-plan-summary')?.textContent.includes('已完成 1 / 1'));await nav('plan');await page.waitForSelector('#plan-completed');await page.locator('#plan-completed summary').click();assert.equal(await page.locator('[data-task-complete=v4-task]').getAttribute('aria-pressed'),'true');await page.locator('[data-task-complete=v4-task]').click();await nav('today');assert.equal(await page.locator('[data-task-complete=v4-task]').getAttribute('aria-pressed'),'false');await nav('plan');await shot('plan');await bounds('.plan-page')
 await nav('today');const actions=await page.locator('#today-workout,#today-record-weight,#today-pelvic').evaluateAll(es=>es.map(e=>({r:e.getBoundingClientRect().right,h:e.getBoundingClientRect().height,radius:getComputedStyle(e).borderRadius,background:getComputedStyle(e).backgroundColor})));assert.ok(Math.max(...actions.map(a=>a.r))-Math.min(...actions.map(a=>a.r))<=2);assert.equal(new Set(actions.map(a=>a.radius)).size,1);assert.equal(new Set(actions.map(a=>a.background)).size,1)
 // Four factual report cards have identical dimensions and shared same-row bar baseline.
 await nav('progress');await page.locator('[data-progress-view=reports]').click();await page.waitForSelector('.coach-report');await page.locator('[data-report-mode=day]').click();await page.waitForSelector('.coach-nutrition');const geometry=await page.locator('.coach-nutrient').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('.coach-meter').getBoundingClientRect();return{w:r.width,h:r.height,top:r.top,bar:b.top}}));assert.equal(geometry.length,4);assert.ok(Math.max(...geometry.map(g=>g.w))-Math.min(...geometry.map(g=>g.w))<=1);assert.ok(Math.max(...geometry.map(g=>g.h))-Math.min(...geometry.map(g=>g.h))<=1);for(const g of geometry)for(const h of geometry)if(Math.abs(g.top-h.top)<1)assert.ok(Math.abs(g.bar-h.bar)<=2);await bounds('.coach-report');await shot('report');assert.deepEqual(errors,[])
 receipts.push({width,scale,colorScheme,reducedMotion,continuousTwoFoods:true,doubleSubmitGuard:true,historyExactPrecision:true,strictCandidates:true,previewNoWrites:true,sharedSnapshot:true,states:true,unknownNotZero:true,taskSync:true,actionGeometry:actions,reportGeometry:geometry,noOverflow:true,errors,physicalIPhone:'Pending'});console.log(prefix+' PASS')
 }catch(error){console.log('FAILURE_TOUCH_TRACE',JSON.stringify(await page.evaluate(()=>window.v4TouchTrace)));await shot('failure').catch(()=>{});throw error}finally{await ctx.close()}
}
await browser.close();await fs.writeFile(path.join(dir,'receipt'+(process.env.FITLOG_V4_WIDTH?'-'+process.env.FITLOG_V4_WIDTH:'')+'.json'),JSON.stringify(receipts,null,2))
