// Real app/tool boundary; synthetic credentials and mocked YouTube / official player only.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const {chromium}=await import(process.env.FITLOG_PLAYWRIGHT_MODULE)
const base=process.env.FITLOG_QA_URL||'http://127.0.0.1:5175/fitlog-lite/',prod=base.includes('github.io')
const sizes=prod?[[390,844],[430,932]]:[[320,812],[375,812],[390,844],[430,932]],receipts=[]
const browser=await chromium.launch({headless:true,executablePath:process.env.FITLOG_CHROME})
try{for(const [width,height] of sizes){const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,serviceWorkers:'block',timezoneId:'Asia/Shanghai'})
try{
await context.addInitScript(()=>{const p={id:'video-test',name:'合成 AI 服务',protocol:'openai-chat-completions',baseUrl:'https://mock-video-ai.invalid/v1',model:'chat-model',visionModel:'image-model',toolCapability:'supported',visionCapability:'supported',createdAt:'',updatedAt:''};localStorage.setItem('fitlog-ai-profiles-v1',JSON.stringify([p]));localStorage.setItem('fitlog-ai-active-profile-v1',p.id);localStorage.setItem('fitlog-ai-key-v1:'+p.id,'synthetic-ai-secret');localStorage.setItem('fitlog-ai-privacy-ack-v1','1')})
const page=await context.newPage(),errors=[],states=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message))
let count=3,fail=false,searches=0,modelCalls=0,holdSearch=false,releaseSearch
await page.route('https://mock-video-ai.invalid/**',async route=>{const body=route.request().postDataJSON();modelCalls++;assert.ok(!JSON.stringify(body).includes('synthetic-video-key'));assert.ok(!JSON.stringify(body).includes('synthetic-ai-secret'));const last=body.messages.at(-1);const call={id:'same-'+modelCalls,type:'function',function:{name:'search_training_videos',arguments:JSON.stringify({query:'cable face pull exercise tutorial',limit:count})}};await route.fulfill({json:{choices:[{message:last.role==='tool'?{content:'找到以下真实搜索结果。'}:{content:null,tool_calls:[call,{...call}]}}]}})})
await page.route('https://www.googleapis.com/youtube/v3/search?**',async route=>{searches++;const request=route.request();if(request.method()==='OPTIONS'){await route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'x-goog-api-key','Access-Control-Allow-Methods':'GET'}});return}assert.equal(request.headers()['x-goog-api-key'],'synthetic-video-key');assert.ok(!request.url().includes('synthetic-video-key'));if(holdSearch){await new Promise(resolve=>releaseSearch=resolve);try{await route.fulfill({json:{items:[]}})}catch{}return}await route.fulfill(fail?{status:403,body:'raw synthetic-video-key'}:{json:{items:Array.from({length:count},(_,i)=>({id:{videoId:'Abcdefghij'+(i+1)},snippet:{title:i===0?'绳索面拉正确动作教学这是一个较长的中文标题用于验证小屏阅读与换行'.repeat(3):'CableFacePullLongEnglishTutorialCorrectTechniqueAndShoulderForm'.repeat(3),channelTitle:'YouTube 教学频道 LongTrainingChannel',thumbnails:{default:{url:'https://evil.invalid'}}}}))}})})
await page.route('https://i.ytimg.com/**',route=>route.abort())
await page.route('https://www.youtube.com/iframe_api',route=>route.fulfill({contentType:'application/javascript',body:`window.YT={Player:class{constructor(frame,options){this.frame=frame;window.mockVideoPlayers=(window.mockVideoPlayers||0)+1;const hold=window.mockHoldNextPlayer,fail=window.mockFailNextPlayer;window.mockHoldNextPlayer=window.mockFailNextPlayer=false;if(!hold)setTimeout(()=>options.events[fail?'onError':'onReady'](),60)}destroy(){this.frame.remove();window.mockVideoPlayers--}}};window.onYouTubeIframeAPIReady?.();`}))
await page.route('https://www.youtube-nocookie.com/embed/**',route=>route.fulfill({contentType:'text/html',body:'<html><body style="background:#202824;color:white">Synthetic official player surface</body></html>'}))
await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('#open-ai-assistant');await page.addStyleTag({content:':root{--safe-area-top:47px;--safe-area-bottom:34px}'})
const close=async()=>{await page.locator('dialog[open] [data-close]').click()}
const send=async()=>{await page.locator('#ai-message-input').fill('给我找绳索面拉教学视频');await page.locator('#ai-send').click();await page.waitForFunction(()=>document.querySelector('#ai-send')&&!document.querySelector('#ai-send').hidden)}
const audit=async(name,scale)=>{await page.waitForTimeout(230);const failures=await page.evaluate(()=>{const root=document.querySelector('dialog[open]')||document.querySelector('#view'),r=root.getBoundingClientRect(),out=[];if(document.documentElement.scrollWidth>innerWidth+1)out.push('root');for(const e of root.querySelectorAll('*')){const b=e.getBoundingClientRect(),s=getComputedStyle(e);if(!b.width||!b.height||e.closest('[hidden]')||e instanceof SVGElement)continue;if(b.left<r.left-1||b.right>r.right+1)out.push('bounds '+e.className);if(e.matches('button,a')&&(b.height<43.5||b.width<43.5||e.scrollWidth>e.clientWidth+1))out.push('control '+(e.id||e.className));if(e.matches('input:not([type=checkbox]),textarea')&&parseFloat(s.fontSize)<16)out.push('font '+e.name)}return [...new Set(out)]});await page.screenshot({path:`/tmp/video-search-${prod?'prod':'local'}-${width}-${scale}-${name}.png`});assert.deepEqual(failures,[],`${width}/${scale}/${name}`);assert.ok(!(await page.locator('body').innerText()).includes('synthetic-video-key'));states.push({name,scale})}
await page.locator('#open-ai-assistant').click();await send();assert.equal(searches,0);assert.ok((await page.locator('.ai-conversation').innerText()).includes('训练视频搜索尚未配置'));await audit('not-configured',100);await page.locator('#ai-assistant-settings').click();await page.locator('#ai-video-search').click();assert.equal(await page.locator('[data-provider-section="youtube"]').isVisible(),false);assert.equal(await page.locator('[data-policy-section]').isVisible(),false);await audit('settings',100);await page.locator('[name=videoKey]').fill('synthetic-video-key');await page.locator('#video-save-only').click();assert.equal(await page.locator('[name=videoKey]').inputValue(),'');assert.equal(await page.locator('[data-provider-section="youtube"]').isVisible(),true);await close();await page.locator('#open-ai-assistant').click();await page.locator('#ai-clear-chat').click();await send();assert.equal(searches,0);assert.ok((await page.locator('.ai-conversation').innerText()).includes('隐私说明'));await close();await page.locator('#open-management').click();await page.locator('#more-ai-settings').click();await page.locator('#ai-video-search').click();await page.locator('[name=videoConsent]').check();await page.locator('form button[type=submit]').click();await page.waitForFunction(()=>/视频搜索可用|部分来源可用|测试失败/.test(document.querySelector('.video-config-status')?.textContent));assert.match(await page.locator('.video-config-status').innerText(),/视频搜索可用|测试成功/);await audit('configured',100);await close()
for(const scale of [100,120,140]){await page.evaluate(scale=>document.documentElement.style.fontSize=16*scale/100+'px',scale);await page.locator('#open-ai-assistant').click();await page.locator('#ai-clear-chat').click();count=1;let n=searches;await send();assert.equal(searches,n+1);assert.equal(await page.locator('.video-card').count(),1);assert.equal(await page.locator('.video-card iframe').count(),0);await audit('one-result',scale);await page.locator('#ai-clear-chat').click();count=3;n=searches;await send();assert.equal(searches,n+1);assert.equal(await page.locator('.video-card').count(),3);await page.locator('.video-card').nth(2).locator('.video-media').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelectorAll('.thumbnail-missing').length===3);assert.equal(await page.locator('.thumbnail-missing').count(),3);await page.locator('.ai-conversation').evaluate(e=>e.scrollTop=0);await audit('three-long-titles',scale);for(let i=0;i<3;i++)await page.locator('.video-card').nth(i).screenshot({path:`/tmp/video-search-${prod?'prod':'local'}-${width}-${scale}-card-${i+1}.png`});await page.locator('.ai-conversation').evaluate(e=>e.scrollTop=0)
const external=page.locator('.video-actions a').first();assert.equal(await external.getAttribute('href'),'https://www.youtube.com/watch?v=Abcdefghij1');assert.equal(await external.getAttribute('rel'),'noopener noreferrer');await page.locator('.video-actions button').first().click();await page.waitForFunction(()=>window.mockVideoPlayers===1);assert.equal(await page.locator('.video-card iframe').count(),1);const iframe=page.locator('.video-card iframe');const url=new URL(await iframe.getAttribute('src'));assert.equal(url.hostname,'www.youtube-nocookie.com');assert.equal(url.searchParams.get('autoplay'),'0');assert.equal(url.searchParams.get('playsinline'),'1');assert.equal(await iframe.getAttribute('referrerpolicy'),'strict-origin-when-cross-origin');const bounds=await iframe.boundingBox();assert.ok(bounds.width>=200&&bounds.height>=200);await audit('playing',scale);await page.locator('.video-actions button').nth(1).click();assert.equal(await page.locator('.video-card iframe').count(),1);assert.ok((await page.locator('.video-card iframe').getAttribute('src')).includes('Abcdefghij2'));await audit('switching',scale);
await page.evaluate(()=>window.mockFailNextPlayer=true);await page.locator('.video-actions button').nth(2).click();await page.waitForFunction(()=>document.querySelectorAll('.video-card iframe').length===0&&[...document.querySelectorAll('.video-status')].some(e=>e.textContent.includes('暂时无法')));assert.equal(await page.locator('.video-actions a').count(),3);await audit('player-error-fallback',scale);
await page.clock.install();await page.evaluate(()=>window.mockHoldNextPlayer=true);await page.locator('.video-actions button').first().click();await page.waitForFunction(()=>window.mockVideoPlayers===1);await page.clock.fastForward(16000);assert.equal(await page.locator('.video-card iframe').count(),0);assert.ok((await page.locator('.video-status').first().innerText()).includes('暂时无法'));await audit('player-timeout-fallback',scale);await close();assert.equal(await page.locator('iframe').count(),0);n=searches;await page.locator('#open-ai-assistant').click();assert.equal(searches,n);assert.equal(await page.locator('.video-card').count(),3);assert.equal(await page.locator('iframe').count(),0);await audit('reopen',scale);await page.locator('#ai-clear-chat').click();assert.equal(await page.locator('.video-card').count(),0);fail=true;await send();assert.ok((await page.locator('.ai-conversation').innerText()).includes('未获授权'));assert.ok(!(await page.locator('.ai-conversation').innerText()).includes('raw'));await audit('provider-error',scale);fail=false;
if(scale===100){for(const action of ['stop','close']){await page.locator('#ai-clear-chat').click();holdSearch=true;releaseSearch=undefined;await page.locator('#ai-message-input').fill('找绳索面拉视频');await page.locator('#ai-send').click();await page.waitForFunction(()=>!document.querySelector('#ai-stop').hidden);while(!releaseSearch)await page.waitForTimeout(10);if(action==='stop')await page.locator('#ai-stop').click();else await close();releaseSearch();holdSearch=false;if(action==='close')await page.locator('#open-ai-assistant').click();await page.waitForFunction(()=>document.querySelector('#ai-send')&&!document.querySelector('#ai-send').hidden);assert.equal(await page.locator('.video-card').count(),0);await audit('search-'+action+'-aborted',scale)}}await close()}
assert.deepEqual(errors,[]);receipts.push({width,height,states:states.length,searches,modelCalls,duplicateCallOnce:true,keyExcluded:true,singleClickLoadedPlayer:true,closeDestroy:true,reopenNoSearch:true,playerErrorAndTimeoutFallback:true,pendingSearchStopAndClose:true,realProvider:'Not performed',physicalIPhone:'Pending'});console.log(JSON.stringify(receipts.at(-1)))
}finally{await context.close()}}
await fs.writeFile(`/tmp/video-search-${prod?'prod':'local'}-receipt.json`,JSON.stringify(receipts,null,2))
}finally{await browser.close()}
