import {afterEach,describe,it,expect,vi} from 'vitest'
import {aiEnvironment,aiFood,aiCall} from './helpers/ai'
import {logFood} from '../src/services/foodService'
import {AiOrchestrator} from '../src/ai/orchestrator'
import {AiProfiles} from '../src/services/aiProfiles'
import {aiProposalPreviewLines} from '../src/ui/aiUiHelpers'
const environments:ReturnType<typeof aiEnvironment>[]=[]
const setup=()=>{const e=aiEnvironment();environments.push(e);return e}
afterEach(async()=>{vi.restoreAllMocks();for(const e of environments.splice(0)){e.database.close();await e.database.delete()}})
const food={action:'create',name:'燕麦',referenceGrams:100,calories:389,protein:16.9,carbs:66.3,fat:6.9}
const workout={action:'create',name:'双动作',newExercises:[{key:'a',name:'动作A',notes:'动作备注需预览'},{key:'b',name:'动作B'}],exercises:[{exerciseRef:'a',sets:[{reps:10,weightKg:20,rpe:7,note:'第一组'},{reps:8}]},{exerciseRef:'b',sets:[{reps:12}]}]}
async function commit(e:ReturnType<typeof setup>,tool:string,args:unknown){const p=await e.execute(tool,args);expect(p.error).toBeUndefined();const done=await e.proposals.confirm(p.proposalId);expect(done.status).toBe('completed');return done}
describe('catalog proposal service boundary',()=>{
 it('Food preview is memory-only, cancel leaves DB unchanged',async()=>{const e=setup(),before=await e.database.foods.toArray(),p=await e.execute('propose_food',food);expect(p.preview.summary.join()).toContain('新建食物');expect(await e.database.foods.toArray()).toEqual(before);e.proposals.cancel(p.proposalId);expect((await e.proposals.confirm(p.proposalId)).status).toBe('cancelled');expect(await e.database.foods.toArray()).toEqual(before)})
 it('Food confirms real canonical data once with no invented missing macros',async()=>{const e=setup(),p=await e.execute('propose_food',{action:'create',name:'未知宏量',referenceGrams:100,calories:317});await Promise.all([e.proposals.confirm(p.proposalId),e.proposals.confirm(p.proposalId)]);const row=await e.database.foods.toCollection().first();expect(await e.database.foods.count()).toBe(1);expect(row).toMatchObject({calories:317,referenceGrams:100});expect(row?.protein).toBeUndefined()})
 it('Food partial edit preserves serving/macros/brand and immutable FoodLog snapshots',async()=>{const e=setup(),f=aiFood('existing',{brand:'品牌',servingGrams:42});await e.database.foods.add(f);await logFood(f,123,'2026-10-02','lunch',e.database);const logs=await e.database.foodLogs.toArray();await commit(e,'propose_food',{action:'update',id:f.id,calories:330});expect(await e.database.foods.get(f.id)).toMatchObject({...f,calories:330,updatedAt:expect.any(String)});expect(await e.database.foodLogs.toArray()).toEqual(logs)})
 it('Food missing key values rejects without a proposal',async()=>{const e=setup();for(const args of [{action:'create',name:'缺少营养'},{...food,calories:undefined}]){expect((await e.execute('propose_food',args)).error).toBeTruthy()}expect(e.proposals.all).toHaveLength(0)})
 it('duplicate normalized names and ambiguous update IDs require clarification',async()=>{const e=setup();await e.database.foods.add(aiFood('o',{name:'燕麦'}));expect((await e.execute('propose_food',food)).error).toBe('catalog_validation');expect((await e.execute('propose_food',{action:'update',name:'燕麦',calories:123})).error).toBe('catalog_validation')})
 it('explicit Food ID disambiguates legacy same-name brands without blocking a partial edit',async()=>{const e=setup(),a=aiFood('a',{name:'燕麦',brand:'A'}),b=aiFood('b',{name:'燕麦',brand:'B'});await e.database.foods.bulkAdd([a,b]);await commit(e,'propose_food',{action:'update',id:'b',calories:389});expect(await e.database.foods.get('a')).toEqual(a);expect(await e.database.foods.get('b')).toMatchObject({...b,calories:389,updatedAt:expect.any(String)});expect((await e.execute('propose_food',food)).error).toBe('catalog_validation')})
 it('Exercise create/update uses service and retains unspecified notes',async()=>{const e=setup();await commit(e,'propose_exercise',{action:'create',name:'新动作',notes:'备注'});const row=(await e.database.exercises.where('name').equals('新动作').first())!;await commit(e,'propose_exercise',{action:'update',id:row.id,name:'动作新名称'});expect(await e.database.exercises.get(row.id)).toMatchObject({name:'动作新名称',notes:'备注'});expect((await e.execute('propose_exercise',{action:'create',name:'动作新名称'})).error).toBe('catalog_validation')})
 it('Workout plus two new Exercises commits in one confirmation and one onCommitted event',async()=>{const e=setup(),onCommitted=vi.fn();e.proposals.onCommitted=onCommitted;const p=await e.execute('propose_workout_template',workout);expect(p.preview.writeCount).toBe(3);expect(p.preview.details.join()).toContain('动作备注需预览');expect(await e.database.workoutTemplates.count()).toBe(0);await Promise.all([e.proposals.confirm(p.proposalId),e.proposals.confirm(p.proposalId)]);expect(onCommitted).toHaveBeenCalledOnce();const t=(await e.database.workoutTemplates.toArray())[0]!;expect(t.exercises.map(x=>x.exerciseName)).toEqual(['动作A','动作B']);for(const x of t.exercises)expect(await e.database.exercises.get(x.exerciseId!)).toBeTruthy()})
 it('Workout nested edit changes one set field and preserves all other actions/sets',async()=>{const e=setup();await commit(e,'propose_workout_template',workout);const t=(await e.database.workoutTemplates.toArray())[0]!,x=t.exercises[0]!,set=x.sets[0]!;await commit(e,'propose_workout_template',{action:'update',id:t.id,exercises:[{id:x.id,sets:[{id:set.id,reps:15}]}]});const saved=(await e.database.workoutTemplates.get(t.id))!;expect(saved.exercises).toEqual([{...x,sets:[{...set,reps:15},x.sets[1]]},t.exercises[1]])})
 it('Workout rejects invented references or stale nested IDs',async()=>{const e=setup();expect((await e.execute('propose_workout_template',{action:'create',name:'伪造',exercises:[{exerciseRef:'not-real',sets:[{reps:5}]}]})).error).toBe('catalog_validation');await commit(e,'propose_workout_template',workout);const t=(await e.database.workoutTemplates.toArray())[0]!;expect((await e.execute('propose_workout_template',{action:'update',id:t.id,exercises:[{id:'invented'}]})).error).toBe('catalog_validation')})
 it('Diet plus new Food commits real source-derived fallback without model fallback',async()=>{const e=setup();await commit(e,'propose_diet_template',{action:'create',name:'早餐',newFoods:[{key:'oats',name:'燕麦',referenceGrams:100,calories:389}],items:[{foodRef:'oats',grams:80}]});const t=(await e.database.dietTemplates.toArray())[0]!,item=t.items[0]!;expect(item.fallback).toMatchObject({calories:389,referenceGrams:100});expect(item.fallback.protein).toBeUndefined();expect(await e.database.foods.get(item.foodId!)).toBeTruthy();expect((await e.execute('propose_diet_template',{action:'update',id:t.id,items:[{id:item.id,fallback:{calories:999}}]})).error).toBe('invalid_arguments')})
 it('Diet partial grams edit retains every other field/item and fallback',async()=>{const e=setup();await e.database.foods.add(aiFood('f'));await commit(e,'propose_diet_template',{action:'create',name:'早餐',description:'原说明',items:[{foodRef:'f',grams:100},{foodRef:'f',grams:50}]});const old=(await e.database.dietTemplates.toArray())[0]!;await commit(e,'propose_diet_template',{action:'update',id:old.id,items:[{id:old.items[0]!.id,grams:120}]});expect((await e.database.dietTemplates.get(old.id))?.items).toEqual([{...old.items[0],grams:120},old.items[1]])})
 it('Nutrition template creates optional independent goals without phase/target writes',async()=>{const e=setup();await commit(e,'propose_nutrition_strategy',{action:'create',name:'营养模板',variants:[{name:'高碳日',carbs:300},{name:'休息日',calories:1800}]});const variants=await e.database.nutritionStrategyVariants.toArray();expect(variants.find(v=>v.name==='高碳日')?.calories).toBeUndefined();expect(await e.database.nutritionStrategyPhases.count()).toBe(0);expect(await e.database.nutritionTargets.count()).toBe(0)})
 it('Nutrition template update preserves untouched variants and goals',async()=>{const e=setup();await commit(e,'propose_nutrition_strategy',{action:'create',name:'营养',variants:[{name:'A',protein:100,calories:2000},{name:'B',carbs:200}]});const t=(await e.database.nutritionStrategyTemplates.toArray())[0]!,old=(await e.database.nutritionStrategyVariants.toArray()).sort((a,b)=>a.sortOrder-b.sortOrder);await commit(e,'propose_nutrition_strategy',{action:'update',id:t.id,variants:[{id:old[0]!.id,protein:150}]});const rows=(await e.database.nutritionStrategyVariants.toArray()).sort((a,b)=>a.sortOrder-b.sortOrder);expect(rows[0]).toMatchObject({...old[0],protein:150,updatedAt:expect.any(String)});expect(rows[1]).toMatchObject({...old[1],updatedAt:expect.any(String)})})
 it('composite write failure rolls back previously created Exercises',async()=>{const e=setup(),p=await e.execute('propose_workout_template',workout),before=await e.database.exercises.toArray();vi.spyOn(e.database.workoutTemplates,'put').mockRejectedValueOnce(new Error('disk full'));expect((await e.proposals.confirm(p.proposalId)).status).toBe('expired');expect(await e.database.exercises.toArray()).toEqual(before);expect(await e.database.workoutTemplates.count()).toBe(0)})
 it('composite Diet failure rolls back new Foods',async()=>{const e=setup(),p=await e.execute('propose_diet_template',{action:'create',name:'早餐',newFoods:[{key:'o',name:'燕麦',referenceGrams:100,calories:389}],items:[{foodRef:'o',grams:80}]});vi.spyOn(e.database.dietTemplates,'put').mockRejectedValueOnce(new Error('disk full'));expect((await e.proposals.confirm(p.proposalId)).status).toBe('expired');expect(await e.database.foods.count()).toBe(0)})
 it('rechecks source inside final transaction and refuses stale replacement',async()=>{const e=setup();await e.database.foods.add(aiFood('f'));const p=await e.execute('propose_food',{action:'update',id:'f',name:'修改名'});await e.database.foods.update('f',{calories:999});const result=await e.proposals.confirm(p.proposalId);expect(result.message).toBe('数据已变化，请重新生成建议。');expect((await e.database.foods.get('f'))?.calories).toBe(999)})
 it('permissions checked for definitions, execution, catalog reads and confirmation',async()=>{const e=setup(),p=await e.execute('propose_food',food);e.permissions.writeProposals=false;expect((await e.execute('propose_food',food)).error).toBe('permission_denied');expect(e.registry.definitions().some(t=>t.function.name==='propose_food')).toBe(false);expect((await e.proposals.confirm(p.proposalId)).status).toBe('expired');e.permissions.read.training=false;expect((await e.execute('search_catalog',{kind:'exercise',query:''})).error).toBe('permission_denied')})
 it('unsupported model cannot run unsolicited catalog tool calls',async()=>{const e=setup(),values=new Map<string,string>(),storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v)},removeItem:(k:string)=>{values.delete(k)}};const profiles=new AiProfiles(storage),profile=profiles.save({name:'A',baseUrl:'https://mock.invalid/v1',model:'a'},'synthetic-key');profiles.acknowledgePrivacy();profiles.setCapability(profile.id,'unsupported');const chat=vi.fn().mockResolvedValue({content:'',toolCalls:[aiCall('propose_food',food)]});const engine=new AiOrchestrator({profiles,database:e.database,context:()=>e.context,clientFactory:()=>({chat,chatStream:chat}) as never});await engine.send('建燕麦');expect(chat.mock.calls[0]![0].tools).toBeUndefined();expect(engine.proposals.all).toHaveLength(0);expect(await e.database.foods.count()).toBe(0)})
 it('catalog read is bounded and human preview separates summary and details without JSON',async()=>{const e=setup();await e.database.foods.bulkAdd(Array.from({length:15},(_,i)=>aiFood('f'+i)));const result=await e.execute('search_catalog',{kind:'food',query:'',limit:2});expect(result.items).toHaveLength(2);expect(result.truncated).toBe(true);const p=await e.execute('propose_food',food);expect(aiProposalPreviewLines(e.proposals.get(p.proposalId)!)).toEqual(p.preview.summary);expect(p.preview.details.join()).toContain('热量 kcal：389');expect(p.preview.details.join()).not.toContain('"name":')})
})
