import 'fake-indexeddb/auto'
import { afterEach, describe, expect, it } from 'vitest'
import { FitLogDatabase } from '../src/db/database'
import { restoreBackup, exportBackup } from '../src/services/backupService'
import { readDailyRecords, readDailyRecordsRange, readRecoveryRecords } from '../src/services/dailyRecordsSummary'
import { clearDayRecords } from '../src/services/dayRecordsService'
import { loadReport } from '../src/services/reportService'
import { calendarCategories, getCalendarRecordCategories, loadMonthSummaries } from '../src/ui/calendarPage'
import { dailyRecordsHtml } from '../src/ui/dayDetail'
import { recoveryRangeSummary } from '../src/utils/recovery'
import { recoveryLineGeometry, recoveryLineChartHtml } from '../src/ui/recoveryLineChart'
import { getReportRange, shiftReportPeriod } from '../src/utils/reporting'
import fixture from './fixtures/legacyV11Data.json'
const databases:FitLogDatabase[]=[]
const date='2026-09-28',stamp='2026-09-28T08:00:00Z'
async function make(){const d=new FitLogDatabase('daily-'+crypto.randomUUID());databases.push(d);await restoreBackup({app:'FitLog Lite',schemaVersion:11,exportedAt:stamp,data:fixture},d);return d}
afterEach(async()=>{for(const d of databases.splice(0)){d.close();await d.delete()}})
const esc=(v:unknown)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')
describe('bounded shared daily facts',()=>{
 it('reads all 42 visible dates including adjacent months without rewriting saved snapshots',async()=>{const d=await make();await d.waterLogs.put({id:'adjacent',date:'2026-08-31',amountMl:250,timestamp:stamp,createdAt:stamp,updatedAt:stamp});const before=(await exportBackup(d)).data;const map=await loadMonthSummaries(2026,8,d);expect(map.size).toBe(42);expect(map.get('2026-08-31')?.waterMl).toBe(250);expect(map.get('2026-09-28')?.calories).toBe(100);expect(map.get('2026-09-28')?.carbs).toBeUndefined();expect((await exportBackup(d)).data).toEqual(before)})
 it('nine actual categories include inactive historical check-ins and completed wake-date sleep',async()=>{const d=await make();await d.habits.update('habit-old',{active:false});await d.sleepSessions.update('sleep-completed',{recordDate:date});await d.waterLogs.update('water-frozen',{date});const r=await readDailyRecords(date,d);expect(getCalendarRecordCategories(r.summary)).toEqual(calendarCategories);expect(r.summary).toMatchObject({habitCount:1,sleepCount:1,sleepMinutes:456,waterCount:1,waterMl:350});expect(r.source.sleepSessions.some(s=>s.activeKey)).toBe(false);expect(r.source.habits[0]?.active).toBe(false)})
 it('complete detail uses saved names, unknown macros, all sets, RPE, optional load and escaped notes',async()=>{const d=await make();await d.workouts.update('workout-old',{note:'<script>unsafe</script>'});const r=await readDailyRecords(date,d),html=dailyRecordsHtml(r,esc);expect(html.match(/data-record-category=/g)).toHaveLength(9);for(const text of ['Historical food snapshot','Historical exercise snapshot','RPE 7','重量未记录','碳水 未知','脂肪 未知','Legacy habit','1 次训练','10 次收缩','&lt;script>unsafe&lt;/script>'])expect(html).toContain(text);expect(html).not.toContain('PRIVATE_TEST_FOOD_123');expect(html).not.toContain('Edited current library exercise')})
 it('sums multiple episodes and water records, excludes active sessions, preserves missing dates',async()=>{const d=await make();await d.sleepSessions.update('sleep-completed',{recordDate:date});await d.sleepSessions.put({id:'nap',startTime:'2026-09-28T05:00:00Z',endTime:'2026-09-28T06:00:00Z',durationMinutes:60,recordDate:date,createdAt:stamp,updatedAt:stamp});await d.waterLogs.bulkPut([250,500,250].map((amountMl,i)=>({id:'w'+i,date,amountMl,timestamp:stamp,createdAt:stamp,updatedAt:stamp})));const r=await readDailyRecords(date,d);expect(r.summary).toMatchObject({sleepMinutes:516,sleepCount:2,waterMl:1000,waterCount:3});expect((await readDailyRecords('2026-09-27',d)).summary.waterMl).toBeUndefined();const range=await readRecoveryRecords(date,date,d);expect(range.sleep).toHaveLength(3);expect(range.water).toHaveLength(3)})
 it('clear retains Sleep Water Habit Tasks and removes exactly the existing seven-store domain',async()=>{const d=await make();await d.sleepSessions.update('sleep-completed',{recordDate:date});await d.waterLogs.update('water-frozen',{date});const before=(await exportBackup(d)).data;await clearDayRecords(date,d);const after=(await exportBackup(d)).data;for(const store of ['sleepSessions','waterLogs','habitCheckIns','tasks','foods','workoutTemplates'] as const)expect(after[store]).toEqual(before[store]);expect(getCalendarRecordCategories((await readDailyRecords(date,d)).summary)).toEqual(['habit','sleep','water']);for(const store of ['foodLogs','dietEvents','nutritionTargets','workouts','cardioSessions','pelvicFloorSessions','weights'] as const)expect(after[store].filter(r=>r.date===date)).toHaveLength(0)})
 it('day report and detail have identical facts; month averages count recorded dates only',async()=>{const d=await make();await d.sleepSessions.update('sleep-completed',{recordDate:date});await d.waterLogs.bulkPut([250,500].map((amountMl,i)=>({id:'w'+i,date,amountMl,timestamp:stamp,createdAt:stamp,updatedAt:stamp})));const day=await loadReport('day',date,date,d);expect(day.daily).toEqual(await readDailyRecords(date,d));const month=await loadReport('month',date,date,d);expect(month.recovery).toMatchObject({recordedDays:1,averageMinutes:456,waterRecordedDays:1,waterTotal:750,waterAverage:750});expect(getReportRange('day',date)).toMatchObject({start:date,end:date});expect(shiftReportPeriod('day','2026-09-30',1)).toBe('2026-10-01')})
 it('date ranges remain inclusive across DST and month boundaries',async()=>{const d=await make();expect([...(await readDailyRecordsRange('2026-03-07','2026-03-10',d)).keys()]).toEqual(['2026-03-07','2026-03-08','2026-03-09','2026-03-10']);expect(recoveryRangeSummary([],[],'2026-09-30','2026-10-02').daily.map(p=>p.date)).toEqual(['2026-09-30','2026-10-01','2026-10-02'])})
})
describe('recovery line labels and missing dates',()=>{
 it('splits lines on missing dates and retains isolated zero points',()=>{const points=[{date:'2026-10-01',value:0},{date:'2026-10-02'},{date:'2026-10-03',value:500},{date:'2026-10-04',value:500}];const g=recoveryLineGeometry(points,'water');expect(g.segments.map(s=>s.length)).toEqual([1,2]);const html=recoveryLineChartHtml(points,'water');expect(html.match(/recovery-point-value/g)).toHaveLength(3);expect(html).toContain('>0</text>');expect(html).not.toContain('data-point-value="undefined"')})
 it.each(['sleep','water'] as const)('gives large, equal and close %s numeric labels distinct padded slots',kind=>{const g=recoveryLineGeometry(Array.from({length:90},(_,i)=>({date:'2026-10-01',value:i%2?999999:999998})),kind);for(let i=1;i<g.points.length;i++)expect(g.points[i]!.x-g.points[i-1]!.x).toBeGreaterThanOrEqual(g.points[i]!.label!.length*7.5+7);expect(g.points[0]!.x).toBeGreaterThan(g.spacing/2);expect(g.width-g.points.at(-1)!.x).toBeGreaterThan(g.spacing/2)})
 it('empty range remains empty; no fabricated zero chart',()=>{expect(recoveryLineChartHtml([{date}], 'water')).toContain('暂无饮水记录');expect(recoveryLineChartHtml([{date}],'sleep')).not.toContain('<svg')})
})
