import 'fake-indexeddb/auto'
import {afterEach,describe,it,expect} from 'vitest'
import type {Workout,WorkoutSet,Habit,FoodLog} from '../src/db/types'
import {analyzeExercisePerformance,validRecordedSet} from '../src/utils/exercisePerformanceAnalysis'
import {trainingVolumeAnalysis} from '../src/utils/trainingVolumeAnalysis'
import {analyzeCoachReport} from '../src/utils/coachReportAnalysis'
import {aggregateReport,type ReportSource} from '../src/utils/reporting'
import {loadCoachReport} from '../src/services/coachReportService'
import {FitLogDatabase} from '../src/db/database'
import {nearestTrendPoint} from '../src/ui/trendInteraction'
import {calendarOrdinal,trendPlotHeight} from '../src/ui/trendGeometry'
import {performanceHtml,coachReportHtml,coachPlotHtml} from '../src/ui/coachReport'
import {recoveryLineGeometry,recoveryLineChartHtml} from '../src/ui/recoveryLineChart'
const range={start:'2026-10-05',end:'2026-10-11'},stamp='2026-09-01T08:00:00Z'
const set=(weightKg:number|undefined,reps=8):WorkoutSet=>({id:crypto.randomUUID(),reps,...(weightKg===undefined?{}:{weightKg})})
const workout=(id:string,date:string,sets:WorkoutSet[],exerciseId:string|undefined='bench',name='杠铃卧推'):Workout=>({id,date,startedAt:date+'T08:00:00Z',finishedAt:date+'T09:00:00Z',createdAt:stamp,updatedAt:stamp,exercises:[{id:id+'e',exerciseId,exerciseName:name,sets}]})
const source=():ReportSource=>({foodLogs:[],nutritionTargets:[],workouts:[],cardioSessions:[],pelvicFloorSessions:[],weights:[],habits:[],habitCheckIns:[]})
const analyze=(rows:Workout[])=>analyzeExercisePerformance(rows,range)[0]!
const habit=(patch:Partial<Habit>={}):Habit=>({id:'h',name:'运动',active:true,sortOrder:0,createdAt:stamp,updatedAt:stamp,...patch})
const food=(id:string,date:string,protein:number|undefined,calories=100):FoodLog=>({id,date,foodName:id,grams:100,referenceGrams:100,caloriesPerReference:calories,totalCalories:calories,totalProtein:protein,createdAt:stamp,updatedAt:stamp})
const report=(s:ReportSource,mode:'day'|'week'|'month'='week',anchor='2026-10-09')=>analyzeCoachReport(s,aggregateReport(s,mode,anchor,'2026-10-09'))
const checks=(s:ReportSource,dates:string[])=>{s.habitCheckIns=dates.map(date=>({id:date,habitId:'h',date,createdAt:stamp,updatedAt:stamp,completedAt:stamp}))}
const dbs:FitLogDatabase[]=[]
afterEach(async()=>{for(const d of dbs.splice(0)){d.close();await d.delete()}})
describe('qualified action comparison and complete historical records',()=>{
 it('same8reps60→65 is5kg and8.33%, with a cross-period baseline date',()=>{const g=analyze([workout('prior','2026-09-20',[set(60)]),workout('now','2026-10-09',[set(65)])]);expect(g.status).toBe('improved');expect(g.baseline?.date).toBe('2026-09-20');expect(g.changes[0]).toMatchObject({kind:'weight',condition:8,delta:5});expect(g.changes[0].percentage).toBeCloseTo(8.3333)})
 it('same60kg8→10 is2reps, not a weight growth percentage',()=>{const g=analyze([workout('a','2026-10-05',[set(60,8)]),workout('b','2026-10-09',[set(60,10)])]);expect(g.changes).toEqual([{kind:'reps',condition:60,previous:8,current:10,delta:2}]);expect(g.status).toBe('improved')})
 it('heavier load with fewer repetitions is changed conditions, never growth',()=>{const g=analyze([workout('a','2026-10-05',[set(60,10)]),workout('b','2026-10-09',[set(65,5)])]);expect(g.status).toBe('changed');expect(g.changes).toEqual([]);expect(g.baseline).toBeUndefined()})
 it('chooses best weight per common rep rather than arbitrary first sets',()=>{const g=analyze([workout('a','2026-10-05',[set(50),set(60),set(70,5)]),workout('b','2026-10-09',[set(45),set(65),set(75,5)])]);expect(g.changes.filter(c=>c.kind==='weight').map(c=>c.delta)).toEqual([5,5])})
 it('chooses best rep count per common weight',()=>{const g=analyze([workout('a','2026-10-05',[set(60,5),set(60,8)]),workout('b','2026-10-09',[set(60,6),set(60,10)])]);expect(g.changes).toEqual([{kind:'reps',condition:60,previous:8,current:10,delta:2}])})
 it('does not cherry-pick mixed conditions as overall improvement',()=>{const g=analyze([workout('a','2026-10-05',[set(60,8),set(80,3)]),workout('b','2026-10-09',[set(65,8),set(75,3)])]);expect(g.status).toBe('mixed');expect(g.changes.map(c=>c.delta)).toEqual([5,-5])})
 it('equal weight and reps is stable',()=>{expect(analyze([workout('a','2026-10-05',[set(60)]),workout('b','2026-10-09',[set(60)])]).status).toBe('stable')})
 it('decline remains explicit',()=>{expect(analyze([workout('a','2026-10-05',[set(60)]),workout('b','2026-10-09',[set(55)])]).status).toBe('declined')})
 it('first fact establishes baseline without percentage or new-record claim',()=>{const g=analyze([workout('a','2026-10-09',[set(60)])]);expect(g.status).toBe('first');expect(g.changes).toEqual([]);expect(g.records.every(r=>!r.newRecord)).toBe(true)})
 it('missing external loads remain unknown, never zero-volume',()=>{const g=analyze([workout('a','2026-10-05',[set(undefined)]),workout('b','2026-10-09',[set(undefined)])]);expect(g.status).toBe('no-history');expect(g.current).toMatchObject({recordedSets:1,weightedSets:0});expect(g.current?.volume).toBeUndefined();expect(g.current?.highestWeight).toBeUndefined()})
 it('skips the nearest incompatible session for an earlier comparable one',()=>{const g=analyze([workout('a','2026-09-20',[set(60)]),workout('b','2026-10-05',[set(80,2)]),workout('c','2026-10-09',[set(65)])]);expect(g.baseline?.workoutId).toBe('a');expect(g.changes[0].delta).toBe(5)})
 it('recent improvement below old best is not a historical record',()=>{const g=analyze([workout('old','2026-08-01',[set(75)]),workout('a','2026-10-05',[set(60)]),workout('b','2026-10-09',[set(65)])]);expect(g.status).toBe('improved');expect(g.records.find(r=>r.kind==='load')).toMatchObject({previous:75,newRecord:false});expect(g.records.find(r=>r.kind==='weight')).toMatchObject({previous:75,newRecord:false})})
 it('identifies separately load, same-rep and same-weight true records',()=>{const g=analyze([workout('a','2026-09-20',[set(60,8),set(55,10)]),workout('b','2026-10-09',[set(65,8),set(55,12)])]);expect(g.records.filter(r=>r.newRecord).map(r=>r.kind)).toEqual(['load','weight','reps'])})
 it('ties are not new records',()=>{expect(analyze([workout('a','2026-10-05',[set(60)]),workout('b','2026-10-09',[set(60)])]).records.every(r=>!r.newRecord)).toBe(true)})
 it('different IDs with same name never merge',()=>{const rows=[workout('a','2026-10-05',[set(60)],'one'),workout('b','2026-10-09',[set(65)],'two')];expect(analyzeExercisePerformance(rows,range)).toHaveLength(2);expect(analyzeExercisePerformance(rows,range).every(g=>g.status==='first')).toBe(true)})
 it('unique exact normalized legacy name can compare without changing snapshots',()=>{const a=workout('a','2026-09-20',[set(60)],undefined,'  杠铃卧推 ');delete a.exercises[0].exerciseId;const g=analyze([a,workout('b','2026-10-09',[set(65)])]);expect(g.baseline?.name).toBe('  杠铃卧推 ');expect(g.status).toBe('improved')})
 it('ambiguous legacy names are explicitly unreliable',()=>{const a=workout('old','2026-10-09',[set(60)]);delete a.exercises[0].exerciseId;const gs=analyzeExercisePerformance([workout('a','2026-10-05',[set(60)],'one'),workout('b','2026-10-06',[set(60)],'two'),a],range);expect(gs.find(g=>g.key.startsWith('legacy:'))?.status).toBe('unreliable')})
 it('barbell/dumbbell/Smith/pull-down/pull-up names remain separate',()=>{const rows=['杠铃卧推','哑铃卧推','杠铃深蹲','史密斯深蹲','高位下拉','引体向上'].map((name,i)=>{const w=workout(String(i),'2026-10-09',[set(60)],undefined,name);delete w.exercises[0].exerciseId;return w});expect(analyzeExercisePerformance(rows,range)).toHaveLength(6)})
 it('exerciseId survives a renamed library while historical names stay unchanged',()=>{const g=analyze([workout('a','2026-10-05',[set(60)],'one','旧快照'),workout('b','2026-10-09',[set(65)],'one','新名称')]);expect(g.history.map(s=>s.name)).toEqual(['旧快照','新名称']);expect(g.status).toBe('improved')})
 it('unfinished and invalid completed timestamps do not enter outcomes',()=>{const a=workout('open','2026-10-09',[set(100)]);delete a.finishedAt;const b=workout('bad','2026-10-09',[set(100)]);b.finishedAt='bad';expect(analyzeExercisePerformance([a,b],range)).toEqual([])})
 it('latest qualified session wins, even with multiple sessions on one date',()=>{const a=workout('a','2026-10-09',[set(60)]),b=workout('b','2026-10-09',[set(65)]);b.startedAt='2026-10-09T10:00:00Z';b.finishedAt='2026-10-09T11:00:00Z';expect(analyze([b,a]).current?.workoutId).toBe('b')})
 it('same-day timestamps sort by actual instant across valid ISO timezone offsets',()=>{const a=workout('earlier','2026-10-09',[set(60)]),b=workout('later','2026-10-09',[set(65)]);a.startedAt='2026-10-09T08:00:00+08:00';a.finishedAt='2026-10-09T10:00:00+08:00';b.startedAt='2026-10-09T02:30:00Z';b.finishedAt='2026-10-09T03:00:00Z';const g=analyze([b,a]);expect(g.current?.workoutId).toBe('later');expect(g.baseline?.workoutId).toBe('earlier');expect(g.changes[0].delta).toBe(5)})
 it('future history excluded, actions without current-period facts retained for selector',()=>{const gs=analyzeExercisePerformance([workout('a','2026-09-20',[set(60)]),workout('future','2026-11-01',[set(100)])],range);expect(gs[0].current).toBeUndefined();expect(gs[0].history).toHaveLength(1)})
 it('duplicate identity within one workout combines real sets into a single session',()=>{const w=workout('a','2026-10-09',[set(60)]);w.exercises.push({...w.exercises[0],id:'other',sets:[set(50)]});expect(analyze([w]).current?.recordedSets).toBe(2);expect(analyze([w]).history).toHaveLength(1)})
 it.each([set(60,0),set(60,-1),set(60,1.5),set(60,NaN),set(NaN),set(Infinity),set(-1)])('invalid set cannot affect load/volume %j',bad=>{expect(validRecordedSet(bad)).toBe(false);const g=analyze([workout('a','2026-10-09',[bad,set(60)])]);expect(g.current).toMatchObject({recordedSets:1,omittedSets:1,highestWeight:60,volume:480})})
 it('explicit0kg is legal but missing is distinct',()=>{const g=analyze([workout('a','2026-10-09',[set(0),set(undefined)])]);expect(g.current).toMatchObject({recordedSets:2,weightedSets:1,highestWeight:0,volume:0})})
 it('volume is the sum of valid weighted sets and excludes unfinished workouts',()=>{const open=workout('open','2026-10-09',[set(100)]);delete open.finishedAt;expect(trainingVolumeAnalysis([workout('a','2026-10-09',[set(60,8),set(50,10),set(undefined),set(-1)]),open],range)).toMatchObject({sessions:1,recordedSets:3,weightedSets:2,omittedSets:1,volume:980})})
})
describe('nutrition, weights and weekly habit semantics',()=>{
 it('averages all complete recorded days, pairs targets on exactly matching days',()=>{const s=source();s.foodLogs=[food('a','2026-10-05',10),food('b','2026-10-06',30)];s.nutritionTargets=[{id:'t',date:'2026-10-05',protein:20,createdAt:stamp,updatedAt:stamp}];expect(report(s).nutrition.protein).toMatchObject({actual:20,pairedActual:10,target:20,achievement:50,completeDays:2,matchedDays:1})})
 it('partial macros are unknown whole-day totals, not zero or partial sums',()=>{const s=source();s.foodLogs=[food('a','2026-10-05',10),food('b','2026-10-05',undefined)];expect(report(s).nutrition.protein).toMatchObject({completeDays:0,partialDays:1});expect(report(s).nutrition.protein.actual).toBeUndefined();expect(report(s).nutrition.calories.actual).toBe(200)})
 it('explicit zero is a complete recorded nutrient fact',()=>{const s=source();s.foodLogs=[food('a','2026-10-05',0,0)];expect(report(s).nutrition.protein).toMatchObject({actual:0,completeDays:1});expect(report(s).foodDays).toBe(1)})
 it('no food, invalid macro or absent target never fabricates goal ratios',()=>{const s=source();expect(report(s).nutrition.protein.actual).toBeUndefined();s.foodLogs=[food('a','2026-10-05',NaN)];expect(report(s).nutrition.protein.actual).toBeUndefined();expect(report(s).nutrition.protein.achievement).toBeUndefined()})
 it('g/kg uses latest valid selected-day weight only',()=>{const s=source();s.foodLogs=[food('a','2026-10-09',100)];s.weights=[{id:'old',date:'2026-10-08',weightKg:60,createdAt:stamp,updatedAt:stamp},{id:'a',date:'2026-10-09',weightKg:80,createdAt:stamp,updatedAt:stamp},{id:'b',date:'2026-10-09',weightKg:100,createdAt:stamp,updatedAt:'2026-10-09T09:00:00Z'}];expect(report(s,'day').nutrition.protein.gkg).toBe(1);s.weights=s.weights.slice(0,1);expect(report(s,'day').nutrition.protein.gkg).toBeUndefined()})
 it('partial macros hide g/kg even with weight',()=>{const s=source();s.foodLogs=[food('a','2026-10-09',100),food('b','2026-10-09',undefined)];s.weights=[{id:'a',date:'2026-10-09',weightKg:80,createdAt:stamp,updatedAt:stamp}];expect(report(s,'day').nutrition.protein.gkg).toBeUndefined()})
 it('weight first/last and coverage are real, invalid/absent/future not zero',()=>{const s=source();expect(report(s).weightDelta).toBeUndefined();s.weights=[{id:'a',date:'2026-10-05',weightKg:80,createdAt:stamp,updatedAt:stamp},{id:'b',date:'2026-10-09',weightKg:79,createdAt:stamp,updatedAt:stamp},{id:'invalid',date:'2026-10-08',weightKg:NaN,createdAt:stamp,updatedAt:stamp}];expect(report(s).weightDelta).toBe(-1);expect(report(s).weights).toHaveLength(2)})
 it('weekly target3 completed3 uses3/3 and reaches100%, never3/7',()=>{const s=source();s.habits=[habit({targetPerWeek:3})];checks(s,['2026-10-05','2026-10-06','2026-10-09']);expect(report(s).habits[0].weeks[0]).toMatchObject({completed:3,target:3,ratio:1,achieved:true})})
 it('a month boundary includes actual natural-week check-ins without inflating monthly counts',()=>{const s=source();s.habits=[habit({targetPerWeek:3})];checks(s,['2026-09-29','2026-10-01','2026-10-02']);const h=report(s,'month').habits[0];expect(h.count).toBe(2);expect(h.weeks[0]).toMatchObject({completed:3,periodCompleted:2,target:3,ratio:1,achieved:true,naturalStart:'2026-09-28'})})
 it('no goal displays counts without invented ratio',()=>{const s=source();s.habits=[habit()];checks(s,['2026-10-05']);expect(report(s).habits[0].weeks[0].ratio).toBeUndefined()})
 it('target count takes precedence over simultaneous weekdays',()=>{const s=source();s.habits=[habit({targetPerWeek:3,weekdays:[1,2,3,4,5]})];expect(report(s).habits[0].weeks[0].target).toBe(3)})
 it('weekday-only goal uses actual configured planned-day count',()=>{const s=source();s.habits=[habit({weekdays:[1,3]})];expect(report(s).habits[0].weeks[0].target).toBe(2);expect(report(s).habits[0].cells.slice(0,4)).toEqual(['missing','off','missing','off'])})
 it('future and before-creation cells are not missed; new partial-week plan not retroactive',()=>{const s=source();s.habits=[habit({createdAt:'2026-10-07T00:00:00Z',updatedAt:'2026-10-07T00:00:00Z',targetPerWeek:3})];expect(report(s).habits[0].cells).toEqual(['before','before','unknown','unknown','unknown','future','future']);expect(report(s).habits[0].weeks[0].target).toBeUndefined()})
 it('saved legacy check-ins before current creation metadata remain facts without historical obligations',()=>{const s=source();s.habits=[habit({createdAt:'2026-10-08T08:00:00Z',updatedAt:'2026-10-08T08:00:00Z',targetPerWeek:3})];checks(s,['2026-10-05']);const h=report(s).habits[0];expect(h.count).toBe(1);expect(h.cells[0]).toBe('done');expect(h.cells[1]).toBe('before');expect(h.weeks[0].target).toBeUndefined()})
 it('inactive history preserves actual check-ins without inventing post-deactivation obligations',()=>{const s=source();s.habits=[habit({active:false,targetPerWeek:3})];checks(s,['2026-10-05']);expect(report(s).habits[0].cells[0]).toBe('done');expect(report(s).habits[0].cells[1]).toBe('unknown');expect(report(s).habits[0].weeks[0].target).toBeUndefined()})
 it('plan edits without snapshots disclose unknown historical targets',()=>{const s=source();s.habits=[habit({updatedAt:'2026-10-08T00:00:00Z',targetPerWeek:3})];expect(report(s,'month').habits[0].weeks.every(w=>w.target===undefined)).toBe(true)})
 it('service reads historical baseline and all20 stores remain byte-equivalent',async()=>{const d=new FitLogDatabase('coach-'+crypto.randomUUID());dbs.push(d);await d.open();await d.workouts.bulkPut([workout('a','2026-09-20',[set(60)]),workout('b','2026-10-09',[set(65)])]);const snapshot=()=>Promise.all(d.tables.map(t=>t.toArray()));const before=await snapshot(),r=await loadCoachReport('week','2026-10-09','2026-10-09',d);expect(r.analysis.groups[0].baseline?.date).toBe('2026-09-20');expect(await snapshot()).toEqual(before);expect(d.verno).toBe(11);expect(d.tables).toHaveLength(20)})
})
describe('calendar plot contract',()=>{
 it('future report reads empty bounded facts without inventing obligations',async()=>{const d=new FitLogDatabase('coach-future-'+crypto.randomUUID());dbs.push(d);await d.open();await d.habits.put(habit({targetPerWeek:3}));const r=await loadCoachReport('week','2027-01-20','2026-10-09',d);expect(r.analysis.elapsedDays).toBe(0);expect(r.analysis.habits[0].weeks[0]).toMatchObject({future:true,target:undefined,ratio:undefined});expect(r.analysis.training.sessions).toBe(0);expect(r.analysis.nutrition.calories.actual).toBeUndefined()})
 it('all ranges and all nonempty densities share162px and44px real-date spacing',()=>{for(const days of [7,30,90])for(const count of [1,2,3,days]){const points=Array.from({length:days},(_,i)=>({date:`2026-01-${String(i+1).padStart(2,'0')}`,value:i<count?250:undefined}));const g=recoveryLineGeometry(points,'water');expect(g.height).toBe(trendPlotHeight);expect(g.points[1].x-g.points[0].x).toBe(44)}})
 it('time gaps and missing recovery days stay real; sparse numbers are not repeated in the plot',()=>{expect(calendarOrdinal('2026-10-09')-calendarOrdinal('2026-10-05')).toBe(4);const g=recoveryLineGeometry([{date:'2026-10-05',value:250},{date:'2026-10-06'},{date:'2026-10-07',value:500}],'water');expect(g.segments).toHaveLength(2);expect(recoveryLineChartHtml(g.points,'water')).not.toContain('class="recovery-point-label"')})
})

describe('professional report presentation uses the real analysis',()=>{
 const esc=(v:unknown)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
 it('frequency dots count the same actual completed dates as the overview even with no valid sets',()=>{const s=source();s.workouts=[workout('invalid-sets','2026-10-05',[set(-1)])];const r=aggregateReport(s,'week','2026-10-09','2026-10-09'),a=analyzeCoachReport(s,r);expect(a.training).toMatchObject({days:1,sessions:1,dates:['2026-10-05'],recordedSets:0,omittedSets:1});expect(a.groups).toEqual([]);const html=coachReportHtml({report:r,analysis:a},{focus:'all',metric:'load'},'week',esc);expect((html.match(/coach-freq-dot done/g)??[])).toHaveLength(1);expect(html).toContain('暂无已完成的合格动作记录')})
 it('renders the actual5kg and cross-period date instead of a generic largest-load claim',()=>{const g=analyze([workout('prior','2026-09-20',[set(60)]),workout('now','2026-10-09',[set(65)])]);const html=performanceHtml(g,esc);expect(html).toContain('提升 5 kg');expect(html).toContain('2026-09-20');expect(html).toContain('相同 8 次');expect(html).not.toContain('力量提高')})
 it('escapes user-authored legacy names and preserves qualified snapshots',()=>{const g=analyze([workout('prior','2026-09-20',[set(60)],'x','<script>旧动作</script>'),workout('now','2026-10-09',[set(65)],'x','<script>新动作</script>')]);const s=source();s.workouts=[workout('now','2026-10-09',[set(65)],'x','<script>新动作</script>')];const r=aggregateReport(s,'week','2026-10-09','2026-10-09'),a=analyzeCoachReport(s,r);const html=coachReportHtml({report:r,analysis:a},{focus:'all',metric:'load'},'week',esc);expect(html).not.toContain('<script>');expect(html).toContain('&lt;script&gt;');expect(g.baseline?.name).toBe('<script>旧动作</script>')})
 it('daily report retains all nine actual domains and does not draw a one-day trend',()=>{const s=source();s.workouts=[workout('now','2026-10-09',[set(65)])];s.foodLogs=[food('f','2026-10-09',30)];const r=aggregateReport(s,'day','2026-10-09','2026-10-09'),a=analyzeCoachReport(s,r),html=coachReportHtml({report:r,analysis:a},{focus:'all',metric:'load'},'day',esc);expect(html.match(/data-record-category=/g)).toHaveLength(9);expect(html).not.toContain('data-coach-plot');expect(html).toContain('当天实际摄入');expect(html).toContain('第1组 · 8次 · 65 kg')})
 it('zero baseline does not produce infinity or a misleading percentage',()=>{const g=analyze([workout('a','2026-10-05',[set(0)]),workout('b','2026-10-09',[set(5)])]);expect(g.changes[0].percentage).toBeUndefined();expect(performanceHtml(g,esc)).not.toContain('Infinity')})
})

describe('multiple sessions retain truthful date positions',()=>{
 it('does not shift a second same-date session to a fake extra date slot',()=>{const html=coachPlotHtml([{id:'a',date:'2026-10-09',value:60,detail:'a'},{id:'b',date:'2026-10-09',value:65,detail:'b'}],undefined,'负重',v=>String(v));expect(html.match(/data-x="36"/g)).toHaveLength(2);expect(html.match(/class="recovery-point-date"/g)).toHaveLength(1)})
 it('real coincident date columns choose the closest vertical observation',()=>{expect(nearestTrendPoint([{x:80,y:30},{x:80,y:100}],80,95,{top:20,bottom:120})).toBe(1);expect(nearestTrendPoint([{x:80,y:30},{x:80,y:100}],80,35,{top:20,bottom:120})).toBe(0)})
})
