import { describe, it, expect, vi } from 'vitest'
import { parseMealPhotoEstimate, estimateMealPhoto, MEAL_PHOTO_PROMPT, MEAL_PHOTO_PRIVACY_KEY } from '../src/services/mealPhotoEstimateService'
import { FOOD_VISION_PROMPT, parseNutritionLabelExtraction } from '../src/services/aiVisionFoodService'
const good={summary:'火锅单餐，份量不确定',caloriesLow:1200,caloriesHigh:2200,assumptions:['用油与配料未知']}
describe('separate single-meal rough Vision workflow',()=>{
 it('parses a range and unknown endpoints without making macro/gram/FoodLog data',()=>{expect(parseMealPhotoEstimate(JSON.stringify(good))).toEqual(good);expect(parseMealPhotoEstimate(JSON.stringify({...good,caloriesLow:null,caloriesHigh:null})).caloriesLow).toBeNull();expect(MEAL_PHOTO_PROMPT).toContain('不是包装营养表转录');expect(MEAL_PHOTO_PROMPT).not.toBe(FOOD_VISION_PROMPT);expect(MEAL_PHOTO_PRIVACY_KEY).toBe('fitlog-meal-photo-privacy-ack-v1');expect(()=>parseNutritionLabelExtraction(JSON.stringify(good))).toThrow()})
 it.each([{caloriesLow:-1},{caloriesHigh:-1},{caloriesLow:2300},{caloriesHigh:100001},{caloriesLow:'1200'},{caloriesLow:null},{caloriesHigh:null},{caloriesLow:Infinity},{caloriesHigh:NaN},{summary:'x'.repeat(241)},{summary:''},{assumptions:Array(6).fill('a')},{assumptions:['x'.repeat(161)]},{assumptions:[1]},{protein:20},{grams:100}])('strictly rejects malformed/extra result %j',override=>{expect(()=>parseMealPhotoEstimate(JSON.stringify({...good,...override}))).toThrow()})
 it.each(['not json','```json\n'+JSON.stringify(good)+'\n```',JSON.stringify(good)+' explanation','[]','null','x'.repeat(5001)])('rejects raw/non-JSON/fenced/oversized text',text=>expect(()=>parseMealPhotoEstimate(text)).toThrow())
 it('only actual local preprocessing products may enter transport; arbitrary URLs/data/blobs and >2 inputs rejected',async()=>{const client={visionChat:vi.fn()};for(const images of [[],[{dataUrl:'https://attacker.invalid/image',bytes:1,width:100,height:100}],[{dataUrl:'blob:x',bytes:1,width:100,height:100}],Array(3).fill({dataUrl:'data:image/jpeg;base64,/9j/AAAA',bytes:6,width:100,height:100})])await expect(estimateMealPhoto(client,images,[])).rejects.toThrow();expect(client.visionChat).not.toHaveBeenCalled()})
})
