import 'fake-indexeddb/auto'
import Dexie from 'dexie'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { FitLogDatabase, STARTER_EXERCISE_NAMES } from '../src/db/database'
import { startSleep, finishSleep, editSleep, deleteSleep, addWater, editWater, deleteWater } from '../src/services/recoveryService'
import { averageClock, latestValidDayWeight, macroPerKg, recoverySummary, sleepMinutes } from '../src/utils/recovery'
import { getLocalDateString } from '../src/utils/date'
import { exportBackup, restoreBackup, validateBackup } from '../src/services/backupService'
import { legacyV10Database } from './fixtures/legacyV10Database'
import legacy from './fixtures/legacyV10Data.json'
import currentFixture from './fixtures/legacyV11Data.json'
import { legacyV11Database } from './fixtures/legacyV11Database'
import { encryptSyncText, decryptSyncText } from '../src/services/syncCryptoService'
import { syncDataHash } from '../src/utils/syncDataHash'
const databases:FitLogDatabase[]=[]
const make=(name=`recovery-${crypto.randomUUID()}`)=>{const d=new FitLogDatabase(name);databases.push(d);return d}
afterEach(async()=>{vi.restoreAllMocks();for(const d of databases.splice(0)){d.close();await Dexie.delete(d.name)}})
const start=()=>new Date(2026,9,8,23,48),end=()=>new Date(2026,9,9,7,24)
describe('durable sleep lifecycle',()=>{
 it('starts once under repeated/concurrent requests, including a second database connection',async()=>{const d=make(),other=make(d.name);const rows=await Promise.all([startSleep(d,start()),startSleep(other,start()),startSleep(d,start())]);expect(new Set(rows.map(r=>r.id)).size).toBe(1);expect(await d.sleepSessions.count()).toBe(1);other.close()})
 it('survives close/reopen and completes on the local wake date with exact elapsed duration',async()=>{const d=make(),s=await startSleep(d,start());d.close();await d.open();expect((await d.sleepSessions.get(s.id))?.activeKey).toBe('active');const r=await finishSleep(s.id,d,end());expect(r).toMatchObject({recordDate:'2026-10-09',durationMinutes:456});expect(r.activeKey).toBeUndefined();expect((await finishSleep(s.id,d,new Date(2026,9,9,8))).endTime).toBe(end().toISOString());expect(await d.sleepSessions.where('activeKey').equals('active').count()).toBe(0)})
 it('cancels only the selected active record; new sleep can begin again',async()=>{const d=make(),first=await startSleep(d,start());await finishSleep(first.id,d,end());const second=await startSleep(d,new Date(2026,9,9,23));await deleteSleep(second.id,d);expect(await d.sleepSessions.get(first.id)).toBeTruthy();expect((await startSleep(d,new Date(2026,9,10,23))).id).not.toBe(second.id)})
 it('a forgotten >24h session persists, does not auto-finish or spawn another',async()=>{const d=make(),a=await startSleep(d,start());d.close();await d.open();expect((await startSleep(d,new Date(2026,9,11))).id).toBe(a.id);const r=await finishSleep(a.id,d,new Date(2026,9,11));expect(r.durationMinutes).toBeGreaterThan(1440)})
 it('manual corrections recalculate minutes/wake date and preserve identity/creation time',async()=>{const d=make(),a=await startSleep(d,start());await finishSleep(a.id,d,end());const e=new Date(2026,9,9,8),r=await editSleep(a.id,new Date(2026,9,9,0).toISOString(),e.toISOString(),d,new Date(2026,9,10));expect(r.durationMinutes).toBe(480);expect(r.createdAt).toBe(a.createdAt);expect(r.recordDate).toBe('2026-10-09')})
 it('active start correction stays active, invalid/inverted/future edits leave data intact',async()=>{const d=make(),a=await startSleep(d,start());const revised=await editSleep(a.id,new Date(2026,9,8,22).toISOString(),undefined,d,end());expect(revised.activeKey).toBe('active');await expect(editSleep(a.id,end().toISOString(),start().toISOString(),d,end())).rejects.toThrow();await expect(editSleep(a.id,'invalid',undefined,d,end())).rejects.toThrow();await expect(editSleep(a.id,new Date(2026,9,10).toISOString(),undefined,d,end())).rejects.toThrow();expect(await d.sleepSessions.get(a.id)).toEqual(revised)})
 it('absolute instants account for offsets and DST instead of subtracting local clock strings',()=>{expect(sleepMinutes('2026-10-08T23:48:00+08:00','2026-10-09T07:24:00+08:00')).toBe(456);expect(sleepMinutes('2026-11-01T01:30:00-04:00','2026-11-01T02:30:00-05:00')).toBe(120);expect(()=>sleepMinutes('bad','bad')).toThrow();expect(()=>sleepMinutes(end().toISOString(),start().toISOString())).toThrow()})
})
describe('append-only water with explicit correction/undo',()=>{
 it('keeps each rapid drink, local day/timestamp and exact integer sum; edit/delete one does not affect another day',async()=>{const d=make();const rows=await Promise.all([addWater(250,d,start()),addWater(500,d,start()),addWater(350,d,end())]);expect(await d.waterLogs.count()).toBe(3);expect((await d.waterLogs.where('date').equals(getLocalDateString(start())).toArray()).reduce((n,w)=>n+w.amountMl,0)).toBe(750);await editWater(rows[0]!.id,300,d);await deleteWater(rows[1]!.id,d);expect((await d.waterLogs.get(rows[0]!.id))?.amountMl).toBe(300);expect((await d.waterLogs.get(rows[2]!.id))?.amountMl).toBe(350);d.close();await d.open();expect(await d.waterLogs.count()).toBe(2)})
 it.each([0,-1,1.5,NaN,Infinity,100001])('rejects invalid amount %s before writing',async value=>{const d=make();await expect(addWater(value,d)).rejects.toThrow();expect(await d.waterLogs.count()).toBe(0)})
})
describe('honest daily nutrition and recovery statistics',()=>{
 it('uses only the latest valid weight on the selected date; never historical fallback',()=>{const stamp='2026-10-08T01:00:00Z',w=(id:string,date:string,weightKg:number,updatedAt=stamp)=>({id,date,weightKg,createdAt:stamp,updatedAt});expect(latestValidDayWeight([w('old','2026-10-07',80)],'2026-10-08')).toBeUndefined();expect(latestValidDayWeight([w('a','2026-10-08',85),w('b','2026-10-08',86,'2026-10-08T02:00:00Z'),w('c','2026-10-08',0,'2026-10-08T03:00:00Z')],'2026-10-08')).toBe(86);expect(macroPerKg(164,86)).toBe('1.91 g/kg');expect(macroPerKg(252,86)).toBe('2.93 g/kg');expect(macroPerKg(52,86)).toBe('0.60 g/kg');expect(macroPerKg(0,86)).toBe('0.00 g/kg');expect(macroPerKg(164,undefined)).toBeUndefined();expect(macroPerKg(164,86,false)).toBeUndefined()})
 it('averages clock values across midnight and does not invent a mean for opposed times',()=>{const t=(h:number,m:number)=>new Date(2026,9,8,h,m).toISOString();expect(averageClock([t(23,50),t(0,10)])).toBe('00:00');expect(averageClock([t(0,0),t(12,0)])).toBeUndefined()})
 it('aggregates multiple sessions per wake day, excludes active/future/missing and offers 7/30/90 day ranges',async()=>{const d=make(),a=await startSleep(d,start());await finishSleep(a.id,d,end());const b=await startSleep(d,new Date(2026,9,9,10));await finishSleep(b.id,d,new Date(2026,9,9,11));await startSleep(d,new Date(2026,9,9,23));await addWater(500,d,end());const r=recoverySummary(await d.sleepSessions.toArray(),await d.waterLogs.toArray(),'2026-10-09',7);expect(r.averageMinutes).toBe(516);expect(r.recordedDays).toBe(1);expect(r.daily.at(-1)?.minutes).toBe(516);expect(r.daily).toHaveLength(7);expect(r.daily[0]?.minutes).toBeUndefined();expect(r.daily.at(-1)?.waterMl).toBe(500);expect(recoverySummary([],[],'2026-10-09',30).averageMinutes).toBeUndefined()})
})
describe('V11 preservation, Backup and encrypted Sync release guard',()=>{
 it('upgrades actual frozen V10 without changing any row/index or reseeding; new stores are empty',async()=>{const d=make(),old=legacyV10Database(d.name);await old.open();await old.transaction('rw',old.tables,async()=>{for(const [name,rows]of Object.entries(legacy))await old.table(name).bulkAdd(rows)});const indexes=Object.fromEntries(old.tables.map(t=>[t.name,t.schema.indexes.map(i=>i.src)]));old.close();await d.open();expect(d.verno).toBe(11);expect(d.tables).toHaveLength(20);for(const[name,rows]of Object.entries(legacy)){expect(await d.table(name).toArray()).toEqual([...rows].sort((a,b)=>a.id.localeCompare(b.id)));expect(d.table(name).schema.indexes.map(i=>i.src)).toEqual(indexes[name])}expect(await d.sleepSessions.count()).toBe(0);expect(await d.waterLogs.count()).toBe(0);d.close();await d.open();expect(await d.exercises.count()).toBe(legacy.exercises.length)})
 it('Backup11 round-trips completed/active sleeps and water, encrypted envelope stays V1; old restore has empty recovery',async()=>{const d=make();await restoreBackup({app:'FitLog Lite',schemaVersion:10,exportedAt:end().toISOString(),data:legacy},d);const s=await startSleep(d,start());await finishSleep(s.id,d,end());await startSleep(d,new Date(2026,9,9,23));await addWater(350,d,end());const b=await exportBackup(d);expect(b.schemaVersion).toBe(11);const envelope=await encryptSyncText(JSON.stringify(b),'synthetic-recovery-password');expect(envelope.formatVersion).toBe(1);const copy=make();await restoreBackup(JSON.parse(await decryptSyncText(envelope,'synthetic-recovery-password')),copy);expect((await exportBackup(copy)).data).toEqual(b.data);expect(await syncDataHash((await exportBackup(copy)).data)).toBe(await syncDataHash(b.data));await restoreBackup({app:'FitLog Lite',schemaVersion:10,exportedAt:b.exportedAt,data:legacy},copy);expect(await copy.sleepSessions.count()).toBe(0);expect(await copy.waterLogs.count()).toBe(0)})
 it('rejects malformed/multiple-active/inconsistent durations before replacement',async()=>{const d=make();await startSleep(d,start());await addWater(250,d,end());const good=await exportBackup(d);for(const mutate of [(b:typeof good)=>b.data.sleepSessions.push({...b.data.sleepSessions[0]!,id:'second-active'}),(b:typeof good)=>b.data.waterLogs[0]!.amountMl=1.2,(b:typeof good)=>{b.data.sleepSessions[0]!.durationMinutes=123}]){const bad=structuredClone(good);mutate(bad);expect(()=>validateBackup(bad)).toThrow();await expect(restoreBackup(bad,d)).rejects.toThrow();expect((await exportBackup(d)).data).toEqual(good.data)}})
 it('failed restore rolls back both recovery and legacy stores in the same transaction',async()=>{const d=make();await startSleep(d,start());await addWater(250,d,end());const before=await exportBackup(d),incoming=structuredClone(before);incoming.data.waterLogs[0]!.amountMl=500;vi.spyOn(d.waterLogs,'bulkAdd').mockRejectedValueOnce(new Error('disk failure'));await expect(restoreBackup(incoming,d)).rejects.toThrow('disk failure');expect((await exportBackup(d)).data).toEqual(before.data)})
 it('frozen V11 active/completed/water and all previous snapshots survive reopen and Backup',async()=>{const d=make(),frozen=legacyV11Database(d.name);await frozen.open();await frozen.transaction('rw',frozen.tables,async()=>{for(const[name,rows]of Object.entries(currentFixture))await frozen.table(name).bulkAdd(rows)});frozen.close();await d.open();const before=await exportBackup(d);d.close();await d.open();expect((await exportBackup(d)).data).toEqual(before.data);const copy=make();await restoreBackup(before,copy);expect((await exportBackup(copy)).data).toEqual(before.data);expect(await copy.sleepSessions.where('activeKey').equals('active').count()).toBe(1)})
 it('completed inverted/future corrections are rejected without rewriting the original',async()=>{const d=make(),a=await startSleep(d,start());const completed=await finishSleep(a.id,d,end());await expect(editSleep(a.id,end().toISOString(),start().toISOString(),d,new Date(2026,9,10))).rejects.toThrow();await expect(editSleep(a.id,start().toISOString(),new Date(2026,9,11).toISOString(),d,new Date(2026,9,10))).rejects.toThrow();expect(await d.sleepSessions.get(a.id)).toEqual(completed)})
 it('new database populate still runs once',async()=>{const d=make();await d.open();expect(await d.exercises.count()).toBe(STARTER_EXERCISE_NAMES.length);await d.exercises.clear();d.close();await d.open();expect(await d.exercises.count()).toBe(0)})
})
