import 'fake-indexeddb/auto'
import Dexie from 'dexie'
import { afterEach, expect, it } from 'vitest'
import { FitLogDatabase } from '../src/db/database'
import type { Food } from '../src/db/types'
import { calorieBudgetHtml } from '../src/ui/calorieBudget'
import { remainingNutritionGoalsHtml } from '../src/ui/remainingNutritionGoals'
import { macroNutritionSummaryForDay } from '../src/ui/macroNutritionSummary'
import { completeNutrition, getNutritionCompletionSummary } from '../src/utils/nutritionCompletion'
import { readDailyNutritionSummary } from '../src/services/dailyNutritionSummary'
import { applyNutritionCompletionPlan, readNutritionCompletionSource, nutritionCompletionSourceSignature } from '../src/services/nutritionCompletionService'
import { nutritionHtml } from '../src/ui/coachReport'
const dbs:FitLogDatabase[]=[]
afterEach(async()=>{for(const d of dbs.splice(0)){d.close();await Dexie.delete(d.name)}})
const make=()=>{const d=new FitLogDatabase('v4-'+crypto.randomUUID());dbs.push(d);return d}
const date='2026-10-01',stamp='2026-10-01T00:00:00Z'
const food=(id:string,values:Partial<Food>={}):Food=>({id,name:id,referenceGrams:100,calories:100,protein:20,carbs:0,fat:0,createdAt:stamp,updatedAt:stamp,...values})
it.each([[1250,2000,'below','还差 750'],[2000,2000,'reached','已达目标'],[2750,2000,'above','高于目标 750'],[9999,undefined,'unset','尚未设置目标'],[20,0,'above','高于目标 20'],[0,0,'zero','已达目标']] as const)('budget preserves actual %s goal %s state %s',(actual,goal,state,text)=>{for(const surface of ['today','food'] as const){const html=calorieBudgetHtml(actual,goal,surface);expect(html).toContain(`data-actual="${actual}"`);expect(html).toContain(`<strong>${actual}</strong>`);expect(html).toContain(text);expect(html).toContain(state);expect(html).not.toMatch(/svg|NaN|Infinity|data-count/);if(goal===undefined)expect(html).not.toContain('% 已摄入')}})
it('remaining area always exposes four independently meaningful states',()=>{const summary=getNutritionCompletionSummary({calories:2000,protein:10,fat:0},[{id:'x',date,foodName:'unknown',grams:100,referenceGrams:100,caloriesPerReference:2000,totalCalories:2000,totalProtein:20,createdAt:stamp,updatedAt:stamp}]);const html=remainingNutritionGoalsHtml(summary);for(const text of ['已达目标','已超 10 g','未设置目标','数据不完整'])expect(html).toContain(text);expect(html.match(/class="remaining-goal /g)).toHaveLength(4)})
it.each([[['a']],[['a','b']],[[]]])('strict candidate IDs %j never leak unselected foods',ids=>{const result=completeNutrition({calories:500,protein:100,carbs:200},[],[food('a'),food('b',{carbs:50}),food('unselected',{calories:300,protein:50,carbs:50})],new Set(),new Set(ids));expect(result.plans.every(p=>p.items.every(i=>ids.includes(i.food.id)))).toBe(true);if(ids.length)expect(result.plans.length).toBeGreaterThan(0);else expect(result.plans).toEqual([]);if(ids.length===1)expect(result.plans.every(p=>!p.closeEnough&&p.difference.carbs===-200)).toBe(true)})
it('same-name IDs and incomplete candidates remain distinct and missing is not zero',()=>{const r=completeNutrition({protein:100,carbs:100},[],[food('a',{name:'相同名称'}),food('b',{name:'相同名称',carbs:50}),food('c',{protein:undefined})],new Set(),new Set(['a','c']));expect(r.excludedFoodCount).toBe(1);expect(r.plans.every(p=>p.items.every(i=>i.food.id==='a'))).toBe(true);expect(()=>completeNutrition({protein:10},[],[],new Set(),new Set(['1','2','3','4','5']))).toThrow('4')})
it('already satisfied and no goals never fabricate a completion plan',()=>{expect(completeNutrition({},[],[food('a')]).plans).toEqual([]);expect(completeNutrition({protein:0},[],[food('a')]).plans).toEqual([])})
it('one atomic adoption validates current source and blocks repeated concurrent adoption',async()=>{const d=make(),f=food('a');await d.foods.add(f);await d.nutritionTargets.add({id:'goal',date,protein:100,createdAt:stamp,updatedAt:stamp});const source=await readNutritionCompletionSource(date,d),guard={signature:nutritionCompletionSourceSignature(source),allowedFoodIds:['a']};const results=await Promise.allSettled([applyNutritionCompletionPlan(date,'lunch',[{food:f,grams:100}],d,guard),applyNutritionCompletionPlan(date,'lunch',[{food:f,grams:100}],d,guard)]);expect(results.map(r=>r.status).sort()).toEqual(['fulfilled','rejected']);expect(await d.foodLogs.count()).toBe(1);expect((await d.foodLogs.toArray())[0]).toMatchObject({date,meal:'lunch',grams:100,totalProtein:20})})
it.each(['food','target','log','whitelist'])('stale %s rejects without any partial write',async change=>{const d=make(),f=food('a');await d.foods.add(f);await d.nutritionTargets.add({id:'goal',date,protein:100,createdAt:stamp,updatedAt:stamp});const source=await readNutritionCompletionSource(date,d),guard={signature:nutritionCompletionSourceSignature(source),allowedFoodIds:change==='whitelist'?['b']:['a']};if(change==='food')await d.foods.update('a',{calories:200});if(change==='target')await d.nutritionTargets.update('goal',{protein:150});if(change==='log')await applyNutritionCompletionPlan(date,'lunch',[{food:f,grams:5}],d);const before=await d.foodLogs.toArray();await expect(applyNutritionCompletionPlan(date,'lunch',[{food:f,grams:100}],d,guard)).rejects.toThrow();expect(await d.foodLogs.toArray()).toEqual(before)})
it('future plans are read-only even if called outside UI',async()=>{const d=make();await expect(applyNutritionCompletionPlan('2099-01-01','lunch',[{food:food('a'),grams:100}],d)).rejects.toThrow('未来');expect(await d.foodLogs.count()).toBe(0)})
it('shared snapshot renders unknown dimension, same-date latest weight, exact ratios and unchanged facts',async()=>{const d=make(),f=food('a',{carbs:undefined,fat:10});await applyNutritionCompletionPlan(date,'lunch',[{food:f,grams:100}],d);await d.weights.put({id:'latest',date,weightKg:80,createdAt:stamp,updatedAt:'2026-10-01T01:00:00Z'});const rows=await d.foodLogs.toArray(),day=await readDailyNutritionSummary(date,d),html=macroNutritionSummaryForDay(day);expect(html).toContain('0.25 g/kg');expect(html).toContain('0.13 g/kg');expect(html).toContain('数据不完整');expect(html.match(/g\/kg/g)).toHaveLength(4);expect(html).not.toContain('碳水 摄入 0g');expect(await d.foodLogs.toArray()).toEqual(rows);await d.weights.clear();expect(macroNutritionSummaryForDay(await readDailyNutritionSummary(date,d))).not.toContain('g/kg')})
it('report has four complete structural tracks and retains all statistical evidence in details',()=>{const m={actual:123.4,target:150,pairedActual:100,achievement:66.67,completeDays:3,partialDays:2,matchedDays:1,gkg:1.85},html=nutritionHtml({calories:m,protein:m,carbs:{...m,target:undefined},fat:{...m,actual:undefined}},4,7);expect(html.match(/class="coach-nutrient /g)).toHaveLength(4);expect(html.match(/class="coach-meter"/g)).toHaveLength(4);for(const text of ['3 天','部分记录 2 天','同日配对 1 天','66.7%','1.85 g/kg','无同日有效目标比例','数据不完整','查看统计口径'])expect(html).toContain(text)})

it('nonfinite legacy macro snapshots remain unknown without fabricated g/kg',()=>{const day={date,logs:[{id:'invalid',date,foodName:'legacy',grams:100,referenceGrams:100,caloriesPerReference:100,totalCalories:100,totalProtein:NaN,totalCarbs:20,totalFat:-1,createdAt:stamp,updatedAt:stamp}],target:undefined,totals:{calories:100,protein:NaN,carbs:20,fat:-1},effectiveWeight:75};const html=macroNutritionSummaryForDay(day);expect(html.match(/class="macro-value" aria-hidden="true">数据不完整/g)).toHaveLength(2);expect(html).toContain('0.27 g/kg');expect(html).not.toContain('NaNg');expect(html).not.toContain('-1g')})
