import 'fake-indexeddb/auto'
import { describe, it, expect, vi } from 'vitest'
import fixture from './fixtures/webSearchPro.json'
import { extractBilibiliCandidates, normalizeBilibiliVideoUrl, VideoSearchSettings, ZhipuBilibiliSearchProvider, TrainingVideoSearchRouter } from '../src/services/videoSearchService'
import { directTrainingVideoIntent, videoQueryVariants } from '../src/services/trainingVideoIntent'
import { AiProfiles } from '../src/services/aiProfiles'
import { AiOrchestrator } from '../src/ai/orchestrator'
import { aiEnvironment } from './helpers/ai'
const memory=()=>{const m=new Map<string,string>();return {getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v)},removeItem:(k:string)=>{m.delete(k)}}}
const url='https://www.bilibili.com/video/BV1B7411m7LV'
describe('bounded untrusted Web-Search-Pro projection',()=>{
  it('official shape synthetic fixture projects two canonical BV videos',()=>{const r=extractBilibiliCandidates(fixture);expect(r.videos).toHaveLength(2);expect(r.validVideos).toBe(2);expect(r.videos[0]!.watchUrl).toBe(url)})
  it.each([{url},{nested:{link:url}},{choices:[{message:{content:'教学：'+url}}]},{content:`[教学](${url})`},{content:url.replaceAll('/','\\/')},{content:url.replaceAll('/','\\u002f')}])('supports structured/nested/plain/markdown/escaped sources',raw=>expect(extractBilibiliCandidates(raw).videos).toHaveLength(1))
  it.each(['www.bilibili.com','bilibili.com','m.bilibili.com'])('canonicalizes %s with params/trailing slash',host=>expect(normalizeBilibiliVideoUrl(`https://${host}/video/BV1B7411m7LV/?share=1`)).toBe(url))
  it.each(['http://www.bilibili.com/video/BV1B7411m7LV','https://evil.bilibili.com/video/BV1B7411m7LV','https://www.bilibili.com.evil.invalid/video/BV1B7411m7LV','https://www.bilibili.com/read/BV1B7411m7LV','https://www.bilibili.com/search?BV1B7411m7LV','https://www.bilibili.com/video/BVbad','https://a@www.bilibili.com/video/BV1B7411m7LV','https://www.bilibili.com:999/video/BV1B7411m7LV',`<iframe src="${url}"></iframe>`])('rejects unsafe/non-video %s',raw=>expect(extractBilibiliCandidates({content:raw}).videos).toEqual([]))
  it('dedupes BV across URL sources; drops arbitrary HTML; rejects giant/secret input',()=>{expect(extractBilibiliCandidates({url,content:`[教学](${url}/?x=1)`}).videos).toHaveLength(1);expect(()=>extractBilibiliCandidates({content:'x'.repeat(130*1024)})).toThrow();expect(()=>extractBilibiliCandidates({url,title:'known-secret'},3,['known-secret'])).toThrow();expect(extractBilibiliCandidates({content:'<script>evil</script>'+url}).videos).toEqual([])})
  it('limits projection to three by default/five maximum and bounds traversal',()=>{const rows=Array.from({length:100},(_,i)=>({link:`https://www.bilibili.com/video/BV1B7411m${String(i).padStart(3,'0')}`}));expect(extractBilibiliCandidates(rows).videos.length).toBe(3);expect(extractBilibiliCandidates(rows,5).videos.length).toBe(5)})
})
describe('deterministic successful-empty variants',()=>{
  const setup=(fetcher:typeof fetch)=>{const settings=new VideoSearchSettings(memory());settings.acknowledge();return new ZhipuBilibiliSearchProvider(settings,()=>({key:'synthetic-search-key'}),fetcher)}
  it('zero then two valid stops after second request, with safe diagnostics',async()=>{const f=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({choices:[{message:{content:'无结果'}}]}))).mockResolvedValueOnce(new Response(JSON.stringify(fixture))),p=setup(f);expect(await p.search('杠铃俯身划传')).toHaveLength(2);expect(f).toHaveBeenCalledTimes(2);expect(p.lastDiagnostics).toMatchObject({requests:2,validVideos:2});const bodies=f.mock.calls.map(c=>JSON.parse(c[1].body));expect(bodies[0].messages[0].content).toContain('杠铃俯身划船');expect(bodies[1].messages[0].content).toContain('杠铃划船');expect(JSON.stringify(bodies)).not.toContain('synthetic-search-key')})
  it('first success sends exactly one request',async()=>{const f=vi.fn().mockResolvedValue(new Response(JSON.stringify(fixture)));expect(await setup(f).search('深蹲')).toHaveLength(2);expect(f).toHaveBeenCalledOnce()})
  it('zero exhausts at most three, no extra requests',async()=>{const f=vi.fn(()=>Promise.resolve(new Response('{}'))),p=setup(f);expect(await p.search('杠铃俯身划船')).toEqual([]);expect(f).toHaveBeenCalledTimes(3);expect(p.lastDiagnostics).toEqual({requests:3,candidateLinks:0,validVideos:0})})
  it('HTTP failure is not retried; pre-abort does not fetch',async()=>{const f=vi.fn().mockResolvedValue(new Response('private',{status:403})),p=setup(f);await expect(p.search('卧推')).rejects.toThrow();expect(f).toHaveBeenCalledOnce();f.mockClear();const c=new AbortController();c.abort();await expect(p.search('卧推',3,c.signal)).rejects.toMatchObject({code:'aborted'});expect(f).not.toHaveBeenCalled()})
  it('AUTO keeps YouTube fallback on domestic empty',async()=>{const settings=new VideoSearchSettings(memory());settings.acknowledge();settings.setEnabled('bilibili',true);settings.setEnabled('youtube',true);const b={search:vi.fn().mockResolvedValue([])},y={search:vi.fn().mockResolvedValue([{id:'Abcdefghij1',provider:'youtube'}])};const router=new TrainingVideoSearchRouter(settings,{bilibili:b,youtube:y});expect((await router.searchDetailed('深蹲',3)).videos).toHaveLength(1);expect(y.search).toHaveBeenCalledOnce()})
})
describe('conservative no-chat video intent',()=>{
  it.each(['搜索杠铃俯身划船训练视频','搜索杠铃俯身划船的训练视频','帮我搜一下杠铃俯身划船教学视频。','找深蹲教学视频','给我几个绳索面拉视频','帮我找绳索面拉教学视频'])('extracts explicit %s',text=>expect(directTrainingVideoIntent(text)).toBeTruthy())
  it.each(['找那个弯着腰往肚子拉的动作视频','我肩膀不舒服，帮我找深蹲视频','我的体重70公斤，找深蹲视频','javascript:找深蹲视频','找未知动作视频'])('keeps ambiguous/private text in normal routing',text=>expect(directTrainingVideoIntent(text)).toBeUndefined())
  it('variants are unique and finite',()=>{expect(videoQueryVariants('杠铃俯身划传')).toHaveLength(3);expect(videoQueryVariants('绳索面拉')).toHaveLength(3)})
  it.each(['搜索杠铃俯身划船的训练视频','帮我找绳索面拉教学视频'])('explicit final text invokes tool once and zero chat/client calls: %s',async text=>{const env=aiEnvironment(),profiles=new AiProfiles(memory());profiles.save({name:'synthetic',baseUrl:'https://mock.invalid/v1',model:'chat'},'synthetic-key');profiles.acknowledgePrivacy();const search=vi.fn().mockResolvedValue(extractBilibiliCandidates(fixture).videos),factory=vi.fn();const engine=new AiOrchestrator({profiles,database:env.database,context:()=>env.context,videoSearch:{search},clientFactory:factory});try{await engine.send(text);expect(factory).not.toHaveBeenCalled();expect(search).toHaveBeenCalledOnce();expect(engine.items.filter(x=>x.kind==='videos')[0]!.videos).toHaveLength(2);expect(engine.items.at(-1)!.content).toBe('找到 2 个训练视频。');expect(engine.usage).toEqual({});expect(await env.database.habits.count()).toBe(0)}finally{env.database.close();await env.database.delete()}})
})
