import 'fake-indexeddb/auto'
import { describe, it, expect, vi } from 'vitest'
import { VideoSearchSettings, YouTubeVideoSearchProvider, validateVideoQuery, projectVideoResults, videoEmbedUrl, videoWatchUrl, VIDEO_KEY } from '../src/services/videoSearchService'
import { AiProfiles } from '../src/services/aiProfiles'
import { AiOrchestrator } from '../src/ai/orchestrator'
import { buildFitLogSystemPrompt } from '../src/ai/systemPrompt'
import { aiEnvironment, aiCall } from './helpers/ai'
const memory = () => { const values=new Map<string,string>();return {getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)},removeItem:(key:string)=>{values.delete(key)}} }
const raw = {items:['Abcdefghij1','Abcdefghij2','Abcdefghij3'].map(id=>({id:{videoId:id},snippet:{title:'绳索面拉 正确动作',channelTitle:'Training channel',publishedAt:'2026-09-01T00:00:00Z',thumbnails:{high:{url:'javascript:malicious'}}}}))}
const setup = (fetcher:typeof fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify(raw))),timeout=15000) => {const settings=new VideoSearchSettings(memory());settings.save('synthetic-video-key');settings.acknowledge();return {settings,fetcher,provider:new YouTubeVideoSearchProvider(settings,fetcher,()=>['known-secret'],timeout)}}
describe('real YouTube search boundary',()=>{
  it('unconfigured and privacy errors are structured and never fetch',async()=>{const {provider,settings,fetcher}=setup();settings.remove();await expect(provider.search('face pull')).rejects.toMatchObject({code:'video_not_configured'});expect(fetcher).not.toHaveBeenCalled();const s=new VideoSearchSettings(memory());s.save('synthetic-key');await expect(new YouTubeVideoSearchProvider(s,fetcher).search('face pull')).rejects.toMatchObject({code:'video_privacy'})})
  it('fetches fixed endpoint once with safe flags/header, default 3, original relevance and locally derived thumbnails',async()=>{const {provider,fetcher}=setup();const videos=await provider.search('  cable face pull form  ');expect(videos).toHaveLength(3);expect(videos[0]!.thumbnailUrl).toBe('https://i.ytimg.com/vi/Abcdefghij1/hqdefault.jpg');expect(fetcher).toHaveBeenCalledOnce();const [url,init]=(fetcher as ReturnType<typeof vi.fn>).mock.calls[0]!;expect(url).not.toContain('synthetic-video-key');expect(new URL(url).searchParams.get('q')).toBe('cable face pull form');expect(init).toMatchObject({credentials:'omit',cache:'no-store',redirect:'error',headers:{'X-Goog-Api-Key':'synthetic-video-key'}})})
  it.each(['','  ','https://attacker.invalid','weight 70 kg','体重公斤 健康记录','x'.repeat(121)])('rejects empty/URL/private/oversized query %s',async query=>{const {provider,fetcher}=setup();await expect(provider.search(query)).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled()})
  it.each([0,6,1.5])('bounds limit %s',limit=>expect(()=>validateVideoQuery('face pull',limit)).toThrow())
  it('drops bad IDs/duplicates, bounds strings and does not trust arbitrary image URLs',()=>{const videos=projectVideoResults({items:[{id:{videoId:'../bad'},snippet:{title:'bad',channelTitle:'bad'}},...raw.items,raw.items[0],{id:{videoId:'ABCDEFGHIJK'},snippet:{title:'x'.repeat(1000),channelTitle:'y'.repeat(200)}}]},5,[]);expect(videos).toHaveLength(4);expect(videos.at(-1)!.title).toHaveLength(240);expect(videos.at(-1)!.channel).toHaveLength(100)})
  it('derives only strict watch/embed URLs; autoplay=0, inline and official source',()=>{expect(videoWatchUrl('Abcdefghij1')).toBe('https://www.youtube.com/watch?v=Abcdefghij1');const embed=new URL(videoEmbedUrl('Abcdefghij1','https://king-640-060.github.io'));expect(embed.hostname).toBe('www.youtube-nocookie.com');expect(embed.searchParams.get('autoplay')).toBe('0');expect(embed.searchParams.get('playsinline')).toBe('1');for(const id of ['javascript:bad','../../bad','data:x','abcdefghij']){expect(()=>videoWatchUrl(id)).toThrow();expect(()=>videoEmbedUrl(id,'https://example.com')).toThrow()}})
  it.each([new Response('bad json'),new Response('x'.repeat(129*1024)),new Response('raw synthetic-video-key',{status:403}),new Response(JSON.stringify({items:[{snippet:{title:'synthetic-video-key'}}]}))])('safe malformed/oversized/service/secret rejection',async response=>{const {provider}=setup(vi.fn().mockResolvedValue(response));await expect(provider.search('face pull')).rejects.toThrow();try{await provider.search('face pull')}catch(error){expect(String(error)).not.toContain('synthetic-video-key');expect(String(error)).not.toContain('raw')}})
  it('timeout and caller abort cancel transport without retries',async()=>{const fetcher=vi.fn((_url,_init)=>new Promise((_resolve,reject)=>{_init.signal.addEventListener('abort',()=>reject(new Error('raw secret')))})) as unknown as typeof fetch;const {provider}=setup(fetcher,10);await expect(provider.search('face pull')).rejects.toMatchObject({code:'video_timeout'});const controller=new AbortController();const pending=provider.search('face pull',3,controller.signal);controller.abort();await expect(pending).rejects.toMatchObject({code:'aborted'});expect(fetcher).toHaveBeenCalledTimes(2)})
  it('response reader is bounded even without Content-Length',async()=>{const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array(130*1024));c.close()}});const {provider}=setup(vi.fn().mockResolvedValue(new Response(stream)));await expect(provider.search('face pull')).rejects.toMatchObject({code:'video_response_limit'})})
  it('scanner includes video key without changing AIConfig or showing stored form values',()=>{const storage=memory(),profiles=new AiProfiles(storage);storage.setItem(VIDEO_KEY,'synthetic-video-key');expect(profiles.knownSecrets).toContain('synthetic-video-key');expect(storage.getItem('fitlog-ai-config-v1')).toBeNull()})
  it('duplicate call ID searches once, separates typed UI artifacts from model metadata and clear removes them',async()=>{
    const env=aiEnvironment(),profiles=new AiProfiles(memory()),p=profiles.save({name:'A',baseUrl:'https://mock.invalid/v1',model:'chat'},'synthetic-ai-key');profiles.acknowledgePrivacy();profiles.setCapability(p.id,'supported')
    const search=vi.fn().mockResolvedValue(projectVideoResults(raw,3,[])),chat=vi.fn().mockResolvedValueOnce({content:'',toolCalls:[aiCall('search_training_videos',{query:'绳索面拉 教学'},'same'),aiCall('search_training_videos',{query:'绳索面拉 教学'},'same')]}).mockResolvedValueOnce({content:'找到以下动作示范。',toolCalls:[]})
    const engine=new AiOrchestrator({profiles,database:env.database,context:()=>env.context,videoSearch:{search},clientFactory:()=>({chat,chatStream:chat,visionChat:vi.fn(),testConnection:vi.fn(),testToolCapability:vi.fn(),testVisionCapability:vi.fn(),listModels:vi.fn()})})
    try {await engine.send('找那个用绳索往脸拉的动作视频');expect(search).toHaveBeenCalledOnce();expect(search.mock.calls[0]![2]).toBeInstanceOf(AbortSignal);expect(engine.items.filter(item=>item.kind==='videos')).toHaveLength(1);const payload=JSON.stringify(chat.mock.calls[1]![0]);expect(payload).toContain('YouTube Data API');expect(payload).not.toContain('thumbnailUrl');expect(payload).not.toMatch(/iframe|hqdefault.jpg|synthetic-ai-key/);engine.clear();expect(engine.items).toEqual([]);expect(await env.database.dietEvents.count()).toBe(0)}finally{env.database.close();await env.database.delete()}
  })
  it('prompt prefers the real tool and forbids fabricated links/private queries/canonical estimate sums',()=>{const env=aiEnvironment(),prompt=buildFitLogSystemPrompt(env.context);expect(prompt).toContain('search_training_videos');expect(prompt).toContain('永不编造视频链接');expect(prompt).toContain('训练视频搜索尚未配置。');expect(prompt).toContain('绝不能加入实际热量')})
})
