import {describe,it,expect} from 'vitest'
import {readWaterReference,saveWaterReference,WATER_REFERENCE_KEY} from '../src/services/waterReferenceConfig'
import {recoverySummary,sleepMinutes} from '../src/utils/recovery'
import {shiftLocalDate} from '../src/utils/date'
import type {SleepSession,WaterLog} from '../src/db/types'
describe('device-only water reference',()=>{
 it('default is read-only; save and explicit null survive a fresh reader',()=>{const map=new Map<string,string>(),storage={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v)}};expect(readWaterReference(storage)).toBe(2500);expect(map.size).toBe(0);saveWaterReference(2000,storage);expect(map.get(WATER_REFERENCE_KEY)).toBe('{"referenceMl":2000}');expect(readWaterReference(storage)).toBe(2000);saveWaterReference(null,storage);expect(readWaterReference(storage)).toBeNull()})
 it.each([0,-1,1.5,NaN,Infinity,100001])('rejects %s without replacing previous preference',value=>{const map=new Map<string,string>(),s={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v)}};saveWaterReference(2000,s);expect(()=>saveWaterReference(value,s)).toThrow();expect(readWaterReference(s)).toBe(2000)})
 it.each([7,30,90] as const)('includes today and precisely %s local dates, completed only and missing != zero',days=>{const today='2026-11-02',first=shiftLocalDate(today,1-days),stamp='2026-11-01T01:30:00-04:00',end='2026-11-01T02:30:00-05:00',s=(id:string,date:string):SleepSession=>({id,startTime:shiftLocalDate(date,1)+'T02:00:00',endTime:shiftLocalDate(date,1)+'T04:00:00',durationMinutes:sleepMinutes(stamp,end),recordDate:shiftLocalDate(date,1),createdAt:stamp,updatedAt:end}),w=(id:string,date:string,amountMl:number):WaterLog=>({id,date,amountMl,timestamp:stamp,createdAt:stamp,updatedAt:stamp});const r=recoverySummary([s('first',first),s('today',today),s('excluded',shiftLocalDate(first,-1)),{id:'active',startTime:stamp,activeKey:'active',createdAt:stamp,updatedAt:stamp}],[w('a',today,250),w('b',today,500)],today,days);expect(r.daily).toHaveLength(days);expect(r.daily[0]!.date).toBe(first);expect(r.daily.at(-1)!.date).toBe(today);expect(r.recordedDays).toBe(2);expect(r.averageMinutes).toBe(120);expect(r.daily[1]!.minutes).toBeUndefined();expect(r.daily[1]!.waterMl).toBeUndefined();expect(r.daily.at(-1)!.waterMl).toBe(750);expect(Object.keys(r).sort()).toEqual(['averageEnd','averageMinutes','averageStart','daily','recordedDays'])})
})
