import type { CoachReport } from '../services/coachReportService'
import type { CoachFocus, CoachNutrition } from '../utils/coachReportAnalysis'
import type { ExercisePerformance, PerformanceSession } from '../utils/exercisePerformanceAnalysis'
import { formatNumber } from '../utils/nutrition'
import { formatEnergyInputValue } from '../utils/energy'
import { recoveryReportHtml } from './recoveryReport'
import { dailyRecordsHtml } from './dayDetail'
import { bindTrendPointer, nearestTrendPoint } from './trendInteraction'
import { bindVisibleTrendDates, calendarOrdinal } from './trendGeometry'
export interface CoachState {focus:CoachFocus;exercise?:string;metric:'load'|'volume';point?:string}
type Escape=(value:unknown)=>string
const number=(n:number|undefined,unit='')=>n===undefined?'未记录':`${formatNumber(n)}${unit?' '+unit:''}`
const stat=(label:string,value:string,note='')=>`<div class="coach-stat"><span>${label}</span><strong>${value}</strong>${note?`<small>${note}</small>`:''}</div>`
const section=(title:string,body:string,meta='')=>`<section class="report-section coach-section"><div class="coach-head"><h2>${title}</h2>${meta?`<span class="coach-meta">${meta}</span>`:''}</div>${body}</section>`
const statusLabels={first:'建立训练基准',unreliable:'无法可靠比较','no-history':'暂无可比较历史',changed:'负重与次数同时变化',improved:'有同条件进步',stable:'表现持平',declined:'同条件表现下降',mixed:'各条件表现不一致'}
function sessionSummary(s:PerformanceSession|undefined):string {return s?s.highestWeight===undefined?`${s.recordedSets} 组 · 未记录外部负重`:`${number(s.highestWeight,'kg')} × ${s.highestWeightReps} 次`:'尚无记录'}
export function performanceHtml(group:ExercisePerformance,esc:Escape):string {
  const current=group.current,prior=group.baseline??(current?group.history[group.history.indexOf(current)-1]:undefined)
  const change=group.changes.find(c=>c.delta!==0)??group.changes[0]
  const comparable=(s:PerformanceSession|undefined,isCurrent:boolean)=>change&&s?change.kind==='weight'?`${number(isCurrent?change.current:change.previous,'kg')} × ${change.condition} 次`:`${number(change.condition,'kg')} × ${isCurrent?change.current:change.previous} 次`:sessionSummary(s)
  const changes=group.changes.map(c=>`<li>${c.kind==='weight'?`相同 ${c.condition} 次，负重 ${number(c.previous)} → ${number(c.current)} kg，${c.delta>0?'提升':c.delta<0?'下降':'持平'} ${number(Math.abs(c.delta),'kg')}${c.percentage===undefined?'':`（${c.percentage>0?'+':''}${number(c.percentage)}%）`}`:`相同 ${number(c.condition,'kg')}，次数 ${c.previous} → ${c.current}，${c.delta>0?'增加':c.delta<0?'减少':'持平'} ${Math.abs(c.delta)} 次`}</li>`).join('')
  const explanation=group.status==='changed'?'负重与次数的条件发生变化，不能仅凭更高重量判定整体提高。':group.status==='unreliable'?'旧记录的同名动作对应多个身份，不能可靠合并。':group.status==='first'?'首次合格记录建立基准，不计算增长率。':group.status==='no-history'?'缺少可比较的有效外部负重数据。':group.status==='mixed'?'部分条件提高、部分下降，分别阅读各项变化。':'同动作、同条件比较；不等同于整体力量或身体成分变化。'
  const records=group.records.filter(r=>r.newRecord).map(r=>`<li>${r.kind==='load'?`历史最高已记录负重 ${number(r.current,'kg')}（非1RM）`:r.kind==='weight'?`同 ${r.condition} 次历史最佳负重 ${number(r.current,'kg')}`:`同 ${number(r.condition,'kg')} 历史最佳次数 ${r.current} 次`}</li>`).join('')
  return `<div class="coach-compare"><div class="coach-comp-tile"><small>${group.baseline?'比较基准':'此前记录'}</small><time>${esc(prior?.date??'无')}</time><strong>${comparable(prior,false)}</strong><em>${group.baseline?'同条件最佳组':'最高已记录组'}</em></div><span class="coach-comp-arrow" aria-hidden="true">→</span><div class="coach-comp-tile"><small>本次</small><time>${esc(current?.date??'本期无记录')}</time><strong>${comparable(current,true)}</strong><em>${group.baseline?'同条件最佳组':'最高已记录组'}</em></div></div><div class="coach-insight ${group.status==='improved'?'up':'muted'}"><b data-performance-status>${statusLabels[group.status]}</b>${changes?`<ul>${changes}</ul>`:''}<p>${explanation}</p></div>${records?`<details class="coach-records"><summary>刷新历史表现纪录</summary><ul>${records}</ul></details>`:''}${current?`<p class="coach-note">本次 ${current.recordedSets} 个有效记录组；${current.weightedSets} 组可计算外部负重；${current.omittedSets} 组无效记录已排除。总负荷 ${number(current.volume,'kg·次')}。</p>`:''}`
}
export interface CoachPlotPoint {id:string;date:string;value:number;detail:string}
export function coachPlotHtml(points:CoachPlotPoint[],selectedId:string|undefined,title:string,esc:Escape):string {
  if(!points.length)return '<p class="coach-note">暂无可计算的记录，缺失数据不作为零。</p>'
  const first=calendarOrdinal(points[0]!.date),positions:number[]=[]
  for(const p of points)positions.push(36+(calendarOrdinal(p.date)-first)*44)
  const width=Math.max(280,positions.at(-1)!+36),height=162,minimum=Math.min(...points.map(p=>p.value)),maximum=Math.max(...points.map(p=>p.value)),pad=Math.max((maximum-minimum)*.2,maximum*.025,1),low=Math.max(0,minimum-pad),high=maximum+pad
  const mapped=points.map((p,i)=>({...p,x:positions[i]!,y:120-(p.value-low)/(high-low)*100})),selected=mapped.find(p=>p.id===selectedId)??mapped.at(-1)!
  return `<div class="coach-plot" data-coach-plot><div class="coach-graph-title"><b>${title}</b><span data-coach-readout role="status" aria-live="polite">${esc(selected.date)} · ${esc(selected.detail)}</span></div><div class="trend-visual"><div class="trend-plot-frame"><div class="trend-y-axis" aria-hidden="true">${[high,(high+low)/2,low].map((n,i)=>`<span style="top:${[20,70,120][i]!/162*100}%">${number(n)}</span>`).join('')}</div><div class="trend-chart-shell coach-chart-scroll"><svg class="coach-graph" viewBox="0 0 ${width} ${height}" style="min-width:${width/16}rem" role="group" aria-label="${esc(title)}，实际日期，方向键选择记录">${[20,70,120].map(y=>`<line class="trend-grid" x1="0" x2="${width}" y1="${y}" y2="${y}"/>`).join('')}<polyline class="recovery-line-path" points="${mapped.map(p=>`${p.x},${p.y}`).join(' ')}"/><line class="recovery-selection-line" data-coach-locator x1="${selected.x}" x2="${selected.x}" y1="20" y2="120"/>${mapped.map((p,i)=>`<g data-coach-point="${esc(p.id)}" data-x="${p.x}" data-y="${p.y}" data-detail="${esc(p.date+' · '+p.detail)}" role="button" aria-label="${esc(p.date+' · '+p.detail)}" tabindex="${p.id===selected.id?0:-1}" aria-pressed="${p.id===selected.id}" class="${p.id===selected.id?'is-selected':''}"><circle class="recovery-line-hit" cx="${p.x}" cy="${p.y}" r="22"/><circle class="recovery-line-marker" cx="${p.x}" cy="${p.y}" r="3.5"/>${mapped.findIndex(q=>q.date===p.date)===i?`<text class="recovery-point-date" x="${p.x}" y="150" text-anchor="middle">${Number(p.date.slice(5,7))}/${Number(p.date.slice(8))}</text>`:''}</g>`).join('')}</svg></div></div></div></div>`
}
export function bindCoachPlots(host:HTMLElement,onSelect:(id:string)=>void):()=>void {
  const events=new AbortController(),choices=host.querySelector<HTMLElement>('.coach-exercise-switch'),active=choices?.querySelector<HTMLElement>('[aria-pressed=true]');if(choices&&active){const reveal=()=>{const row=choices.getBoundingClientRect(),item=active.getBoundingClientRect();choices.scrollLeft+=item.left-row.left-(choices.clientWidth-item.width)/2};reveal();const resize=new ResizeObserver(reveal);resize.observe(choices);events.signal.addEventListener('abort',()=>resize.disconnect(),{once:true})}
  for(const plot of host.querySelectorAll<HTMLElement>('[data-coach-plot]')){
    const svg=plot.querySelector<SVGSVGElement>('svg')!,scroll=plot.querySelector<HTMLElement>('.coach-chart-scroll')!,points=[...svg.querySelectorAll<SVGElement>('[data-coach-point]')]
    const select=(point:SVGElement,focus=false)=>{for(const p of points){const selected=p===point;p.classList.toggle('is-selected',selected);p.setAttribute('aria-pressed',String(selected));p.setAttribute('tabindex',selected?'0':'-1')}plot.querySelector('[data-coach-readout]')!.textContent=point.dataset.detail!;const line=plot.querySelector('[data-coach-locator]')!;line.setAttribute('x1',point.dataset.x!);line.setAttribute('x2',point.dataset.x!);onSelect(point.dataset.coachPoint!);if(focus){point.focus({preventScroll:true});scroll.scrollLeft=Number(point.dataset.x)*parseFloat(getComputedStyle(document.documentElement).fontSize)/16-scroll.clientWidth/2}}
    const stop=bindTrendPointer(svg,scroll,(x,y)=>{const m=svg.getScreenCTM();if(!m)return;const screen=(x:number,y:number)=>new DOMPoint(x,y).matrixTransform(m),index=nearestTrendPoint(points.map(p=>screen(Number(p.dataset.x),Number(p.dataset.y))),x,y,{top:screen(0,20).y,bottom:screen(0,120).y});if(index!==undefined)select(points[index]!)})
    events.signal.addEventListener('abort',stop,{once:true});plot.addEventListener('click',e=>{if(e.detail===0){const p=(e.target as Element).closest<SVGElement>('[data-coach-point]');if(p)select(p)}},{signal:events.signal})
    plot.addEventListener('keydown',e=>{const p=(e.target as Element).closest<SVGElement>('[data-coach-point]');if(!p)return;const i=points.indexOf(p),next=e.key==='ArrowLeft'?Math.max(0,i-1):e.key==='ArrowRight'?Math.min(points.length-1,i+1):e.key==='Home'?0:e.key==='End'?points.length-1:e.key==='Enter'||e.key===' '?i:undefined;if(next!==undefined){e.preventDefault();select(points[next]!,true)}},{signal:events.signal})
    scroll.scrollLeft=scroll.scrollWidth-scroll.clientWidth;bindVisibleTrendDates(svg,scroll,events.signal)
  }
  return()=>events.abort()
}
function nutritionHtml(n:Record<'calories'|'protein'|'carbs'|'fat',CoachNutrition>,foodDays:number,days:number,daily=false):string {
  const labels={calories:'热量',protein:'蛋白质',carbs:'碳水',fat:'脂肪'}
  return section('饮食与营养执行',`<div class="coach-mini-grid">${stat('饮食记录覆盖',`${foodDays} / ${days} 天`,'未记录不作为零摄入')}${stat('热量完整记录',`${n.calories.completeDays} 天`,`${n.calories.partialDays} 天记录不完整`)}</div><div class="coach-nutrition">${Object.entries(labels).map(([key,label])=>{const m=n[key as keyof typeof n],unit=key==='calories'?'kcal':'g',show=(value:number|undefined,suffix='')=>value===undefined?'未记录':(key==='calories'?formatEnergyInputValue(value):formatNumber(value))+(suffix?' '+suffix:'');return `<article class="coach-nutrient"><div><strong>${label}</strong><span>${show(m.actual,unit)}</span></div><small>${daily?'当天实际摄入':'完整记录日平均'} · ${m.completeDays} 天；部分记录 ${m.partialDays} 天</small>${m.target===undefined?'<small>未设置同日有效目标</small>':`<small>同日配对 ${m.matchedDays} 天：${show(m.pairedActual)} / ${show(m.target,unit)} · 目标比例 ${number(m.achievement)}%</small><div class="coach-meter" role="img" aria-label="${label}同日目标比例 ${number(m.achievement)}%"><i style="width:${Math.min(100,m.achievement??0)}%"></i></div>`}${m.gkg===undefined?'':`<small>${m.gkg.toFixed(2)} g/kg</small>`}</article>`}).join('')}</div><p class="coach-note">比较用户保存的同日目标；记录低于目标不代表确定热量赤字，蛋白质达标不等于必然增肌。</p>`)
}
export function coachReportHtml(data:CoachReport,state:CoachState,mode:'day'|'week'|'month',esc:Escape):string {
  const {report,analysis:a}=data,focus=state.focus,groups=a.groups,group=groups.find(g=>g.key===state.exercise)??groups.find(g=>g.current)??groups[0]
  const focusHtml=`<div class="coach-focus" role="group" aria-label="分析关注点">${([['all','综合'],['strength','力量'],['hypertrophy','增肌'],['fat-loss','减脂']] as const).map(([key,label])=>`<button data-coach-focus="${key}" aria-pressed="${focus===key}">${label}</button>`).join('')}</div>`
  const intro=`<div class="coach-intro"><h2>${mode==='day'?'当天实际记录':mode==='week'?'本周表现与执行':'本月发展与执行'}</h2><p>从真实记录看训练表现、营养与恢复；缺失信息保持未知。</p></div>${focusHtml}`
  const overview=section(mode==='day'?'当天重点':'本期训练概览',`<div class="coach-overview">${stat('力量训练',`${a.training.days} 天`,`${a.training.sessions} 次已完成训练`)}${stat('力量记录组',`${a.training.recordedSets} 组`,'尚未区分热身与工作组')}${stat('本期可比动作',`${groups.filter(g=>g.current&&g.baseline).length} 项`,'基准可来自周期之前')}${stat('饮食记录',`${a.foodDays} / ${a.elapsedDays} 天`,'仅代表记录覆盖')}</div>`)
  const performance=group?section('动作表现与进步',`<p class="coach-description">同一个动作、同次数或同负重比较，历史名称保留快照。</p><div class="coach-exercise-switch" role="group" aria-label="选择动作">${groups.map(g=>`<button data-coach-exercise="${esc(g.key)}" aria-pressed="${g===group}">${esc(g.name)}${g.current?'':' · 本期无记录'}</button>`).join('')}</div>${group.current?performanceHtml(group,esc):'<p class="coach-note">本期无合格训练，下面显示已有真实历史。</p>'}${mode==='day'?'':`<div class="coach-trend-mode" role="group" aria-label="动作趋势指标"><button data-coach-chart="load" aria-pressed="${state.metric==='load'}">最高负重</button><button data-coach-chart="volume" aria-pressed="${state.metric==='volume'}">记录总负荷</button></div>${coachPlotHtml(group.history.flatMap(s=>{const value=state.metric==='load'?s.highestWeight:s.volume;return value===undefined?[]:[{id:s.workoutId,date:s.date,value,detail:`完成 ${new Date(s.finishedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}；最高负重 ${number(s.highestWeight,'kg')} × ${s.highestWeightReps??'未知'} 次；记录总负荷 ${number(s.volume,'kg·次')}`}]}),state.point,state.metric==='load'?'每次最高已记录负重':'每次动作记录总负荷',esc)}`}<p class="coach-note">总负荷 = Σ(外部重量 × 次数)，不代表肌肉增长或能量消耗；不可跨动作评判好坏。</p><button type="button" class="coach-link text-btn" data-coach-history="${esc(group.key)}">查看该动作逐次训练明细 ${'›'}</button>`):section('动作表现与进步','<p class="coach-note">暂无已完成的合格动作记录，不能判定训练进步。</p>')
  const frequency=section('训练频率与训练量',mode==='month'?`<div class="coach-weekly-training">${a.weeklyTraining.filter(w=>w.start<=(report.days.filter(d=>!d.future).at(-1)?.date??'')).map(w=>`<div><span>${esc(w.label)}</span><strong>${w.start>(report.days.filter(d=>!d.future).at(-1)?.date??'')?'未来日期':`${w.days} 天 · ${w.recordedSets} 组`}</strong><small>${w.start>(report.days.filter(d=>!d.future).at(-1)?.date??'')?'尚未到来，不作未完成判断':`${w.sessions} 次力量训练；记录总负荷 ${number(w.volume,'kg·次')}`}</small></div>`).join('')}</div><p class="coach-note">总负荷仅汇总记录工作，不比较不同动作质量。</p>`:`<div class="coach-frequency">${report.days.map((d,i)=>{const active=a.training.dates.includes(d.date);return `<div><span class="coach-freq-dot ${active?'done':''} ${d.future?'future':''}">${d.future?'—':active?'✓':'·'}</span><small>${'一二三四五六日'[i]}</small></div>`}).join('')}</div><div class="coach-mini-grid">${stat('力量记录组',`${a.training.recordedSets} 组`,`${a.training.weightedSets} 组有负重，排除 ${a.training.omittedSets} 组无效数据`)}${stat('有氧累计时长',number(report.summary.cardioMinutes,'分钟'),`${report.summary.cardioSessions} 次真实记录；凯格尔 ${report.summary.pelvicSessions} 次`)}</div><p class="coach-note">无记录不等同于没有训练；尚不能区分热身或增肌有效工作组。</p>`)
  const first=a.weights[0],last=a.weights.at(-1),weight=section('体重与减脂观察',first?`<div class="coach-mini-grid">${stat('区间首次记录',number(first.weightKg,'kg'),esc(first.date))}${stat('区间末次记录',number(last?.weightKg,'kg'),esc(last?.date??''))}</div>${a.weights.length>1?coachPlotHtml(a.weights.map(w=>({id:'weight:'+w.id,date:w.date,value:w.weightKg,detail:number(w.weightKg,'kg')})),undefined,'实际体重记录',esc):''}<p class="coach-note">${new Set(a.weights.map(w=>w.date)).size} 天有记录；${a.weightDelta===undefined?'记录不足，无法判断趋势':`首末变化 ${a.weightDelta>0?'+':''}${number(a.weightDelta,'kg')}`}。体重变化不等于脂肪或肌肉变化。</p>`:'<p class="coach-note">暂无体重记录，不能推断体脂或体重变化。</p>')
  const habits=a.habits.length?section('习惯执行',`<div class="coach-habit-list">${a.habits.map(h=>`<article><div class="coach-habit-head"><strong>${esc(h.habit.name)}</strong><span>${h.count} 次实际打卡</span></div>${mode==='week'?`<div class="coach-seven">${h.cells.map((c,i)=>`<div><small>${'一二三四五六日'[i]}</small><span class="coach-habit-cell ${c}" aria-label="${report.days[i]!.date}，${{done:'已打卡',missing:'计划日未打卡',off:'非指定计划日',future:'未来',before:'尚未创建',unknown:'历史计划未知'}[c]}">${{done:'✓',missing:'○',off:'·',future:'—',before:'—',unknown:'?'}[c]}</span></div>`).join('')}</div>`:`<div class="coach-habit-weeks">${h.weeks.map(w=>`<div class="${w.achieved?'achieved':''}"><small>${esc(w.label)}</small><b>${w.future?'—':`${w.completed}${w.target===undefined?' 次':` / ${w.target}`}`}</b>${w.ratio===undefined?'':`<div class="coach-meter" role="img" aria-label="${w.completed} / ${w.target}，${w.achieved?'已达周目标':'当前完成'}"><i style="width:${w.ratio*100}%"></i></div>`}<small>${w.future?'未来日期':w.target===undefined?'无可靠历史目标':w.achieved?'已达周目标':w.partial?'周期尚不完整':'实际周目标'}${w.future?'':w.partial?' · 部分周':''}${w.completed!==w.periodCompleted?' · 含跨月打卡':''}</small></div>`).join('')}</div>`}<p class="coach-note">${h.habit.targetPerWeek?`当前周目标 ${h.habit.targetPerWeek} 次；计次数不指定每天必做。`:h.habit.weekdays?.length?'按指定星期计划统计。':'自由打卡，无目标比例。'}${!h.habit.active?'已停用；历史打卡保留。':''}</p></article>`).join('')}</div><p class="coach-note">✓ 已打卡 · ○ 计划日未打卡 · · 非指定计划日 · — 未来/尚未创建 · ? 历史计划未知。按自然周累计，跨月打卡明确标注；计划变更无快照时不反推历史要求。</p>`):''
  if(mode==='day')return `<div class="coach-report" data-coach-reading="${focus}">${intro}${overview}${group?.current&&group.baseline?performance:''}${nutritionHtml(a.nutrition,a.foodDays,a.elapsedDays,true)}<div class="coach-day-facts">${dailyRecordsHtml(report.daily!,esc)}</div></div>`
  return `<div class="coach-report" data-coach-reading="${focus}">${intro}${overview}${focus==='fat-loss'?weight+nutritionHtml(a.nutrition,a.foodDays,a.elapsedDays)+performance+frequency:focus==='strength'?performance+frequency:focus==='hypertrophy'?performance+frequency+nutritionHtml(a.nutrition,a.foodDays,a.elapsedDays)+recoveryReportHtml(report):performance+frequency+weight+nutritionHtml(a.nutrition,a.foodDays,a.elapsedDays)+habits+recoveryReportHtml(report)}${focus==='all'?'':`<p class="coach-note">当前为${{strength:'力量',hypertrophy:'增肌', 'fat-loss':'减脂'}[focus]}阅读重点；切换综合查看同一批完整记录。</p>`}</div>`
}
export function exerciseHistoryHtml(group:ExercisePerformance,esc:Escape):string {
 return `<div class="coach-history">${group.history.toReversed().map(s=>`<article><h3>${esc(s.date)} · ${esc(s.name)}</h3><p class="coach-note">${s.recordedSets} 组 · 总负荷 ${number(s.volume,'kg·次')}；${s.weightedSets} 组可计算，排除 ${s.omittedSets} 无效组。</p><ol>${s.sets.map(set=>`<li>${set.weightKg===undefined?'未记录负重':number(set.weightKg,'kg')} × ${set.reps} 次${set.rpe===undefined?'':` · 历史 RPE ${esc(set.rpe)}`}${set.note?`<p>${esc(set.note)}</p>`:''}</li>`).join('')}</ol></article>`).join('')}</div>`
}
