import { Chart } from 'chart.js'
import type { WeightLog } from '../db/types'
import { formatNumber } from '../utils/nutrition'
import { nearestTrendPoint, bindTrendPointer } from './trendInteraction'
import { trendEmptyHtml, trendDateLabel } from './trendModule'
import { calendarOrdinal, trendScale, trendYLabels } from './trendGeometry'
import type { ReportRange } from '../utils/reporting'
function geometry(actual:WeightLog[],range?:ReportRange){
 const start=range?.start??actual[0]?.date,end=range?.end??actual.at(-1)?.date,from=start?calendarOrdinal(start):0,span=end?calendarOrdinal(end)-from:0
 const x=actual.map(w=>calendarOrdinal(w.date)-from),width=Math.max(280,span*44+72)
 return{start,span,x,width,...trendScale(actual.map(w=>w.weightKg),'weight')}
}
export function weightChartHtml(actual:WeightLog[],selectedId?:string,canvasId='weight-chart',range?:ReportRange):string {
 const selected=actual.find(w=>w.id===selectedId)??actual.at(-1);if(!selected)return trendEmptyHtml('体重')
 const g=geometry(actual,range)
 return `<div class="chart-selection" role="status" aria-live="polite"><strong data-weight-chart-value>${formatNumber(selected.weightKg)} <span class="trend-unit">kg</span></strong><span data-weight-chart-date>${trendDateLabel(selected.date)}</span></div><div class="trend-visual"><div class="trend-visual-head"><b>体重实际记录</b><span>${new Set(actual.map(w=>w.date)).size} 天有记录 · kg</span></div><div class="trend-plot-frame">${trendYLabels(g.low,g.high,formatNumber)}<div class="weight-chart-scroll trend-chart-shell" role="region" aria-label="体重趋势，左右滚动查看日期"><div class="weight-chart-canvas weight-chart-track" style="min-width:${g.width/16}rem"><div class="weight-chart-window"><canvas data-weight-positions="${g.x.map(day=>36+day*44).join(',')}" data-weight-chart id="${canvasId}" tabindex="0" role="img" aria-label="体重实际记录，方向键选择日期"></canvas></div></div></div></div><p class="trend-plot-help">点选查看完整日期与读数；日期按实际间隔排列，可左右滚动。</p></div>`
}
export function mountWeightChart(root:HTMLElement,actual:WeightLog[],selectedId:string|undefined,onSelection:(id:string)=>void,range?:ReportRange):()=>void {
 const canvas=root.querySelector<HTMLCanvasElement>('canvas[data-weight-chart]');if(!canvas)return()=>{}
 const styles=getComputedStyle(document.documentElement),ink=styles.getPropertyValue('--weight').trim(),muted=styles.getPropertyValue('--text-secondary').trim(),g=geometry(actual,range),scroll=root.querySelector<HTMLElement>('.weight-chart-scroll')!,canvasWindow=root.querySelector<HTMLElement>('.weight-chart-window')!
 let scale=parseFloat(styles.fontSize)/16,fontSize=13*scale
 canvasWindow.style.width=scroll.clientWidth+'px'
 let selected=actual.find(w=>w.id===selectedId)??actual.at(-1)!,chart:Chart<'line',{x:number;y:number}[],string>
 const select=(i:number,ensure=false)=>{selected=actual[i]!;onSelection(selected.id);const value=root.querySelector('[data-weight-chart-value]')!;value.replaceChildren(document.createTextNode(formatNumber(selected.weightKg)+' '));const unit=document.createElement('span');unit.className='trend-unit';unit.textContent='kg';value.append(unit);root.querySelector('[data-weight-chart-date]')!.textContent=trendDateLabel(selected.date);canvas.setAttribute('aria-label',`${selected.date}，${formatNumber(selected.weightKg)} kg，方向键切换`);canvas.dataset.selectedId=selected.id;chart.data.datasets[0]!.pointRadius=actual.map(w=>w.id===selected.id?6*scale:3.5*scale);chart.update('none');if(ensure){scroll.scrollLeft=(36+g.x[i]!*44)*scale-scroll.clientWidth/2;updateWindow()}else {canvas.dataset.selectedX=String(chart.getDatasetMeta(0).data[i]!.x);canvas.dataset.selectedY=String(chart.getDatasetMeta(0).data[i]!.y)}}
 chart=new Chart(canvas,{type:'line',data:{datasets:[{data:actual.map((w,i)=>({x:g.x[i]!,y:w.weightKg})),borderColor:ink,pointBackgroundColor:ink,pointBorderColor:styles.getPropertyValue('--surface').trim(),pointBorderWidth:2*scale,pointRadius:actual.map(w=>w.id===selected.id?6*scale:3.5*scale),borderWidth:2*scale,clip:false,fill:false,tension:0}]},plugins:[{id:'selected-factual-point',beforeDatasetsDraw(c){const ctx=c.ctx;ctx.save();ctx.strokeStyle=styles.getPropertyValue('--divider').trim();ctx.lineWidth=scale;for(const y of [20,70,120]){ctx.beginPath();ctx.moveTo(0,y*scale);ctx.lineTo(c.width,y*scale);ctx.stroke()}ctx.restore()},afterDraw(c){const meta=c.getDatasetMeta(0),i=actual.findIndex(w=>w.id===selected.id),p=meta.data[i];if(!p)return;const ctx=c.ctx;ctx.save();ctx.strokeStyle=ink;ctx.lineWidth=scale;ctx.setLineDash([3*scale,4*scale]);ctx.beginPath();ctx.moveTo(p.x,20*scale);ctx.lineTo(p.x,120*scale);ctx.stroke();ctx.setLineDash([]);ctx.font=`${fontSize}px ${styles.fontFamily}`;ctx.textAlign='center';ctx.fillStyle=muted;const step=Math.max(1,Math.ceil(scroll.clientWidth/(44*scale)/5));for(let n=Math.max(0,Math.floor((scroll.scrollLeft/scale-36)/44));n<=Math.min(g.span,Math.ceil((scroll.scrollLeft+scroll.clientWidth)/scale/44));n++){if(n%step&&n!==g.span)continue;const d=new Date((calendarOrdinal(g.start!)+n)*86400000),date=`${d.getUTCMonth()+1}/${d.getUTCDate()}`,px=c.scales.x!.getPixelForValue(n),scroll=root.querySelector<HTMLElement>('.weight-chart-scroll')!,half=ctx.measureText(date).width/2;if(px-half>=4&&px+half<=scroll.clientWidth-4)ctx.fillText(date,px,150*scale)}ctx.restore()}}],options:{responsive:true,maintainAspectRatio:false,animation:false,events:[],layout:{padding:{top:20*scale,bottom:42*scale,left:0,right:0}},plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{type:'linear',display:false,min:-36/44,max:(scroll.clientWidth/scale-36)/44},y:{display:false,min:g.low,max:g.high}}}})
 const updateWindow=()=>{scale=parseFloat(getComputedStyle(document.documentElement).fontSize)/16;fontSize=13*scale;canvasWindow.style.width=scroll.clientWidth+'px';chart.options.layout!.padding={top:20*scale,bottom:42*scale,left:0,right:0};chart.options.scales!.x!.min=(scroll.scrollLeft/scale-36)/44;chart.options.scales!.x!.max=((scroll.scrollLeft+scroll.clientWidth)/scale-36)/44;const ds=chart.data.datasets[0]!;ds.pointRadius=actual.map(w=>w.id===selected.id?6*scale:3.5*scale);ds.borderWidth=2*scale;ds.pointBorderWidth=2*scale;chart.resize();chart.update('none');canvas.dataset.windowScroll=String(scroll.scrollLeft);canvas.dataset.selectedY=String(chart.getDatasetMeta(0).data[actual.indexOf(selected)]!.y);canvas.dataset.selectedX=String(chart.getDatasetMeta(0).data[actual.indexOf(selected)]!.x)}
 const stopPointer=bindTrendPointer(canvas,scroll,(px,py)=>{const r=canvas.getBoundingClientRect(),sx=r.width/chart.width,sy=r.height/chart.height,points=chart.getDatasetMeta(0).data.map(p=>({x:r.left+p.x*sx,y:r.top+p.y*sy}));const visible=points.map((p,i)=>({p,i})).filter(({p})=>p.x>=r.left&&p.x<=r.right);const picked=nearestTrendPoint(visible.map(v=>v.p),px,py,{top:r.top+20*scale*sy,bottom:r.top+120*scale*sy});if(picked!==undefined)select(visible[picked]!.i)})
 const events=new AbortController();scroll.addEventListener('scroll',updateWindow,{passive:true,signal:events.signal});const resize=new ResizeObserver(updateWindow);resize.observe(scroll);canvas.addEventListener('keydown',e=>{const i=actual.findIndex(w=>w.id===selected.id),next=e.key==='Home'?0:e.key==='End'?actual.length-1:e.key==='ArrowLeft'?Math.max(0,i-1):e.key==='ArrowRight'?Math.min(actual.length-1,i+1):e.key==='Enter'||e.key===' '?i:undefined;if(next!==undefined){e.preventDefault();select(next,true)}},{signal:events.signal});select(actual.indexOf(selected),true);return()=>{resize.disconnect();stopPointer();events.abort();chart.destroy()}
}
