import { Chart } from 'chart.js'
import type { WeightLog } from '../db/types'
import { formatNumber } from '../utils/nutrition'
import { nearestTrendPoint, bindTrendPointer, sparseLabelIndexes } from './trendInteraction'
import { trendEmptyHtml, trendDateLabel } from './trendModule'
export function weightChartHtml(actual:WeightLog[],selectedId?:string, canvasId = "weight-chart"):string {
 const selected=actual.find(w=>w.id===selectedId)??actual.at(-1)
 return selected?`<div class="chart-selection" role="status" aria-live="polite"><strong data-weight-chart-value>${formatNumber(selected.weightKg)} <span class="trend-unit">kg</span></strong><span data-weight-chart-date>${trendDateLabel(selected.date)}</span></div><div class="weight-chart-scroll trend-chart-shell ${actual.length<=3?'is-sparse':''}" role="region" aria-label="体重趋势，左右滚动查看日期"><div class="weight-chart-canvas" style="min-width:${Math.max(280,actual.length*44+72)/16}rem"><canvas data-weight-chart id="${canvasId}" tabindex="0" role="img" aria-label="体重实际记录，方向键选择日期"></canvas></div></div>`:trendEmptyHtml('体重')
}
export function mountWeightChart(root:HTMLElement,actual:WeightLog[],selectedId:string|undefined,onSelection:(id:string)=>void):()=>void {
 const canvas=root.querySelector<HTMLCanvasElement>('canvas[data-weight-chart]');if(!canvas)return()=>{}
 const styles=getComputedStyle(document.documentElement),ink=styles.getPropertyValue('--weight').trim(),muted=styles.getPropertyValue('--text-secondary').trim(),fontSize=parseFloat(styles.fontSize)*.8125
 // Space actual observations evenly so a year-old point cannot collapse adjacent recent dates.
 const x=actual.map((_w,index)=>index)
 let selected=actual.find(w=>w.id===selectedId)??actual.at(-1)!,chart:Chart<'line',{x:number;y:number}[],string>
 const select=(i:number,ensure=false)=>{selected=actual[i]!;onSelection(selected.id);const value=root.querySelector('[data-weight-chart-value]')!;value.replaceChildren(document.createTextNode(formatNumber(selected.weightKg)+' '));const unit=document.createElement('span');unit.className='trend-unit';unit.textContent='kg';value.append(unit);root.querySelector('[data-weight-chart-date]')!.textContent=trendDateLabel(selected.date);canvas.setAttribute('aria-label',`${selected.date}，${formatNumber(selected.weightKg)} kg，方向键切换`);canvas.dataset.selectedId=selected.id;chart.data.datasets[0]!.pointRadius=actual.map(w=>w.id===selected.id?6:3.5);chart.update('none');if(ensure){const p=chart.getDatasetMeta(0).data[i]!,scroll=root.querySelector<HTMLElement>('.weight-chart-scroll')!;scroll.scrollLeft=p.x-scroll.clientWidth/2}}
 chart=new Chart(canvas,{type:'line',data:{datasets:[{data:actual.map((w,i)=>({x:x[i]!,y:w.weightKg})),borderColor:ink,pointBackgroundColor:ink,pointBorderColor:styles.getPropertyValue('--surface').trim(),pointBorderWidth:2,pointRadius:actual.map(w=>w.id===selected.id?6:3.5),borderWidth:2,fill:false,tension:.18}]},plugins:[{id:'selected-factual-point',afterDraw(c){const meta=c.getDatasetMeta(0),i=actual.findIndex(w=>w.id===selected.id),p=meta.data[i];if(!p)return;const ctx=c.ctx;ctx.save();ctx.strokeStyle=ink;ctx.lineWidth=1;ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(p.x,c.chartArea.top);ctx.lineTo(p.x,c.chartArea.bottom);ctx.stroke();ctx.setLineDash([]);ctx.font=`${fontSize}px ${styles.fontFamily}`;ctx.textAlign='center';ctx.fillStyle=muted;const labels=actual.map(w=>formatNumber(w.weightKg)+' kg');for(const index of sparseLabelIndexes(meta.data,labels,c.width,fontSize)){const point=meta.data[index]!;ctx.fillText(labels[index]!,point.x,Math.max(c.chartArea.top+fontSize,point.y-fontSize))}ctx.restore()}}],options:{responsive:true,maintainAspectRatio:false,animation:false,events:[],layout:{padding:{top:actual.length<=3?fontSize+4:4,left:8,right:fontSize*3}},plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{type:'linear',min:actual.length===1?-.5:0,max:actual.length===1?.5:actual.length-1,grid:{display:false},ticks:{color:muted,font:{size:fontSize},maxTicksLimit:actual.length<=3?3:7,precision:0,callback:value=>{const date=actual[Number(value)]?.date;return date?`${Number(date.slice(5,7))}/${Number(date.slice(8))}`:''}}},y:{grid:{color:styles.getPropertyValue('--divider').trim()},ticks:{color:muted,font:{size:fontSize},maxTicksLimit:3}}}}})
 const scroll=root.querySelector<HTMLElement>('.weight-chart-scroll')!,stopPointer=bindTrendPointer(canvas,scroll,(px,py)=>{const r=canvas.getBoundingClientRect(),sx=r.width/chart.width,sy=r.height/chart.height,points=chart.getDatasetMeta(0).data.map(p=>({x:r.left+p.x*sx,y:r.top+p.y*sy}));const index=nearestTrendPoint(points,px,py,{top:r.top+chart.chartArea.top*sy,bottom:r.top+chart.chartArea.bottom*sy});if(index!==undefined)select(index)})
 const events=new AbortController();canvas.addEventListener('keydown',e=>{const i=actual.findIndex(w=>w.id===selected.id),next=e.key==='Home'?0:e.key==='End'?actual.length-1:e.key==='ArrowLeft'?Math.max(0,i-1):e.key==='ArrowRight'?Math.min(actual.length-1,i+1):e.key==='Enter'||e.key===' '?i:undefined;if(next!==undefined){e.preventDefault();select(next,true)}},{signal:events.signal});select(actual.indexOf(selected));return()=>{stopPointer();events.abort();chart.destroy()}
}
